package allowlistgen

import (
	"fmt"
	"sort"
	"strings"
	"time"

	goyaml "github.com/goccy/go-yaml"
	"github.com/whereiskurt/klankrmkr/pkg/profile"
	"golang.org/x/net/publicsuffix"
)

// Generate produces a minimal SandboxProfile from the Recorder's observed
// traffic. It applies the HTTPS-implies-DNS rule: every observed host
// contributes its eTLD+1 suffix to AllowedDNSSuffixes, and any host already
// covered by a suffix is omitted from AllowedHosts.
//
// base is an optional profile name to set in the Extends field (pass "" to omit).
//
// The returned profile includes sensible scaffold defaults for all required
// spec fields (lifecycle, runtime, execution, identity, sidecars, observability,
// agent). Review and customise before using in production.
func (r *Recorder) Generate(base string) (*profile.SandboxProfile, error) {
	// Use the accessor methods — each acquires the mutex independently.
	dns := r.DNSDomains()
	hosts := r.Hosts()
	repos := r.Repos()

	// HTTPS-implies-DNS: union DNS domains and observed hosts before collapsing.
	allDomains := unionStrings(dns, hosts)

	suffixes := CollapseToDNSSuffixes(allDomains)
	remainingHosts := deduplicateHosts(hosts, suffixes)

	// Build empty slices rather than nil so YAML emits [] not null.
	if suffixes == nil {
		suffixes = []string{}
	}
	if remainingHosts == nil {
		remainingHosts = []string{}
	}

	p := &profile.SandboxProfile{
		APIVersion: "klankermaker.ai/v1alpha1",
		Kind:       "SandboxProfile",
		Metadata: profile.Metadata{
			Name: "observed-" + time.Now().Format("20060102-150405"),
		},
		Extends: base,
		Spec: profile.Spec{
			Lifecycle: profile.LifecycleSpec{
				TTL:            "8h",
				IdleTimeout:    "2h",
				TeardownPolicy: "destroy",
			},
			Runtime: profile.RuntimeSpec{
				Substrate:    "ec2",
				InstanceType: "t3.medium",
				Region:       "us-east-1",
			},
			Execution: profile.ExecutionSpec{
				Shell:      "/bin/bash",
				WorkingDir: "/workspace",
			},
			SourceAccess: profile.SourceAccessSpec{
				Mode: "allowlist",
			},
			Network: profile.NetworkSpec{
				Egress: profile.EgressSpec{
					AllowedDNSSuffixes: suffixes,
					AllowedHosts:       remainingHosts,
				},
			},
			Identity: profile.IdentitySpec{
				RoleSessionDuration: "1h",
				AllowedRegions:      []string{"us-east-1"},
				SessionPolicy:       "minimal",
			},
			Sidecars: profile.SidecarsSpec{
				DNSProxy:  profile.SidecarConfig{Enabled: true, Image: "km-dns-proxy:latest"},
				HTTPProxy: profile.SidecarConfig{Enabled: true, Image: "km-http-proxy:latest"},
				AuditLog:  profile.SidecarConfig{Enabled: true, Image: "km-audit-log:latest"},
				Tracing:   profile.SidecarConfig{Enabled: true, Image: "km-tracing:latest"},
			},
			Observability: profile.ObservabilitySpec{
				CommandLog: profile.LogDestination{
					Destination: "cloudwatch",
					LogGroup:    "/klankrmkr/sandboxes",
				},
				NetworkLog: profile.LogDestination{
					Destination: "cloudwatch",
					LogGroup:    "/klankrmkr/network",
				},
			},
			Agent: profile.AgentSpec{
				MaxConcurrentTasks: 1,
				TaskTimeout:        "30m",
			},
		},
	}

	// Attach GitHub access when repos or refs were observed.
	refs := r.Refs()
	if len(repos) > 0 || len(refs) > 0 {
		gh := &profile.GitHubAccess{}
		if len(repos) > 0 {
			gh.AllowedRepos = repos
		}
		if len(refs) > 0 {
			gh.AllowedRefs = refs
		}
		p.Spec.SourceAccess.GitHub = gh
	}

	// Populate InitCommands from recorded shell commands.
	cmds := r.Commands()
	if len(cmds) > 0 {
		p.Spec.Execution.InitCommands = cmds
	}

	return p, nil
}

// GenerateYAML calls Generate and marshals the result to YAML, prepending a
// header comment reminding the operator to review before use.
func (r *Recorder) GenerateYAML(base string) ([]byte, error) {
	p, err := r.Generate(base)
	if err != nil {
		return nil, err
	}

	body, err := goyaml.Marshal(p)
	if err != nil {
		return nil, err
	}

	header := "# Generated by km observe -- review before use\n"
	return append([]byte(header), body...), nil
}

// GenerateAnnotatedYAML is like GenerateYAML but adds comments showing which
// observed domains mapped to each DNS suffix and host, along with hit counts.
// This helps operators quickly understand and tidy the generated profile.
func (r *Recorder) GenerateAnnotatedYAML(base string) ([]byte, error) {
	dns := r.DNSDomains()
	hosts := r.Hosts()
	repos := r.Repos()

	allDomains := unionStrings(dns, hosts)
	suffixes := CollapseToDNSSuffixes(allDomains)
	remainingHosts := deduplicateHosts(hosts, suffixes)

	// Build suffix → observed domains mapping for annotations.
	suffixMap := mapDomainsToSuffixes(allDomains, suffixes)

	p, err := r.Generate(base)
	if err != nil {
		return nil, err
	}

	body, err := goyaml.Marshal(p)
	if err != nil {
		return nil, err
	}

	refs := r.Refs()
	cmds := r.Commands()

	var out strings.Builder
	out.WriteString("# Generated by km observe -- review before use\n")
	fmt.Fprintf(&out, "# Observed: %d DNS domains, %d hosts, %d repos, %d refs, %d commands\n", len(dns), len(hosts), len(repos), len(refs), len(cmds))
	out.WriteString("#\n")

	// Write annotated suffix summary.
	out.WriteString("# DNS suffix summary (--learn-annotate):\n")
	for _, sfx := range suffixes {
		domains := suffixMap[sfx]
		fmt.Fprintf(&out, "#   %s  (%d domains: %s)\n", sfx, len(domains), strings.Join(domains, ", "))
	}
	if len(remainingHosts) > 0 {
		out.WriteString("# Explicit hosts (not covered by suffixes):\n")
		for _, h := range remainingHosts {
			fmt.Fprintf(&out, "#   %s\n", h)
		}
	}
	if len(repos) > 0 {
		out.WriteString("# GitHub repos observed:\n")
		for _, repo := range repos {
			fmt.Fprintf(&out, "#   %s\n", repo)
		}
	}
	if len(refs) > 0 {
		out.WriteString("# Git refs observed:\n")
		for _, ref := range refs {
			fmt.Fprintf(&out, "#   %s\n", ref)
		}
	}
	if len(cmds) > 0 {
		out.WriteString("# Commands observed (suggested initCommands — review before use):\n")
		for _, cmd := range cmds {
			fmt.Fprintf(&out, "#   %s\n", cmd)
		}
	}
	out.WriteString("#\n")

	out.Write(body)
	return []byte(out.String()), nil
}

// mapDomainsToSuffixes returns a map of suffix → list of observed domains that
// collapsed to that suffix. Useful for annotation/debugging.
func mapDomainsToSuffixes(domains []string, suffixes []string) map[string][]string {
	result := make(map[string][]string)
	for _, sfx := range suffixes {
		result[sfx] = nil
	}

	for _, domain := range domains {
		etld1, err := publicsuffix.EffectiveTLDPlusOne(domain)
		if err != nil {
			continue
		}
		key := "." + etld1
		if _, ok := result[key]; ok {
			result[key] = append(result[key], domain)
		}
	}

	// Sort each group for stable output.
	for k := range result {
		sort.Strings(result[k])
	}
	return result
}

// GenerateYAMLFromRecorder is a public convenience wrapper for GenerateYAML.
func GenerateYAMLFromRecorder(r *Recorder, base string) ([]byte, error) {
	return r.GenerateYAML(base)
}

// deduplicateHosts returns the hosts not covered by any of the given DNS suffixes.
// A host is covered if it ends with a suffix (after prepending ".") or is the
// bare eTLD+1 that the suffix represents (suffix == "."+host).
func deduplicateHosts(hosts []string, suffixes []string) []string {
	if len(hosts) == 0 || len(suffixes) == 0 {
		return hosts
	}

	var out []string
	for _, host := range hosts {
		if !isCoveredBySuffix(host, suffixes) {
			out = append(out, host)
		}
	}
	return out
}

// isCoveredBySuffix returns true when host matches one of the DNS suffixes.
// A suffix ".example.com" covers "example.com" (bare domain) and any
// subdomain that ends with ".example.com".
func isCoveredBySuffix(host string, suffixes []string) bool {
	dotHost := "." + host
	for _, sfx := range suffixes {
		// Direct match: suffix is ".host" → host is the eTLD+1 root.
		if sfx == dotHost {
			return true
		}
		// Subdomain match: host ends with ".example.com" → sfx == ".example.com".
		if strings.HasSuffix(dotHost, sfx) {
			return true
		}
	}
	return false
}

// unionStrings merges two string slices, deduplicating entries.
func unionStrings(a, b []string) []string {
	seen := make(map[string]struct{}, len(a)+len(b))
	for _, s := range a {
		seen[s] = struct{}{}
	}
	for _, s := range b {
		seen[s] = struct{}{}
	}
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	return out
}
