locals {
  # Generated by the klanker-maker profile compiler. DO NOT EDIT.
  # Profile: test-ecs-profile

  sandbox_id       = "sb-94-05-km-baseline"
  substrate_module = "ecs"
  region_label     = "use1"
  region_full      = "us-east-1"

  module_inputs = {
    sandbox_id     = "sb-94-05-km-baseline"
    vpc_id         = "vpc-12345"
    public_subnets = ["subnet-a", "subnet-b"]
    use_spot       = false
    task_cpu       = 1024
    task_memory    = 2048

    containers = [
      {
        name               = "main"
        image              = "PLACEHOLDER_ECR/km-sandbox:latest"
        cpu                = 640
        memory             = 1280
        memory_reservation = 640
        essential          = true
        command            = []
        environment = [
          { name = "SANDBOX_ID",    value = "sb-94-05-km-baseline" },
          { name = "KM_LABEL",      value = "km" },
          { name = "HTTP_PROXY",    value = "http://localhost:3128" },
          { name = "HTTPS_PROXY",   value = "http://localhost:3128" },
          { name = "NO_PROXY",      value = "169.254.169.254,169.254.170.2,localhost,127.0.0.1" },
          { name = "KM_EMAIL_ADDRESS", value = "sb-94-05-km-baseline@sandboxes.klankermaker.ai" },
          { name = "KM_SANDBOX_ID",         value = "sb-94-05-km-baseline" },
          { name = "KM_ARTIFACTS_BUCKET",   value = "" },
          # OTEL-07: Claude Code OTLP exports to localhost:4317/4318 bypass the
          # HTTP proxy via NO_PROXY (includes localhost,127.0.0.1).
          { name = "CLAUDE_CODE_ENABLE_TELEMETRY",  value = "1" },
          { name = "OTEL_METRICS_EXPORTER",         value = "otlp" },
          { name = "OTEL_LOGS_EXPORTER",            value = "otlp" },
          { name = "OTEL_EXPORTER_OTLP_PROTOCOL",   value = "grpc" },
          { name = "OTEL_EXPORTER_OTLP_ENDPOINT",   value = "http://localhost:4317" },
          { name = "OTEL_RESOURCE_ATTRIBUTES",      value = "sandbox_id=sb-94-05-km-baseline,profile_name=test-ecs-profile,substrate=ecs" },
        ]
        port_mappings     = []
        log_stream_prefix = "main"
      },
      {
        name               = "km-dns-proxy"
        image              = "PLACEHOLDER_ECR/km-dns-proxy:latest"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",       value = "sb-94-05-km-baseline" },
          { name = "ALLOWED_SUFFIXES", value = "example.com" },
          { name = "UPSTREAM_DNS",     value = "169.254.169.253" },
        ]
        port_mappings     = []
        log_stream_prefix = "dns-proxy"
      },
      {
        name               = "km-http-proxy"
        image              = "PLACEHOLDER_ECR/km-http-proxy:latest"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",               value = "sb-94-05-km-baseline" },
          { name = "ALLOWED_HOSTS",             value = "api.example.com,example.com" },
          { name = "KM_GITHUB_ALLOWED_REPOS",   value = "" },
          { name = "PROXY_PORT",                value = "3128" },
        ]
        port_mappings     = []
        log_stream_prefix = "http-proxy"
      },
      {
        name               = "km-audit-log"
        image              = "PLACEHOLDER_ECR/km-audit-log:latest"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = true
        command            = []
        environment = [
          { name = "SANDBOX_ID",      value = "sb-94-05-km-baseline" },
          { name = "AUDIT_LOG_DEST",  value = "cloudwatch" },
          { name = "CW_LOG_GROUP",    value = "/km/sandboxes/sb-94-05-km-baseline/" },
          { name = "AWS_REGION",      value = "us-east-1" },
        ]
        log_configuration = {
          log_driver = "awslogs"
          options = {
            "awslogs-group"         = "/km/sidecars/sb-94-05-km-baseline"
            "awslogs-region"        = "us-east-1"
            "awslogs-stream-prefix" = "audit-log"
          }
        }
        port_mappings     = []
        log_stream_prefix = "audit-log"
      },
      {
        name               = "km-tracing"
        image              = "PLACEHOLDER_ECR/km-tracing:latest"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",     value = "sb-94-05-km-baseline" },
          { name = "OTEL_S3_BUCKET", value = "" },
          { name = "AWS_REGION",     value = "us-east-1" },
        ]
        port_mappings     = []
        log_stream_prefix = "tracing"
      }
    ]

    sg_egress_rules = [
    ]

    task_role_policy_statements = [
      {
        effect   = "Allow"
        actions  = ["ses:SendEmail", "ses:SendRawEmail"]
        resources = ["*"]
        condition = {
          test     = "StringEquals"
          variable = "ses:FromAddress"
          values   = ["sb-94-05-km-baseline@sandboxes.klankermaker.ai"]
        }
      },
      {
        effect    = "Allow"
        actions   = ["s3:ListObjectsV2", "s3:GetObject"]
        resources = ["arn:aws:s3:::/mail/sb-94-05-km-baseline/*"]
      },
      {
        effect    = "Allow"
        actions   = ["s3:ListBucket"]
        resources = ["arn:aws:s3:::"]
        condition = {
          test     = "StringLike"
          variable = "s3:prefix"
          values   = ["mail/sb-94-05-km-baseline/*"]
        }
      },
    ]
  }
}
