package compiler

import (
	"bytes"
	"fmt"
	"text/template"
)

// budgetEnforcerHCLTemplate produces a per-sandbox budget-enforcer/terragrunt.hcl.
//
// Design: The template is mostly static — it reads dynamic values (sandbox_id,
// substrate, spot_rate, instance_type, etc.) from the sibling service.hcl's
// budget_enforcer_inputs block via read_terragrunt_config. The only Go-templated
// value is the sandbox_id used in the S3 state key, which ensures each sandbox
// has its own isolated Terraform state.
//
// The budget_table_arn is constructed at HCL evaluation time using
// local.site_vars.locals.accounts.application and local.site_vars.locals.region.full
// so the ARN is always correct for the target account without hardcoding account IDs.
//
// instance_id and role_arn are wired from the parent sandbox module's Terraform outputs
// via a dependency block, so the Lambda receives the real EC2 instance ID and IAM role ARN
// at apply time rather than empty or statically-constructed values.
const budgetEnforcerHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Per-sandbox budget enforcer: Lambda + EventBridge 1-minute schedule.

  # Repo root anchored by CLAUDE.md (Terragrunt repo root anchor)
  repo_root  = dirname(find_in_parent_folders("CLAUDE.md"))
  site_vars  = read_terragrunt_config("${local.repo_root}/infra/live/site.hcl")
  svc_config = read_terragrunt_config("${get_terragrunt_dir()}/../service.hcl")

  # Budget enforcer inputs from the sibling service.hcl block.
  # Contains: sandbox_id, substrate, spot_rate, instance_type, created_at, etc.
  be_inputs = local.svc_config.locals.budget_enforcer_inputs

  # Budget table ARN constructed from site variables (avoids hardcoding account IDs).
  budget_table_arn = "arn:aws:dynamodb:${local.site_vars.locals.region.full}:${local.site_vars.locals.accounts.application}:table/${local.site_vars.locals.site.label}-budgets"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "sandbox" {
  config_path = "${get_terragrunt_dir()}/.."

  mock_outputs = {
    ec2spot_instances         = {}
    iam_instance_profile_name = ""
    iam_role_arn              = ""
  }
  mock_outputs_allowed_on_destroy = true
}

# Override remote_state key to isolate this sandbox's budget-enforcer state.
remote_state {
  backend = "s3"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket         = local.site_vars.locals.backend.bucket
    key            = "${local.site_vars.locals.site.tf_state_prefix}/sandboxes/{{ .SandboxID }}/budget-enforcer/terraform.tfstate"
    region         = local.site_vars.locals.backend.region
    encrypt        = local.site_vars.locals.backend.encrypt
    dynamodb_table = local.site_vars.locals.backend.dynamodb_table
  }
}

terraform {
  source = "${local.repo_root}/infra/modules/budget-enforcer/v1.0.0"
}

inputs = merge(
  local.be_inputs,
  {
    # Platform-level inputs resolved from site variables.
    # These are not stored in service.hcl because they are account/region globals.
    lambda_zip_path    = "${local.repo_root}/build/budget-enforcer.zip"
    budget_table_name  = "${local.site_vars.locals.site.label}-budgets"
    budget_table_arn   = local.budget_table_arn
    state_bucket       = get_env("KM_ARTIFACTS_BUCKET", "")
    email_domain       = "sandboxes.${local.site_vars.locals.site.domain}"
    operator_email     = get_env("KM_OPERATOR_EMAIL", "")

    # Wired from ec2spot module outputs via dependency block
    instance_id = try(values(dependency.sandbox.outputs.ec2spot_instances)[0].instance_id, "")
    role_arn    = dependency.sandbox.outputs.iam_role_arn
  }
)
`

// budgetEnforcerHCLData holds the template variables for the budget-enforcer HCL.
// SandboxID is the only dynamic value — everything else is resolved at apply time
// from site.hcl or environment variables.
type budgetEnforcerHCLData struct {
	// SandboxID is used to construct the per-sandbox S3 state key.
	SandboxID string
}

// GenerateBudgetEnforcerHCL produces the content for budget-enforcer/terragrunt.hcl
// for the given sandbox. The caller writes the result to:
//
//	infra/live/{region}/sandboxes/{sandbox-id}/budget-enforcer/terragrunt.hcl
//
// Returns an error only if template parsing or execution fails (programming error,
// not a runtime condition).
func GenerateBudgetEnforcerHCL(sandboxID string) (string, error) {
	tmpl, err := template.New("budget-enforcer-hcl").Parse(budgetEnforcerHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse budget-enforcer HCL template: %w", err)
	}

	data := budgetEnforcerHCLData{
		SandboxID: sandboxID,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute budget-enforcer HCL template: %w", err)
	}
	return buf.String(), nil
}

// generateBudgetEnforcerHCL is the unexported alias used within the compiler package.
// Compile() calls this function when profile.spec.budget is set.
func generateBudgetEnforcerHCL(sandboxID string) (string, error) {
	return GenerateBudgetEnforcerHCL(sandboxID)
}
