package compiler

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// ============================================================
// Docker substrate compiler
// ============================================================

// compileDocker handles the Docker substrate compilation path.
// It produces a docker-compose.yml with 6 services:
//   - main: the sandbox container (user workload)
//   - km-dns-proxy: DNS filtering sidecar with static IP 172.28.0.10
//   - km-http-proxy: HTTP/HTTPS egress proxy with allowlist enforcement
//   - km-audit-log: audit log shipping sidecar
//   - km-tracing: OTEL tracing sidecar
//   - km-cred-refresh: credential rotation loop (only container with operator keys)
//
// Credential isolation: only km-cred-refresh has AWS_ACCESS_KEY_ID/SECRET/SESSION.
// All other containers use AWS_SHARED_CREDENTIALS_FILE pointing to /creds/sandbox or /creds/sidecar.
func compileDocker(p *profile.SandboxProfile, sandboxID string, network *NetworkConfig) (*CompiledArtifacts, error) {
	secretPaths := compileSecrets(p)
	iamPolicy := compileIAMPolicy(p)

	composeYAML, err := generateDockerCompose(p, sandboxID, network, secretPaths)
	if err != nil {
		return nil, fmt.Errorf("generate docker-compose.yml: %w", err)
	}

	return &CompiledArtifacts{
		SandboxID:         sandboxID,
		DockerComposeYAML: composeYAML,
		SecretPaths:       secretPaths,
		IAMPolicy:         iamPolicy,
	}, nil
}

// dockerComposeData is the template data struct for generateDockerCompose.
type dockerComposeData struct {
	SandboxID          string
	MainImage          string
	DNSProxyImage      string
	HTTPProxyImage     string
	AuditLogImage      string
	TracingImage       string
	Region             string
	AllowedDNSSuffixes string // space-separated
	AllowedHosts       string // space-separated
	AllowedRepos       string // space-separated
	AllowedRefs        string // space-separated
	SecretPaths        string // comma-separated
	InitCommands       string // base64-encoded JSON array
	ProfileEnv         string // base64-encoded JSON object
	BudgetEnabled      bool
	BudgetTable        string
	HTTPSOnly          bool
	ArtifactsBucket    string
	StateBucket        string
	EmailDomain        string
	ProxyCACertS3      string
	ProxyCAKeyS3       string
	GitHubTokenSSM     string
	AWSProfile         string // operator's AWS profile name for cred-refresh
	HostAWSDir         string // path to host's ~/.aws directory
}

// dockerComposeTemplate generates a docker-compose.yml for the Docker substrate.
// Services: main, km-dns-proxy, km-http-proxy, km-audit-log, km-tracing, km-cred-refresh.
// Network: km-net (bridge, 172.28.0.0/24). Volumes: km-workspace, cred-vol.
const dockerComposeTemplate = `# Generated by the klankrmkr profile compiler. DO NOT EDIT.
# Sandbox: {{ .SandboxID }}
services:

  main:
    image: {{ .MainImage }}
    container_name: km-{{ .SandboxID }}-main
    depends_on:
      - km-dns-proxy
      - km-http-proxy
      - km-audit-log
    dns:
      - 172.28.0.10
    environment:
      HTTP_PROXY: "http://km-http-proxy:3128"
      HTTPS_PROXY: "http://km-http-proxy:3128"
      NO_PROXY: "localhost,127.0.0.1,172.28.0.0/24"
      AWS_SHARED_CREDENTIALS_FILE: "/creds/sandbox"
      AWS_PROFILE: "sandbox"
      KM_SANDBOX_ID: "{{ .SandboxID }}"
      KM_REGION: "{{ .Region }}"
      KM_ARTIFACTS_BUCKET: "{{ .ArtifactsBucket }}"
      KM_STATE_BUCKET: "{{ .StateBucket }}"
      KM_EMAIL_DOMAIN: "{{ .EmailDomain }}"
      KM_SECRET_PATHS: "{{ .SecretPaths }}"
      KM_INIT_COMMANDS: "{{ .InitCommands }}"
      KM_PROFILE_ENV: "{{ .ProfileEnv }}"
      KM_GITHUB_TOKEN_SSM: "{{ .GitHubTokenSSM }}"
      KM_PROXY_CA_CERT_S3: "{{ .ProxyCACertS3 }}"
    volumes:
      - km-workspace:/workspace
      - cred-vol:/creds:ro
      - audit-vol:/run/km
      - ./km-proxy-ca.crt:/etc/km/proxy-ca.crt:ro
      - ./km-audit-init.sh:/opt/km/km-audit-init.sh:ro
    networks:
      - km-net
    restart: unless-stopped

  km-dns-proxy:
    image: {{ .DNSProxyImage }}
    container_name: km-{{ .SandboxID }}-dns-proxy
    environment:
      ALLOWED_SUFFIXES: "{{ .AllowedDNSSuffixes }}"
      UPSTREAM_DNS: "8.8.8.8"
      SANDBOX_ID: "{{ .SandboxID }}"
      KM_SANDBOX_ID: "{{ .SandboxID }}"
    networks:
      km-net:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

  km-http-proxy:
    image: {{ .HTTPProxyImage }}
    container_name: km-{{ .SandboxID }}-http-proxy
    environment:
      ALLOWED_HOSTS: "{{ .AllowedHosts }}"
      AWS_SHARED_CREDENTIALS_FILE: "/creds/sidecar"
      AWS_PROFILE: "sidecar"
      SANDBOX_ID: "{{ .SandboxID }}"
      KM_SANDBOX_ID: "{{ .SandboxID }}"
      KM_REGION: "{{ .Region }}"
      KM_PROXY_CA_CERT_S3: "{{ .ProxyCACertS3 }}"
      KM_PROXY_CA_KEY_S3: "{{ .ProxyCAKeyS3 }}"
      KM_PROXY_CA_CERT: "PLACEHOLDER_PROXY_CA_B64"
{{- if .BudgetEnabled }}
      KM_BUDGET_ENABLED: "true"
      KM_BUDGET_TABLE: "{{ .BudgetTable }}"
{{- end }}
{{- if .HTTPSOnly }}
      KM_HTTPS_ONLY: "true"
{{- end }}
    volumes:
      - cred-vol:/creds:ro
    networks:
      - km-net
    restart: unless-stopped

  km-audit-log:
    image: {{ .AuditLogImage }}
    container_name: km-{{ .SandboxID }}-audit-log
    environment:
      AUDIT_LOG_DEST: "s3"
      SANDBOX_ID: "{{ .SandboxID }}"
      KM_SANDBOX_ID: "{{ .SandboxID }}"
      KM_ARTIFACTS_BUCKET: "{{ .ArtifactsBucket }}"
      KM_AUDIT_PIPE: "/run/km/audit-pipe"
      AWS_SHARED_CREDENTIALS_FILE: "/creds/sidecar"
      AWS_PROFILE: "sidecar"
    volumes:
      - cred-vol:/creds:ro
      - audit-vol:/run/km
    networks:
      - km-net
    restart: unless-stopped

  km-tracing:
    image: {{ .TracingImage }}
    container_name: km-{{ .SandboxID }}-tracing
    environment:
      SANDBOX_ID: "{{ .SandboxID }}"
      KM_SANDBOX_ID: "{{ .SandboxID }}"
      KM_REGION: "{{ .Region }}"
      AWS_REGION: "{{ .Region }}"
      OTEL_S3_BUCKET: "{{ .ArtifactsBucket }}"
      AWS_SHARED_CREDENTIALS_FILE: "/creds/sidecar"
      AWS_PROFILE: "sidecar"
    volumes:
      - cred-vol:/creds:ro
    networks:
      - km-net
    restart: unless-stopped

  km-cred-refresh:
    image: {{ .MainImage }}
    container_name: km-{{ .SandboxID }}-cred-refresh
    entrypoint: ["/opt/km/cred-refresh.sh"]
    command: []
    environment:
      KM_SANDBOX_ID: "{{ .SandboxID }}"
      KM_SANDBOX_ROLE_ARN: "PLACEHOLDER_SANDBOX_ROLE_ARN"
      KM_SIDECAR_ROLE_ARN: "PLACEHOLDER_SIDECAR_ROLE_ARN"
      AWS_DEFAULT_REGION: "{{ .Region }}"
      AWS_PROFILE: "{{ .AWSProfile }}"
    volumes:
      - cred-vol:/creds
      - {{ .HostAWSDir }}:/root/.aws:ro
    networks:
      - km-net
    restart: unless-stopped

networks:
  km-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  km-workspace:
  cred-vol:
  audit-vol:
`

// generateDockerCompose renders the docker-compose.yml template with profile data.
func generateDockerCompose(p *profile.SandboxProfile, sandboxID string, network *NetworkConfig, secretPaths []string) (string, error) {
	// Encode initCommands as base64 JSON array
	initCmdsJSON, err := json.Marshal(p.Spec.Execution.InitCommands)
	if err != nil {
		return "", fmt.Errorf("marshal initCommands: %w", err)
	}
	initCmdsB64 := base64.StdEncoding.EncodeToString(initCmdsJSON)

	// Inject Bedrock env vars if useBedrock is set.
	profileEnv := mergeBedrockEnv(p)

	// Encode profile env as base64 JSON object
	profileEnvJSON, err := json.Marshal(profileEnv)
	if err != nil {
		return "", fmt.Errorf("marshal profile env: %w", err)
	}
	profileEnvB64 := base64.StdEncoding.EncodeToString(profileEnvJSON)

	// Budget fields
	budgetEnabled := p.Spec.Budget != nil
	budgetTable := ""
	if budgetEnabled {
		budgetTable = fmt.Sprintf("km-budget-%s", sandboxID)
	}

	// Network fields from NetworkConfig (fall back to empty strings)
	artifactsBucket := ""
	stateBucket := ""
	emailDomain := ""
	if network != nil {
		artifactsBucket = network.ArtifactsBucket
		emailDomain = network.EmailDomain
	}

	// CA cert and key S3 paths (constructed when artifactsBucket is known)
	proxyCACertS3 := ""
	proxyCAKeyS3 := ""
	if artifactsBucket != "" {
		proxyCACertS3 = fmt.Sprintf("s3://%s/sidecars/km-proxy-ca.crt", artifactsBucket)
		proxyCAKeyS3 = fmt.Sprintf("s3://%s/sidecars/km-proxy-ca.key", artifactsBucket)
	}

	// GitHub token SSM path
	gitHubTokenSSM := ""
	if p.Spec.SourceAccess.GitHub != nil && len(p.Spec.SourceAccess.GitHub.AllowedRepos) > 0 {
		gitHubTokenSSM = fmt.Sprintf("/sandbox/%s/github-token", sandboxID)
	}

	// Allowed repos/refs
	allowedRepos := ""
	allowedRefs := ""
	if p.Spec.SourceAccess.GitHub != nil {
		allowedRepos = strings.Join(p.Spec.SourceAccess.GitHub.AllowedRepos, " ")
		allowedRefs = strings.Join(p.Spec.SourceAccess.GitHub.AllowedRefs, " ")
	}

	// Build image names — use ECR URIs if KM_ACCOUNTS_APPLICATION is set, otherwise local names.
	accountID := os.Getenv("KM_ACCOUNTS_APPLICATION")
	sidecarImg := func(name string) string {
		if accountID != "" {
			return fmt.Sprintf("%s.dkr.ecr.%s.amazonaws.com/km-%s:latest", accountID, p.Spec.Runtime.Region, name)
		}
		return "km-" + name + ":latest"
	}

	data := dockerComposeData{
		SandboxID:          sandboxID,
		MainImage:          sidecarImg("sandbox"),
		DNSProxyImage:      sidecarImg("dns-proxy"),
		HTTPProxyImage:     sidecarImg("http-proxy"),
		AuditLogImage:      sidecarImg("audit-log"),
		TracingImage:        sidecarImg("tracing"),
		Region:             p.Spec.Runtime.Region,
		AllowedDNSSuffixes: strings.Join(p.Spec.Network.Egress.AllowedDNSSuffixes, ","),
		AllowedHosts:       strings.Join(p.Spec.Network.Egress.AllowedHosts, ","),
		AllowedRepos:       allowedRepos,
		AllowedRefs:        allowedRefs,
		SecretPaths:        strings.Join(secretPaths, ","),
		InitCommands:       initCmdsB64,
		ProfileEnv:         profileEnvB64,
		BudgetEnabled:      budgetEnabled,
		BudgetTable:        budgetTable,
		HTTPSOnly:          p.Spec.Network.HTTPSOnly,
		ArtifactsBucket:    artifactsBucket,
		StateBucket:        stateBucket,
		EmailDomain:        emailDomain,
		ProxyCACertS3:      proxyCACertS3,
		ProxyCAKeyS3:       proxyCAKeyS3,
		GitHubTokenSSM:     gitHubTokenSSM,
		AWSProfile:         os.Getenv("KM_AWS_PROFILE"),
		HostAWSDir:         filepath.Join(os.Getenv("HOME"), ".aws"),
	}

	tmpl, err := template.New("docker-compose").Parse(dockerComposeTemplate)
	if err != nil {
		return "", fmt.Errorf("parse docker-compose template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute docker-compose template: %w", err)
	}

	return buf.String(), nil
}

// GenerateAuditInitScript returns a shell script that creates the named pipe
// and installs the shell audit hook + heartbeat. This script should be mounted
// into the main container and sourced from /etc/profile.d/ or the entrypoint.
//
// On Docker, the named pipe lives on a shared volume (audit-vol) mounted at
// /run/km/ in both the main container and km-audit-log container — mirroring
// the EC2 architecture where both processes share the host filesystem.
func GenerateAuditInitScript(sandboxID string) string {
	return fmt.Sprintf(`#!/bin/bash
# km-audit-init.sh — creates audit named pipe and installs shell hook.
# Generated by the klankrmkr profile compiler. DO NOT EDIT.
# Mount this into the main container and source from entrypoint or profile.d.

# Create named pipe if it doesn't already exist (audit-log sidecar reads from it).
if [ ! -p /run/km/audit-pipe ]; then
  mkdir -p /run/km
  mkfifo /run/km/audit-pipe
  chmod 666 /run/km/audit-pipe
fi

# Install shell audit hook into profile.d so every login shell captures commands.
cat > /etc/profile.d/km-audit.sh << 'HOOK'
# Guard: only install once per shell (profile.d can be sourced multiple times)
[ -n "$_KM_AUDIT_INSTALLED" ] && return 0
_KM_AUDIT_INSTALLED=1

_km_audit() {
  local cmd
  cmd=$(HISTTIMEFORMAT= history 1 | sed 's/^ *[0-9]* *//')
  [ -z "$cmd" ] && return 0
  cmd=$(printf '%%s' "$cmd" | sed 's/\\/\\\\/g; s/"/\\"/g; s/	/ /g' | head -c 500)
  printf '{"timestamp":"%%s","sandbox_id":"%%s","event_type":"command","source":"shell","detail":{"command":"%%s","user":"%%s"}}\n' \
    "$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)" "%s" "$cmd" "$(whoami)" \
    > /run/km/audit-pipe 2>/dev/null
}
PROMPT_COMMAND="_km_audit;${PROMPT_COMMAND}"

_km_heartbeat() {
  while true; do
    sleep 60
    printf '{"timestamp":"%%s","sandbox_id":"%%s","event_type":"heartbeat","source":"shell","detail":{}}\n' \
      "$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)" "%s" > /run/km/audit-pipe 2>/dev/null
  done
}
_km_heartbeat &
_KM_HEARTBEAT_PID=$!
trap 'kill $_KM_HEARTBEAT_PID 2>/dev/null' EXIT
HOOK
chmod 644 /etc/profile.d/km-audit.sh
`, sandboxID, sandboxID)
}
