package compiler

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// githubTokenHCLTemplate produces a per-sandbox github-token/terragrunt.hcl.
//
// Design: Mirrors the budget-enforcer HCL pattern. The template reads dynamic
// inputs from the sibling service.hcl's github_token_inputs block at apply time.
// The only Go-templated value is sandbox_id for the S3 state key isolation.
//
// The Lambda refreshes the token every 45 minutes by writing to the per-sandbox
// SSM path /sandbox/{sandbox-id}/github-token. The GIT_ASKPASS helper reads from
// this path at git-operation time (never exported as an environment variable).
const githubTokenHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Per-sandbox GitHub token refresher: Lambda + EventBridge 45-minute schedule.

  # Repo root anchored by CLAUDE.md (Terragrunt repo root anchor)
  repo_root  = dirname(find_in_parent_folders("CLAUDE.md"))
  site_vars  = read_terragrunt_config("${local.repo_root}/infra/live/site.hcl")
  svc_config = read_terragrunt_config("${get_terragrunt_dir()}/../service.hcl")

  # GitHub token inputs from the sibling service.hcl block.
  # Contains: sandbox_id, ssm_parameter_name, allowed_repos, permissions.
  gh_inputs = local.svc_config.locals.github_token_inputs
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

# Override remote_state key to isolate this sandbox's github-token state.
remote_state {
  backend = "s3"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket         = local.site_vars.locals.backend.bucket
    key            = "${local.site_vars.locals.site.tf_state_prefix}/sandboxes/{{ .SandboxID }}/github-token/terraform.tfstate"
    region         = local.site_vars.locals.backend.region
    encrypt        = local.site_vars.locals.backend.encrypt
    dynamodb_table = local.site_vars.locals.backend.dynamodb_table
  }
}

terraform {
  source = "${local.repo_root}/infra/modules/github-token/v1.0.0"
}

inputs = merge(
  local.gh_inputs,
  {
    # Platform-level inputs resolved at apply time.
    lambda_zip_path      = "${local.repo_root}/build/github-token-refresher.zip"
    installation_id      = "" # populated at apply time from SSM or operator config
    sandbox_iam_role_arn = "arn:aws:iam::${local.site_vars.locals.accounts.application}:role/km-ec2spot-ssm-${local.gh_inputs.sandbox_id}-${local.site_vars.locals.region.label}"
  }
)
`

// githubTokenHCLData holds template variables for the github-token HCL.
// SandboxID is the only dynamic value — everything else is resolved from
// site.hcl or the sibling service.hcl at apply time.
type githubTokenHCLData struct {
	// SandboxID is used to construct the per-sandbox S3 state key.
	SandboxID string
}

// generateGitHubTokenHCL produces the content for github-token/terragrunt.hcl.
// Called from compileEC2 and compileECS when p.Spec.SourceAccess.GitHub != nil.
//
// The caller writes the result to:
//
//	infra/live/{region}/sandboxes/{sandbox-id}/github-token/terragrunt.hcl
func generateGitHubTokenHCL(sandboxID string, p *profile.SandboxProfile) (string, error) {
	tmpl, err := template.New("github-token-hcl").Parse(githubTokenHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse github-token HCL template: %w", err)
	}

	data := githubTokenHCLData{
		SandboxID: sandboxID,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute github-token HCL template: %w", err)
	}
	return buf.String(), nil
}

