package compiler

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// ============================================================
// EC2 service.hcl template
// ============================================================

// ec2ServiceHCLTemplate generates a service.hcl locals block for EC2/ec2spot substrate.
// It includes sg_egress_rules and iam_session_policy in module_inputs so that the
// compiled security configuration actually reaches Terraform (NETW-01, NETW-04).
const ec2ServiceHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Profile: {{ .ProfileName }}

  sandbox_id       = "{{ .SandboxID }}"
  substrate_module = "ec2spot"

  module_inputs = {
    sandbox_id         = "{{ .SandboxID }}"
    vpc_id             = "{{ .VPCID }}"
    public_subnets     = [{{ joinStrings .PublicSubnets }}]
    availability_zones = [{{ joinStrings .AvailabilityZones }}]

    ec2spots = [
      {
        count         = 1
        region        = "{{ .Region }}"
        sandbox_id    = "{{ .SandboxID }}"
        instance_type = "{{ .InstanceType }}"
        use_spot      = {{ .UseSpot }}
{{- if .UseSpot }}
        spot_price_multiplier  = 1.05
        spot_price_offset      = 0.0005
        block_duration_minutes = 0
{{- end }}
        user_data_base64 = "{{ .UserDataBase64 }}"
      }
    ]

    sg_egress_rules = [
{{- range .SGEgressRules }}
      {{ sgRuleHCL . }},
{{- end }}
    ]

    iam_session_policy = {
      max_session_duration = {{ .IAMPolicy.MaxSessionDuration }}
      allowed_regions      = [{{ joinStrings .IAMPolicy.AllowedRegions }}]
    }
  }
}
`

// ============================================================
// ECS service.hcl template
// ============================================================

// ecsServiceHCLTemplate generates a service.hcl locals block for ECS substrate.
// Uses the combined ecs module (cluster + task + service in one).
const ecsServiceHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Profile: {{ .ProfileName }}

  sandbox_id       = "{{ .SandboxID }}"
  substrate_module = "ecs"

  module_inputs = {
    sandbox_id     = "{{ .SandboxID }}"
    vpc_id         = "{{ .VPCID }}"
    public_subnets = [{{ joinStrings .PublicSubnets }}]
    use_spot       = {{ .UseSpot }}
    task_cpu       = {{ .TaskCPU }}
    task_memory    = {{ .TaskMemory }}

    containers = [
      {
        name               = "main"
        image              = "{{ .MainImage }}"
        cpu                = {{ .MainCPU }}
        memory             = {{ .MainMemory }}
        memory_reservation = {{ .MainMemoryReservation }}
        essential          = true
        command            = []
        environment = [
          { name = "SANDBOX_ID", value = "{{ .SandboxID }}" },
          { name = "KM_LABEL", value = "km" }
        ]
        port_mappings     = []
        log_stream_prefix = "main"
      },
      {
        name               = "dns-proxy"
        image              = "DNS_PROXY_IMAGE_PLACEHOLDER"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = true
        command            = []
        environment        = [{ name = "SANDBOX_ID", value = "{{ .SandboxID }}" }]
        port_mappings      = []
        log_stream_prefix  = "dns-proxy"
      },
      {
        name               = "http-proxy"
        image              = "HTTP_PROXY_IMAGE_PLACEHOLDER"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = true
        command            = []
        environment        = [{ name = "SANDBOX_ID", value = "{{ .SandboxID }}" }]
        port_mappings      = []
        log_stream_prefix  = "http-proxy"
      },
      {
        name               = "audit-log"
        image              = "AUDIT_LOG_IMAGE_PLACEHOLDER"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = false
        command            = []
        environment        = [{ name = "SANDBOX_ID", value = "{{ .SandboxID }}" }]
        port_mappings      = []
        log_stream_prefix  = "audit-log"
      },
      {
        name               = "tracing"
        image              = "TRACING_IMAGE_PLACEHOLDER"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = false
        command            = []
        environment        = [{ name = "SANDBOX_ID", value = "{{ .SandboxID }}" }]
        port_mappings      = []
        log_stream_prefix  = "tracing"
      }
    ]

    sg_egress_rules = [
{{- range .SGEgressRules }}
      {{ sgRuleHCL . }},
{{- end }}
    ]
  }
}
`

// ============================================================
// EC2 template parameters
// ============================================================

// ec2HCLParams holds the data for the EC2 service.hcl template.
type ec2HCLParams struct {
	ProfileName       string
	SandboxID         string
	Region            string
	InstanceType      string
	UseSpot           bool
	UserDataBase64    string
	VPCID             string
	PublicSubnets     []string
	AvailabilityZones []string
	SGEgressRules     []SGRule
	IAMPolicy         *IAMSessionPolicy
}

// ============================================================
// ECS template parameters
// ============================================================

// ecsHCLParams holds the data for the ECS service.hcl template.
type ecsHCLParams struct {
	ProfileName           string
	SandboxID             string
	Region                string
	TaskCPU               int
	TaskMemory            int
	MainImage             string
	MainCPU               int
	MainMemory            int
	MainMemoryReservation int
	UseSpot               bool
	VPCID                 string
	PublicSubnets         []string
	SGEgressRules         []SGRule
}

// ============================================================
// Template functions
// ============================================================

// templateFuncs provides helper functions used in service.hcl templates.
var templateFuncs = template.FuncMap{
	// sgRuleHCL serializes a SGRule into an HCL object literal.
	"sgRuleHCL": func(r SGRule) string {
		cidrs := ""
		for i, c := range r.CIDRBlocks {
			if i > 0 {
				cidrs += ", "
			}
			cidrs += fmt.Sprintf("%q", c)
		}
		return fmt.Sprintf(
			"{ from_port = %d, to_port = %d, protocol = %q, cidr_blocks = [%s], description = %q }",
			r.FromPort, r.ToPort, r.Protocol, cidrs, r.Description,
		)
	},
	// joinStrings produces a comma-separated HCL list of quoted strings.
	"joinStrings": func(ss []string) string {
		quoted := make([]string, len(ss))
		for i, s := range ss {
			quoted[i] = fmt.Sprintf("%q", s)
		}
		return strings.Join(quoted, ", ")
	},
}

// ============================================================
// EC2 service.hcl generation
// ============================================================

// generateEC2ServiceHCL produces the service.hcl content for an EC2/ec2spot sandbox.
// NetworkConfig holds shared VPC/subnet info from km init.
type NetworkConfig struct {
	VPCID             string
	PublicSubnets     []string
	AvailabilityZones []string
}

func generateEC2ServiceHCL(p *profile.SandboxProfile, sandboxID string, useSpot bool, sgRules []SGRule, iamPolicy *IAMSessionPolicy, userData string, network *NetworkConfig) (string, error) {
	tmpl, err := template.New("ec2-service-hcl").Funcs(templateFuncs).Parse(ec2ServiceHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse ec2 service.hcl template: %w", err)
	}

	params := ec2HCLParams{
		ProfileName:       p.Metadata.Name,
		SandboxID:         sandboxID,
		Region:            p.Spec.Runtime.Region,
		InstanceType:      p.Spec.Runtime.InstanceType,
		UseSpot:           useSpot,
		UserDataBase64:    userData,
		VPCID:             network.VPCID,
		PublicSubnets:     network.PublicSubnets,
		AvailabilityZones: network.AvailabilityZones,
		SGEgressRules:     sgRules,
		IAMPolicy:         iamPolicy,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("execute ec2 service.hcl template: %w", err)
	}
	return buf.String(), nil
}

// ============================================================
// ECS service.hcl generation
// ============================================================

// ecsDefaultCPU and ecsDefaultMemory are the total Fargate task allocations
// when no override is provided in the profile.
const ecsDefaultCPU = 1024
const ecsDefaultMemory = 2048

// generateECSServiceHCL produces the service.hcl content for an ECS/ecs-cluster sandbox.
func generateECSServiceHCL(p *profile.SandboxProfile, sandboxID string, useSpot bool, sgRules []SGRule, network *NetworkConfig) (string, error) {
	tmpl, err := template.New("ecs-service-hcl").Funcs(templateFuncs).Parse(ecsServiceHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse ecs service.hcl template: %w", err)
	}

	// Main container gets the majority of CPU/memory; sidecars share the rest.
	// Total: 1024 CPU, 2048 MiB memory
	// Sidecars: 2x128 CPU + 2x64 CPU = 384 CPU, 2x256 + 2x128 = 768 MiB
	// Main gets the remainder: 640 CPU, 1280 MiB
	mainCPU := ecsDefaultCPU - (128 + 128 + 64 + 64)
	mainMemory := ecsDefaultMemory - (256 + 256 + 128 + 128)
	mainMemoryReservation := mainMemory / 2

	// Use profile image if set, otherwise placeholder
	mainImage := "MAIN_IMAGE_PLACEHOLDER"
	if p.Spec.Runtime.InstanceType != "" {
		// For ECS, instanceType holds the Fargate task size (e.g. "512/1024")
		// We keep the placeholder here; real image set at provision time.
	}

	params := ecsHCLParams{
		ProfileName:           p.Metadata.Name,
		SandboxID:             sandboxID,
		Region:                p.Spec.Runtime.Region,
		TaskCPU:               ecsDefaultCPU,
		TaskMemory:            ecsDefaultMemory,
		MainImage:             mainImage,
		MainCPU:               mainCPU,
		MainMemory:            mainMemory,
		MainMemoryReservation: mainMemoryReservation,
		UseSpot:               useSpot,
		VPCID:                 network.VPCID,
		PublicSubnets:         network.PublicSubnets,
		SGEgressRules:         sgRules,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("execute ecs service.hcl template: %w", err)
	}
	return buf.String(), nil
}
