package compiler

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/template"
	"time"

	pkggithub "github.com/whereiskurt/klankrmkr/pkg/github"
	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// ============================================================
// EC2 service.hcl template
// ============================================================

// ec2ServiceHCLTemplate generates a service.hcl locals block for EC2/ec2spot substrate.
// It includes sg_egress_rules and iam_session_policy in module_inputs so that the
// compiled security configuration actually reaches Terraform (NETW-01, NETW-04).
// When a budget is defined in the profile, a budget_enforcer module block is included.
const ec2ServiceHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Profile: {{ .ProfileName }}

  sandbox_id       = "{{ .SandboxID }}"
  substrate_module = "ec2spot"
  region_label     = "{{ .RegionLabel }}"
  region_full      = "{{ .Region }}"

  module_inputs = {
    sandbox_id         = "{{ .SandboxID }}"
    vpc_id             = "{{ .VPCID }}"
    public_subnets     = [{{ joinStrings .PublicSubnets }}]
    availability_zones = [{{ joinStrings .AvailabilityZones }}]

    ec2spots = [
      {
        count         = 1
        region        = "{{ .Region }}"
        sandbox_id    = "{{ .SandboxID }}"
        instance_type = "{{ .InstanceType }}"
        use_spot      = {{ .UseSpot }}
{{- if .UseSpot }}
        spot_price_multiplier  = 1.05
        spot_price_offset      = 0.0005
        block_duration_minutes = 0
{{- end }}
        user_data_base64 = "{{ .UserDataBase64 }}"
      }
    ]

    sg_egress_rules = [
{{- range .SGEgressRules }}
      {{ sgRuleHCL . }},
{{- end }}
    ]

    iam_session_policy = {
      max_session_duration = {{ .IAMPolicy.MaxSessionDuration }}
      allowed_regions      = [{{ joinStrings .IAMPolicy.AllowedRegions }}]
    }

    enable_bedrock = {{ .EnableBedrock }}
  }
{{- if .HasBudget }}

  # Budget enforcer: EventBridge 1-minute schedule + Lambda for compute/AI enforcement.
  # Requires profile.spec.budget to be set (compute and/or AI limits).
  budget_enforcer_inputs = {
    sandbox_id     = "{{ .SandboxID }}"
    substrate      = "ec2"
    spot_rate      = {{ .SpotRateUSD }}
    instance_type  = "{{ .InstanceType }}"
    created_at     = "{{ .CreatedAt }}"
{{- if .ComputeLimit }}
    compute_limit_usd = {{ .ComputeLimit }}
{{- end }}
{{- if .AILimit }}
    ai_limit_usd      = {{ .AILimit }}
{{- end }}
    warning_threshold = {{ .WarningThreshold }}
  }
{{- end }}
{{- if .HasGitHub }}

  # GitHub token inputs: EventBridge 45-minute schedule + Lambda for token refresh.
  # Consumed by github-token/terragrunt.hcl via read_terragrunt_config.
  github_token_inputs = {
    sandbox_id         = "{{ .SandboxID }}"
    ssm_parameter_name = "{{ .GitHubSSMPath }}"
    allowed_repos      = [{{ joinStrings .GitHubAllowedRepos }}]
    permissions        = {{ .GitHubPermissions }}
  }
{{- end }}
}
`

// ============================================================
// ECS service.hcl template
// ============================================================

// ecsServiceHCLTemplate generates a service.hcl locals block for ECS substrate.
// Uses the combined ecs module (cluster + task + service in one).
// When a budget is defined, a budget_enforcer_inputs block is appended.
const ecsServiceHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Profile: {{ .ProfileName }}

  sandbox_id       = "{{ .SandboxID }}"
  substrate_module = "ecs"
  region_label     = "{{ .RegionLabel }}"
  region_full      = "{{ .Region }}"

  module_inputs = {
    sandbox_id     = "{{ .SandboxID }}"
    vpc_id         = "{{ .VPCID }}"
    public_subnets = [{{ joinStrings .PublicSubnets }}]
    use_spot       = {{ .UseSpot }}
    task_cpu       = {{ .TaskCPU }}
    task_memory    = {{ .TaskMemory }}
{{- if .EffectiveWritablePaths }}

    volumes = [
{{- range .EffectiveWritablePaths }}
      { name = "{{ volumeName . }}", scope = "task" },
{{- end }}
    ]
{{- end }}

    containers = [
      {
        name               = "main"
        image              = "{{ .MainImage }}"
        cpu                = {{ .MainCPU }}
        memory             = {{ .MainMemory }}
        memory_reservation = {{ .MainMemoryReservation }}
        essential          = true
        command            = []
{{- if .HasFilesystemPolicy }}
        readonlyRootFilesystem = true
{{- end }}
        environment = [
          { name = "SANDBOX_ID",    value = "{{ .SandboxID }}" },
          { name = "KM_LABEL",      value = "km" },
          { name = "HTTP_PROXY",    value = "http://localhost:3128" },
          { name = "HTTPS_PROXY",   value = "http://localhost:3128" },
          { name = "NO_PROXY",      value = "169.254.169.254,169.254.170.2,localhost,127.0.0.1" },
{{- if .HasEmail }}
          { name = "KM_EMAIL_ADDRESS", value = "{{ .SandboxEmail }}" },
{{- end }}
          { name = "KM_SANDBOX_ID",         value = "{{ .KMSandboxID }}" },
          { name = "KM_ARTIFACTS_BUCKET",   value = "{{ .KMArtifactsBucket }}" },
{{- if .KMProxyCACertS3 }}
          { name = "KM_PROXY_CA_CERT_S3",   value = "{{ .KMProxyCACertS3 }}" },
{{- end }}
{{- if .KMSecretPaths }}
          { name = "KM_SECRET_PATHS",       value = "{{ .KMSecretPaths }}" },
{{- end }}
{{- if .KMOTPPaths }}
          { name = "KM_OTP_PATHS",          value = "{{ .KMOTPPaths }}" },
{{- end }}
{{- if .KMInitCommands }}
          { name = "KM_INIT_COMMANDS",      value = "{{ .KMInitCommands }}" },
{{- end }}
{{- if .KMRsyncSnapshot }}
          { name = "KM_RSYNC_SNAPSHOT",     value = "{{ .KMRsyncSnapshot }}" },
{{- end }}
{{- if .KMGitHubTokenSSM }}
          { name = "KM_GITHUB_TOKEN_SSM",   value = "{{ .KMGitHubTokenSSM }}" },
{{- end }}
{{- if .KMGitHubAllowedRefs }}
          { name = "KM_GITHUB_ALLOWED_REFS", value = "{{ .KMGitHubAllowedRefs }}" },
{{- end }}
{{- if .KMProfileEnv }}
          { name = "KM_PROFILE_ENV",        value = "{{ .KMProfileEnv }}" },
{{- end }}
{{- if .KMOperatorEmail }}
          { name = "KM_OPERATOR_EMAIL",     value = "{{ .KMOperatorEmail }}" },
{{- end }}
{{- if .ClaudeTelemetryEnabled }}
          # OTEL-07: Claude Code OTLP exports to localhost:4317/4318 bypass the
          # HTTP proxy via NO_PROXY (includes localhost,127.0.0.1).
          { name = "CLAUDE_CODE_ENABLE_TELEMETRY",  value = "1" },
          { name = "OTEL_METRICS_EXPORTER",         value = "otlp" },
          { name = "OTEL_LOGS_EXPORTER",            value = "otlp" },
          { name = "OTEL_EXPORTER_OTLP_PROTOCOL",   value = "grpc" },
          { name = "OTEL_EXPORTER_OTLP_ENDPOINT",   value = "http://localhost:4317" },
{{- if .ClaudeTelemetryLogPrompts }}
          { name = "OTEL_LOG_USER_PROMPTS",         value = "1" },
{{- end }}
{{- if .ClaudeTelemetryLogToolDetails }}
          { name = "OTEL_LOG_TOOL_DETAILS",         value = "1" },
{{- end }}
          { name = "OTEL_RESOURCE_ATTRIBUTES",      value = "{{ .OTELResourceAttributes }}" },
{{- end }}
        ]
{{- if .EffectiveWritablePaths }}
        mountPoints = [
{{- range .EffectiveWritablePaths }}
          { sourceVolume = "{{ volumeName . }}", containerPath = "{{ . }}", readOnly = false },
{{- end }}
        ]
{{- end }}
        port_mappings     = []
        log_stream_prefix = "main"
      },
      {
        name               = "km-dns-proxy"
        image              = "{{ .DNSProxyImage }}"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",       value = "{{ .SandboxID }}" },
          { name = "ALLOWED_SUFFIXES", value = "{{ .AllowedDNSSuffixes }}" },
          { name = "UPSTREAM_DNS",     value = "169.254.169.253" },
        ]
        port_mappings     = []
        log_stream_prefix = "dns-proxy"
      },
      {
        name               = "km-http-proxy"
        image              = "{{ .HTTPProxyImage }}"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",               value = "{{ .SandboxID }}" },
          { name = "ALLOWED_HOSTS",             value = "{{ .AllowedHTTPHosts }}" },
          { name = "KM_GITHUB_ALLOWED_REPOS",   value = "{{ .GitHubAllowedReposCSV }}" },
          { name = "PROXY_PORT",                value = "3128" },
        ]
        port_mappings     = []
        log_stream_prefix = "http-proxy"
      },
      {
        name               = "km-audit-log"
        image              = "{{ .AuditLogImage }}"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = true
        command            = []
        environment = [
          { name = "SANDBOX_ID",      value = "{{ .SandboxID }}" },
          { name = "AUDIT_LOG_DEST",  value = "cloudwatch" },
          { name = "CW_LOG_GROUP",    value = "/km/sandboxes/{{ .SandboxID }}/" },
          { name = "AWS_REGION",      value = "{{ .Region }}" },
        ]
        log_configuration = {
          log_driver = "awslogs"
          options = {
            "awslogs-group"         = "/km/sidecars/{{ .SandboxID }}"
            "awslogs-region"        = "{{ .Region }}"
            "awslogs-stream-prefix" = "audit-log"
          }
        }
        port_mappings     = []
        log_stream_prefix = "audit-log"
      },
      {
        name               = "km-tracing"
        image              = "{{ .TracingImage }}"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",     value = "{{ .SandboxID }}" },
          { name = "OTEL_S3_BUCKET", value = "{{ .ArtifactsBucket }}" },
          { name = "AWS_REGION",     value = "{{ .Region }}" },
        ]
        port_mappings     = []
        log_stream_prefix = "tracing"
      }
    ]

    sg_egress_rules = [
{{- range .SGEgressRules }}
      {{ sgRuleHCL . }},
{{- end }}
    ]
{{- if .HasEmail }}

    task_role_policy_statements = [
      {
        effect   = "Allow"
        actions  = ["ses:SendEmail", "ses:SendRawEmail"]
        resources = ["*"]
        condition = {
          test     = "StringEquals"
          variable = "ses:FromAddress"
          values   = ["{{ .SandboxEmail }}"]
        }
      },
      {
        effect    = "Allow"
        actions   = ["s3:ListObjectsV2", "s3:GetObject"]
        resources = ["arn:aws:s3:::{{ .ArtifactBucket }}/mail/{{ .SandboxID }}/*"]
      },
      {
        effect    = "Allow"
        actions   = ["s3:ListBucket"]
        resources = ["arn:aws:s3:::{{ .ArtifactBucket }}"]
        condition = {
          test     = "StringLike"
          variable = "s3:prefix"
          values   = ["mail/{{ .SandboxID }}/*"]
        }
      },
    ]
{{- end }}
  }
{{- if .HasBudget }}

  # Budget enforcer: EventBridge 1-minute schedule + Lambda for compute/AI enforcement.
  # Requires profile.spec.budget to be set (compute and/or AI limits).
  budget_enforcer_inputs = {
    sandbox_id    = "{{ .SandboxID }}"
    substrate     = "ecs"
    spot_rate     = {{ .SpotRateUSD }}
    created_at    = "" # populated at apply time via Terragrunt input
    role_arn      = "" # populated at apply time: ECS task role ARN from ecs module output
    task_arn      = "" # populated at apply time: ECS task ARN from ecs module output
    cluster_arn   = "" # populated at apply time: ECS cluster ARN from ecs module output
{{- if .ComputeLimit }}
    compute_limit_usd = {{ .ComputeLimit }}
{{- end }}
{{- if .AILimit }}
    ai_limit_usd      = {{ .AILimit }}
{{- end }}
    warning_threshold = {{ .WarningThreshold }}
  }
{{- end }}
{{- if .HasGitHub }}

  # GitHub token inputs: EventBridge 45-minute schedule + Lambda for token refresh.
  # Consumed by github-token/terragrunt.hcl via read_terragrunt_config.
  github_token_inputs = {
    sandbox_id         = "{{ .SandboxID }}"
    ssm_parameter_name = "{{ .GitHubSSMPath }}"
    allowed_repos      = [{{ joinStrings .GitHubAllowedRepos }}]
    permissions        = {{ .GitHubPermissions }}
  }
{{- end }}
}
`

// ============================================================
// EC2 template parameters
// ============================================================

// ec2HCLParams holds the data for the EC2 service.hcl template.
type ec2HCLParams struct {
	ProfileName       string
	SandboxID         string
	Region            string
	RegionLabel       string
	InstanceType      string
	UseSpot           bool
	UserDataBase64    string
	VPCID             string
	PublicSubnets     []string
	AvailabilityZones []string
	SGEgressRules     []SGRule
	IAMPolicy         *IAMSessionPolicy
	// Budget enforcement fields (BUDG-03, BUDG-07)
	HasBudget        bool    // true when profile.spec.budget is set
	SpotRateUSD      float64 // pre-calculated hourly rate (0.0 when no budget)
	ComputeLimit     float64 // compute max spend USD (0 = not set)
	AILimit          float64 // AI max spend USD (0 = not set)
	CreatedAt        string  // RFC3339 timestamp for compute cost calculation
	WarningThreshold float64 // warning fraction (default 0.8)
	// Bedrock access control
	EnableBedrock bool // true unless --no-bedrock flag is set
	// GitHub token inputs (GH-02, GH-04, GH-05)
	HasGitHub          bool     // true when sourceAccess.github is set
	GitHubSSMPath      string   // /sandbox/{sandbox-id}/github-token
	GitHubAllowedRepos []string // from profile.sourceAccess.github.allowedRepos
	GitHubPermissions  string   // HCL map literal e.g. { contents = "read" }
}

// ============================================================
// ECS template parameters
// ============================================================

// ecsHCLParams holds the data for the ECS service.hcl template.
type ecsHCLParams struct {
	ProfileName           string
	SandboxID             string
	Region                string
	RegionLabel           string
	TaskCPU               int
	TaskMemory            int
	MainImage             string
	MainCPU               int
	MainMemory            int
	MainMemoryReservation int
	UseSpot               bool
	VPCID                 string
	PublicSubnets         []string
	SGEgressRules         []SGRule
	// Sidecar configuration fields (populated from profile network spec and env vars)
	AllowedDNSSuffixes   string // comma-separated allowed DNS suffixes
	AllowedHTTPHosts     string // comma-separated allowed HTTP hosts
	GitHubAllowedReposCSV string // comma-separated GitHub repos for KM_GITHUB_ALLOWED_REPOS proxy env var
	ArtifactsBucket      string // S3 bucket for sidecar OTel traces (KM_ARTIFACTS_BUCKET)
	// Sidecar image URIs (computed from KM_ACCOUNTS_APPLICATION + region + KM_SIDECAR_VERSION)
	// PLACEHOLDER_ECR/ prefix used when KM_ACCOUNTS_APPLICATION is unset.
	DNSProxyImage  string // ECR URI for km-dns-proxy sidecar
	HTTPProxyImage string // ECR URI for km-http-proxy sidecar
	AuditLogImage  string // ECR URI for km-audit-log sidecar
	TracingImage   string // ECR URI for km-tracing sidecar
	// Filesystem enforcement fields (populated from profile policy)
	HasFilesystemPolicy    bool     // true if FilesystemPolicy is set
	EffectiveWritablePaths []string // WritablePaths + auto-injected /tmp when readonlyRootFilesystem is true
	// Email fields (MAIL-02 through MAIL-05)
	HasEmail       bool   // always true in Phase 4 — every sandbox gets an email identity
	SandboxEmail   string // {sandbox-id}@{emailDomain} (from NetworkConfig.EmailDomain)
	ArtifactBucket string // km-sandbox-artifacts-ea554771 (for S3 inbox read IAM)
	// Budget enforcement fields (BUDG-03, BUDG-07)
	HasBudget        bool    // true when profile.spec.budget is set
	SpotRateUSD      float64 // pre-calculated hourly rate (0.0 when no budget)
	ComputeLimit     float64 // compute max spend USD (0 = not set)
	AILimit          float64 // AI max spend USD (0 = not set)
	CreatedAt        string  // RFC3339 timestamp for compute cost calculation
	WarningThreshold float64 // warning fraction (default 0.8)
	// GitHub token inputs (GH-02, GH-04, GH-05)
	HasGitHub          bool     // true when sourceAccess.github is set
	GitHubSSMPath      string   // /sandbox/{sandbox-id}/github-token
	GitHubAllowedRepos []string // from profile.sourceAccess.github.allowedRepos
	GitHubPermissions  string   // HCL map literal e.g. { contents = "read" }
	// Claude Code OTEL telemetry (OTEL-01, OTEL-06)
	ClaudeTelemetryEnabled        bool   // true when claudeTelemetry.enabled is true (or nil=default)
	ClaudeTelemetryLogPrompts     bool   // controls OTEL_LOG_USER_PROMPTS
	ClaudeTelemetryLogToolDetails bool   // controls OTEL_LOG_TOOL_DETAILS
	OTELResourceAttributes        string // pre-formatted: "sandbox_id=X,profile_name=Y,substrate=ecs"
	// Entrypoint env vars (Phase 36 — km-sandbox container entrypoint configuration)
	KMSandboxID         string // always set: sandbox identifier
	KMArtifactsBucket   string // S3 bucket for artifacts/CA/snapshots
	KMStateBucket       string // S3 bucket for metadata
	KMProxyCACertS3     string // s3://bucket/sidecars/km-proxy-ca.crt (set when ArtifactsBucket is known)
	KMSecretPaths       string // comma-separated SSM paths (from identity.allowedSecretPaths)
	KMOTPPaths          string // comma-separated OTP SSM paths (from otp.secrets)
	KMInitCommands      string // base64-encoded JSON array of shell commands
	KMRsyncSnapshot     string // snapshot name to restore
	KMGitHubTokenSSM    string // SSM path for GitHub token (entrypoint)
	KMGitHubAllowedRefs string // comma-separated allowed refs (entrypoint)
	KMProfileEnv        string // base64-encoded JSON env vars
	KMOperatorEmail     string // operator notification address
}

// ============================================================
// GitHub permissions HCL helper
// ============================================================

// permissionsToHCL converts a compiled permissions map to an HCL map literal.
// Used in both EC2 and ECS github_token_inputs blocks.
//
// Example: {"contents": "read"} -> { contents = "read" }
func permissionsToHCL(perms map[string]string) string {
	if len(perms) == 0 {
		return "{}"
	}
	parts := make([]string, 0, len(perms))
	for k, v := range perms {
		parts = append(parts, fmt.Sprintf("%s = %q", k, v))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

// ============================================================
// Template functions
// ============================================================

// templateFuncs provides helper functions used in service.hcl templates.
var templateFuncs = template.FuncMap{
	// sgRuleHCL serializes a SGRule into an HCL object literal.
	"sgRuleHCL": func(r SGRule) string {
		cidrs := ""
		for i, c := range r.CIDRBlocks {
			if i > 0 {
				cidrs += ", "
			}
			cidrs += fmt.Sprintf("%q", c)
		}
		return fmt.Sprintf(
			"{ from_port = %d, to_port = %d, protocol = %q, cidr_blocks = [%s], description = %q }",
			r.FromPort, r.ToPort, r.Protocol, cidrs, r.Description,
		)
	},
	// joinStrings produces a comma-separated HCL list of quoted strings.
	"joinStrings": func(ss []string) string {
		quoted := make([]string, len(ss))
		for i, s := range ss {
			quoted[i] = fmt.Sprintf("%q", s)
		}
		return strings.Join(quoted, ", ")
	},
	// volumeName converts an absolute path to a valid ECS volume name.
	// e.g. "/tmp" -> "vol-tmp", "/workspace/data" -> "vol-workspace-data"
	"volumeName": func(path string) string {
		// Strip leading slash, replace remaining slashes with dashes
		name := strings.TrimPrefix(path, "/")
		name = strings.ReplaceAll(name, "/", "-")
		return "vol-" + name
	},
}

// joinGitHubAllowedReposCSV returns the AllowedRepos slice as a comma-separated string
// suitable for the KM_GITHUB_ALLOWED_REPOS proxy environment variable.
// Returns empty string when GitHub config is nil or AllowedRepos is empty.
func joinGitHubAllowedReposCSV(p *profile.SandboxProfile) string {
	if p.Spec.SourceAccess.GitHub == nil || len(p.Spec.SourceAccess.GitHub.AllowedRepos) == 0 {
		return ""
	}
	return strings.Join(p.Spec.SourceAccess.GitHub.AllowedRepos, ",")
}

// ============================================================
// EC2 service.hcl generation
// ============================================================

// generateEC2ServiceHCL produces the service.hcl content for an EC2/ec2spot sandbox.
// NetworkConfig holds shared VPC/subnet info from km init.
type NetworkConfig struct {
	VPCID             string
	PublicSubnets     []string
	AvailabilityZones []string
	RegionLabel       string
	// EmailDomain is the sandboxes subdomain (e.g. "sandboxes.klankermaker.ai").
	// When empty, defaults to "sandboxes.klankermaker.ai". Derived from Config.Domain
	// as "sandboxes."+domain so forks use their own domain without code changes.
	EmailDomain string
	// ArtifactsBucket is the S3 bucket for sidecars, bootstrap scripts, etc.
	ArtifactsBucket string
	// SpotRateUSD is the resolved spot instance hourly rate in USD.
	// Populated by create.go from the AWS Pricing API (or static fallback table)
	// before calling Compile(). Zero when no budget or rate lookup is skipped.
	SpotRateUSD float64
	// Alias is the optional human-friendly sandbox alias (e.g. "orc-1").
	// When set, the sandbox can also receive and send email as {alias}@{emailDomain}.
	Alias string
}

// budgetHCLFields extracts the budget-related template fields from a SandboxProfile.
// Returns zero values when budget is nil (enforcement disabled).
func budgetHCLFields(p *profile.SandboxProfile) (hasBudget bool, computeLimit, aiLimit, warningThreshold float64) {
	if p.Spec.Budget == nil {
		return false, 0, 0, 0
	}
	hasBudget = true
	threshold := p.Spec.Budget.WarningThreshold
	if threshold <= 0 {
		threshold = 0.8
	}
	if p.Spec.Budget.Compute != nil {
		computeLimit = p.Spec.Budget.Compute.MaxSpendUSD
	}
	if p.Spec.Budget.AI != nil {
		aiLimit = p.Spec.Budget.AI.MaxSpendUSD
	}
	return hasBudget, computeLimit, aiLimit, threshold
}

func generateEC2ServiceHCL(p *profile.SandboxProfile, sandboxID string, useSpot bool, sgRules []SGRule, iamPolicy *IAMSessionPolicy, userData string, network *NetworkConfig) (string, error) {
	tmpl, err := template.New("ec2-service-hcl").Funcs(templateFuncs).Parse(ec2ServiceHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse ec2 service.hcl template: %w", err)
	}

	hasBudget, computeLimit, aiLimit, warningThreshold := budgetHCLFields(p)

	params := ec2HCLParams{
		EnableBedrock:     p.Spec.Execution.UseBedrock,
		ProfileName:       p.Metadata.Name,
		SandboxID:         sandboxID,
		Region:            p.Spec.Runtime.Region,
		RegionLabel:       network.RegionLabel,
		InstanceType:      p.Spec.Runtime.InstanceType,
		UseSpot:           useSpot,
		UserDataBase64:    userData,
		VPCID:             network.VPCID,
		PublicSubnets:     network.PublicSubnets,
		AvailabilityZones: network.AvailabilityZones,
		SGEgressRules:     sgRules,
		IAMPolicy:         iamPolicy,
		// Budget enforcement fields
		HasBudget:        hasBudget,
		SpotRateUSD:      network.SpotRateUSD,
		ComputeLimit:     computeLimit,
		AILimit:          aiLimit,
		WarningThreshold: warningThreshold,
		CreatedAt:        time.Now().UTC().Format(time.RFC3339),
	}

	// Populate GitHub token fields when sourceAccess.github is configured with at least one repo.
	// Empty allowedRepos is treated as deny-by-default (same as nil github config).
	if p.Spec.SourceAccess.GitHub != nil && len(p.Spec.SourceAccess.GitHub.AllowedRepos) > 0 {
		params.HasGitHub = true
		params.GitHubSSMPath = fmt.Sprintf("/sandbox/%s/github-token", sandboxID)
		params.GitHubAllowedRepos = p.Spec.SourceAccess.GitHub.AllowedRepos
		compiledPerms := pkggithub.CompilePermissions(nil)
		params.GitHubPermissions = permissionsToHCL(compiledPerms)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("execute ec2 service.hcl template: %w", err)
	}
	return buf.String(), nil
}

// ============================================================
// ECS service.hcl generation
// ============================================================

// ecsDefaultCPU and ecsDefaultMemory are the total Fargate task allocations
// when no override is provided in the profile.
const ecsDefaultCPU = 1024
const ecsDefaultMemory = 2048

// generateECSServiceHCL produces the service.hcl content for an ECS/ecs-cluster sandbox.
func generateECSServiceHCL(p *profile.SandboxProfile, sandboxID string, useSpot bool, sgRules []SGRule, network *NetworkConfig) (string, error) {
	tmpl, err := template.New("ecs-service-hcl").Funcs(templateFuncs).Parse(ecsServiceHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse ecs service.hcl template: %w", err)
	}

	// Main container gets the majority of CPU/memory; sidecars share the rest.
	// Total: 1024 CPU, 2048 MiB memory
	// Sidecars: 2x128 CPU + 2x64 CPU = 384 CPU, 2x256 + 2x128 = 768 MiB
	// Main gets the remainder: 640 CPU, 1280 MiB
	mainCPU := ecsDefaultCPU - (128 + 128 + 64 + 64)
	mainMemory := ecsDefaultMemory - (256 + 256 + 128 + 128)
	mainMemoryReservation := mainMemory / 2

	// Email domain for Phase 4: use domain from NetworkConfig when set, otherwise default.
	emailDomain := "sandboxes.klankermaker.ai"
	if network != nil && network.EmailDomain != "" {
		emailDomain = network.EmailDomain
	}
	artifactBucket := os.Getenv("KM_ARTIFACTS_BUCKET")
	// No hardcoded fallback — artifacts_bucket should be set via km-config.yaml or env var.

	hasBudget, computeLimit, aiLimit, warningThreshold := budgetHCLFields(p)

	// Compute ECR image URIs for sidecar containers (PROV-10).
	// KM_ACCOUNTS_APPLICATION provides the AWS account ID for the ECR registry.
	// KM_SIDECAR_VERSION controls the image tag; defaults to "latest" when unset.
	accountID := os.Getenv("KM_ACCOUNTS_APPLICATION")
	imageTag := os.Getenv("KM_SIDECAR_VERSION")
	if imageTag == "" {
		imageTag = "latest"
	}
	var ecrRegistry string
	if accountID != "" {
		ecrRegistry = fmt.Sprintf("%s.dkr.ecr.%s.amazonaws.com", accountID, p.Spec.Runtime.Region)
	} else {
		ecrRegistry = "PLACEHOLDER_ECR"
	}
	sidecarImage := func(name string) string {
		return ecrRegistry + "/km-" + name + ":" + imageTag
	}

	// mainImage uses the same ECR registry as sidecars — km-sandbox:{version}
	// This replaces the MAIN_IMAGE_PLACEHOLDER that existed before the sandbox
	// container image was created in Phase 36.
	mainImage := sidecarImage("sandbox")

	params := ecsHCLParams{
		ProfileName:           p.Metadata.Name,
		SandboxID:             sandboxID,
		Region:                p.Spec.Runtime.Region,
		RegionLabel:           network.RegionLabel,
		TaskCPU:               ecsDefaultCPU,
		TaskMemory:            ecsDefaultMemory,
		MainImage:             mainImage,
		MainCPU:               mainCPU,
		MainMemory:            mainMemory,
		MainMemoryReservation: mainMemoryReservation,
		UseSpot:               useSpot,
		VPCID:                 network.VPCID,
		PublicSubnets:         network.PublicSubnets,
		SGEgressRules:         sgRules,
		AllowedDNSSuffixes:    strings.Join(p.Spec.Network.Egress.AllowedDNSSuffixes, ","),
		AllowedHTTPHosts:      strings.Join(append(p.Spec.Network.Egress.AllowedHosts, p.Spec.Network.Egress.AllowedDNSSuffixes...), ","),
		GitHubAllowedReposCSV: joinGitHubAllowedReposCSV(p),
		ArtifactsBucket:       artifactBucket,
		// Sidecar ECR image URIs computed from KM_ACCOUNTS_APPLICATION + region + KM_SIDECAR_VERSION.
		DNSProxyImage:  sidecarImage("dns-proxy"),
		HTTPProxyImage: sidecarImage("http-proxy"),
		AuditLogImage:  sidecarImage("audit-log"),
		TracingImage:   sidecarImage("tracing"),
		// Email fields — every Phase 4 sandbox gets an email identity.
		HasEmail:       true,
		SandboxEmail:   sandboxID + "@" + emailDomain,
		ArtifactBucket: artifactBucket,
		// Budget enforcement fields
		HasBudget:        hasBudget,
		SpotRateUSD:      network.SpotRateUSD,
		ComputeLimit:     computeLimit,
		AILimit:          aiLimit,
		WarningThreshold: warningThreshold,
		CreatedAt:        time.Now().UTC().Format(time.RFC3339),
	}

	// Populate GitHub token fields when sourceAccess.github is configured with at least one repo.
	// Empty allowedRepos is treated as deny-by-default (same as nil github config).
	if p.Spec.SourceAccess.GitHub != nil && len(p.Spec.SourceAccess.GitHub.AllowedRepos) > 0 {
		params.HasGitHub = true
		params.GitHubSSMPath = fmt.Sprintf("/sandbox/%s/github-token", sandboxID)
		params.GitHubAllowedRepos = p.Spec.SourceAccess.GitHub.AllowedRepos
		compiledPerms := pkggithub.CompilePermissions(nil)
		params.GitHubPermissions = permissionsToHCL(compiledPerms)
	}

	// Populate Phase 36 entrypoint env vars (km-sandbox container configuration).
	// KM_SANDBOX_ID and KM_ARTIFACTS_BUCKET are always set; others are conditional.
	params.KMSandboxID = sandboxID
	params.KMArtifactsBucket = artifactBucket
	if artifactBucket != "" {
		params.KMProxyCACertS3 = fmt.Sprintf("s3://%s/sidecars/km-proxy-ca.crt", artifactBucket)
	}
	// KM_SECRET_PATHS: comma-separated SSM paths from identity.allowedSecretPaths
	if len(p.Spec.Identity.AllowedSecretPaths) > 0 {
		params.KMSecretPaths = strings.Join(p.Spec.Identity.AllowedSecretPaths, ",")
	}
	// KM_OTP_PATHS: comma-separated OTP SSM paths from otp.secrets
	if p.Spec.OTP != nil && len(p.Spec.OTP.Secrets) > 0 {
		params.KMOTPPaths = strings.Join(p.Spec.OTP.Secrets, ",")
	}
	// KM_INIT_COMMANDS: base64-encoded JSON array of shell commands
	if len(p.Spec.Execution.InitCommands) > 0 {
		initJSON, err := json.Marshal(p.Spec.Execution.InitCommands)
		if err == nil {
			params.KMInitCommands = base64.StdEncoding.EncodeToString(initJSON)
		}
	}
	// KM_PROFILE_ENV: base64-encoded JSON map of env vars (includes Bedrock vars if useBedrock)
	profileEnv := mergeBedrockEnv(p)
	if len(profileEnv) > 0 {
		envJSON, err := json.Marshal(profileEnv)
		if err == nil {
			params.KMProfileEnv = base64.StdEncoding.EncodeToString(envJSON)
		}
	}
	// KM_OPERATOR_EMAIL: from environment variable
	params.KMOperatorEmail = os.Getenv("KM_OPERATOR_EMAIL")
	// KM_GITHUB_TOKEN_SSM and KM_GITHUB_ALLOWED_REFS: use the already-populated GitHub fields
	if params.HasGitHub {
		params.KMGitHubTokenSSM = params.GitHubSSMPath
		if p.Spec.SourceAccess.GitHub != nil && len(p.Spec.SourceAccess.GitHub.AllowedRefs) > 0 {
			params.KMGitHubAllowedRefs = strings.Join(p.Spec.SourceAccess.GitHub.AllowedRefs, ",")
		}
	}

	// Populate Claude Code OTEL telemetry fields (OTEL-01, OTEL-06).
	// IsEnabled() returns true when ClaudeTelemetry is nil (default on).
	ct := p.Spec.Observability.ClaudeTelemetry
	params.ClaudeTelemetryEnabled = ct.IsEnabled()
	if ct != nil {
		params.ClaudeTelemetryLogPrompts = ct.LogPrompts
		params.ClaudeTelemetryLogToolDetails = ct.LogToolDetails
	}
	params.OTELResourceAttributes = fmt.Sprintf("sandbox_id=%s,profile_name=%s,substrate=ecs", sandboxID, p.Metadata.Name)

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("execute ecs service.hcl template: %w", err)
	}
	return buf.String(), nil
}
