package compiler

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// ============================================================
// EC2 service.hcl template
// ============================================================

// ec2ServiceHCLTemplate generates a service.hcl locals block for EC2/ec2spot substrate.
// It includes sg_egress_rules and iam_session_policy in module_inputs so that the
// compiled security configuration actually reaches Terraform (NETW-01, NETW-04).
// When a budget is defined in the profile, a budget_enforcer module block is included.
const ec2ServiceHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Profile: {{ .ProfileName }}

  sandbox_id       = "{{ .SandboxID }}"
  substrate_module = "ec2spot"
  region_label     = "{{ .RegionLabel }}"
  region_full      = "{{ .Region }}"

  module_inputs = {
    sandbox_id         = "{{ .SandboxID }}"
    vpc_id             = "{{ .VPCID }}"
    public_subnets     = [{{ joinStrings .PublicSubnets }}]
    availability_zones = [{{ joinStrings .AvailabilityZones }}]

    ec2spots = [
      {
        count         = 1
        region        = "{{ .Region }}"
        sandbox_id    = "{{ .SandboxID }}"
        instance_type = "{{ .InstanceType }}"
        use_spot      = {{ .UseSpot }}
{{- if .UseSpot }}
        spot_price_multiplier  = 1.05
        spot_price_offset      = 0.0005
        block_duration_minutes = 0
{{- end }}
        user_data_base64 = "{{ .UserDataBase64 }}"
      }
    ]

    sg_egress_rules = [
{{- range .SGEgressRules }}
      {{ sgRuleHCL . }},
{{- end }}
    ]

    iam_session_policy = {
      max_session_duration = {{ .IAMPolicy.MaxSessionDuration }}
      allowed_regions      = [{{ joinStrings .IAMPolicy.AllowedRegions }}]
    }
  }
{{- if .HasBudget }}

  # Budget enforcer: EventBridge 1-minute schedule + Lambda for compute/AI enforcement.
  # Requires profile.spec.budget to be set (compute and/or AI limits).
  budget_enforcer_inputs = {
    sandbox_id     = "{{ .SandboxID }}"
    substrate      = "ec2"
    spot_rate      = {{ .SpotRateUSD }}
    instance_type  = "{{ .InstanceType }}"
    created_at     = "" # populated at apply time via Terragrunt input
    role_arn       = "" # populated at apply time: IAM role ARN from ec2spot module output
    instance_id    = "" # populated at apply time: EC2 instance ID from ec2spot module output
{{- if .ComputeLimit }}
    compute_limit_usd = {{ .ComputeLimit }}
{{- end }}
{{- if .AILimit }}
    ai_limit_usd      = {{ .AILimit }}
{{- end }}
    warning_threshold = {{ .WarningThreshold }}
  }
{{- end }}
}
`

// ============================================================
// ECS service.hcl template
// ============================================================

// ecsServiceHCLTemplate generates a service.hcl locals block for ECS substrate.
// Uses the combined ecs module (cluster + task + service in one).
// When a budget is defined, a budget_enforcer_inputs block is appended.
const ecsServiceHCLTemplate = `locals {
  # Generated by the klankrmkr profile compiler. DO NOT EDIT.
  # Profile: {{ .ProfileName }}

  sandbox_id       = "{{ .SandboxID }}"
  substrate_module = "ecs"
  region_label     = "{{ .RegionLabel }}"
  region_full      = "{{ .Region }}"

  module_inputs = {
    sandbox_id     = "{{ .SandboxID }}"
    vpc_id         = "{{ .VPCID }}"
    public_subnets = [{{ joinStrings .PublicSubnets }}]
    use_spot       = {{ .UseSpot }}
    task_cpu       = {{ .TaskCPU }}
    task_memory    = {{ .TaskMemory }}
{{- if .EffectiveWritablePaths }}

    volumes = [
{{- range .EffectiveWritablePaths }}
      { name = "{{ volumeName . }}", scope = "task" },
{{- end }}
    ]
{{- end }}

    containers = [
      {
        name               = "main"
        image              = "{{ .MainImage }}"
        cpu                = {{ .MainCPU }}
        memory             = {{ .MainMemory }}
        memory_reservation = {{ .MainMemoryReservation }}
        essential          = true
        command            = []
{{- if .HasFilesystemPolicy }}
        readonlyRootFilesystem = true
{{- end }}
        environment = [
          { name = "SANDBOX_ID",    value = "{{ .SandboxID }}" },
          { name = "KM_LABEL",      value = "km" },
          { name = "HTTP_PROXY",    value = "http://localhost:3128" },
          { name = "HTTPS_PROXY",   value = "http://localhost:3128" },
          { name = "NO_PROXY",      value = "169.254.169.254,169.254.170.2,localhost,127.0.0.1" },
{{- if .HasEmail }}
          { name = "KM_EMAIL_ADDRESS", value = "{{ .SandboxEmail }}" },
{{- end }}
        ]
{{- if .EffectiveWritablePaths }}
        mountPoints = [
{{- range .EffectiveWritablePaths }}
          { sourceVolume = "{{ volumeName . }}", containerPath = "{{ . }}", readOnly = false },
{{- end }}
        ]
{{- end }}
        port_mappings     = []
        log_stream_prefix = "main"
      },
      {
        name               = "km-dns-proxy"
        image              = "{{ .DNSProxyImage }}"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",       value = "{{ .SandboxID }}" },
          { name = "ALLOWED_SUFFIXES", value = "{{ .AllowedDNSSuffixes }}" },
          { name = "UPSTREAM_DNS",     value = "169.254.169.253" },
        ]
        port_mappings     = []
        log_stream_prefix = "dns-proxy"
      },
      {
        name               = "km-http-proxy"
        image              = "{{ .HTTPProxyImage }}"
        cpu                = 128
        memory             = 256
        memory_reservation = 128
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",    value = "{{ .SandboxID }}" },
          { name = "ALLOWED_HOSTS", value = "{{ .AllowedHTTPHosts }}" },
          { name = "PROXY_PORT",    value = "3128" },
        ]
        port_mappings     = []
        log_stream_prefix = "http-proxy"
      },
      {
        name               = "km-audit-log"
        image              = "{{ .AuditLogImage }}"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = true
        command            = []
        environment = [
          { name = "SANDBOX_ID",      value = "{{ .SandboxID }}" },
          { name = "AUDIT_LOG_DEST",  value = "cloudwatch" },
          { name = "CW_LOG_GROUP",    value = "/km/sandboxes/{{ .SandboxID }}/" },
          { name = "AWS_REGION",      value = "{{ .Region }}" },
        ]
        log_configuration = {
          log_driver = "awslogs"
          options = {
            "awslogs-group"         = "/km/sidecars/{{ .SandboxID }}"
            "awslogs-region"        = "{{ .Region }}"
            "awslogs-stream-prefix" = "audit-log"
          }
        }
        port_mappings     = []
        log_stream_prefix = "audit-log"
      },
      {
        name               = "km-tracing"
        image              = "{{ .TracingImage }}"
        cpu                = 64
        memory             = 128
        memory_reservation = 64
        essential          = false
        command            = []
        environment = [
          { name = "SANDBOX_ID",     value = "{{ .SandboxID }}" },
          { name = "OTEL_S3_BUCKET", value = "{{ .ArtifactsBucket }}" },
          { name = "AWS_REGION",     value = "{{ .Region }}" },
        ]
        port_mappings     = []
        log_stream_prefix = "tracing"
      }
    ]

    sg_egress_rules = [
{{- range .SGEgressRules }}
      {{ sgRuleHCL . }},
{{- end }}
    ]
{{- if .HasEmail }}

    task_role_policy_statements = [
      {
        effect   = "Allow"
        actions  = ["ses:SendEmail", "ses:SendRawEmail"]
        resources = ["*"]
        condition = {
          test     = "StringEquals"
          variable = "ses:FromAddress"
          values   = ["{{ .SandboxEmail }}"]
        }
      },
      {
        effect    = "Allow"
        actions   = ["s3:ListObjectsV2", "s3:GetObject"]
        resources = ["arn:aws:s3:::{{ .ArtifactBucket }}/mail/{{ .SandboxID }}/*"]
      },
      {
        effect    = "Allow"
        actions   = ["s3:ListBucket"]
        resources = ["arn:aws:s3:::{{ .ArtifactBucket }}"]
        condition = {
          test     = "StringLike"
          variable = "s3:prefix"
          values   = ["mail/{{ .SandboxID }}/*"]
        }
      },
    ]
{{- end }}
  }
{{- if .HasBudget }}

  # Budget enforcer: EventBridge 1-minute schedule + Lambda for compute/AI enforcement.
  # Requires profile.spec.budget to be set (compute and/or AI limits).
  budget_enforcer_inputs = {
    sandbox_id    = "{{ .SandboxID }}"
    substrate     = "ecs"
    spot_rate     = {{ .SpotRateUSD }}
    created_at    = "" # populated at apply time via Terragrunt input
    role_arn      = "" # populated at apply time: ECS task role ARN from ecs module output
    task_arn      = "" # populated at apply time: ECS task ARN from ecs module output
    cluster_arn   = "" # populated at apply time: ECS cluster ARN from ecs module output
{{- if .ComputeLimit }}
    compute_limit_usd = {{ .ComputeLimit }}
{{- end }}
{{- if .AILimit }}
    ai_limit_usd      = {{ .AILimit }}
{{- end }}
    warning_threshold = {{ .WarningThreshold }}
  }
{{- end }}
}
`

// ============================================================
// EC2 template parameters
// ============================================================

// ec2HCLParams holds the data for the EC2 service.hcl template.
type ec2HCLParams struct {
	ProfileName       string
	SandboxID         string
	Region            string
	RegionLabel       string
	InstanceType      string
	UseSpot           bool
	UserDataBase64    string
	VPCID             string
	PublicSubnets     []string
	AvailabilityZones []string
	SGEgressRules     []SGRule
	IAMPolicy         *IAMSessionPolicy
	// Budget enforcement fields (BUDG-03, BUDG-07)
	HasBudget        bool    // true when profile.spec.budget is set
	SpotRateUSD      float64 // pre-calculated hourly rate (0.0 when no budget)
	ComputeLimit     float64 // compute max spend USD (0 = not set)
	AILimit          float64 // AI max spend USD (0 = not set)
	WarningThreshold float64 // warning fraction (default 0.8)
}

// ============================================================
// ECS template parameters
// ============================================================

// ecsHCLParams holds the data for the ECS service.hcl template.
type ecsHCLParams struct {
	ProfileName           string
	SandboxID             string
	Region                string
	RegionLabel           string
	TaskCPU               int
	TaskMemory            int
	MainImage             string
	MainCPU               int
	MainMemory            int
	MainMemoryReservation int
	UseSpot               bool
	VPCID                 string
	PublicSubnets         []string
	SGEgressRules         []SGRule
	// Sidecar configuration fields (populated from profile network spec and env vars)
	AllowedDNSSuffixes string // comma-separated allowed DNS suffixes
	AllowedHTTPHosts   string // comma-separated allowed HTTP hosts
	ArtifactsBucket    string // S3 bucket for sidecar OTel traces (KM_ARTIFACTS_BUCKET)
	// Sidecar image URIs (computed from KM_ACCOUNTS_APPLICATION + region + KM_SIDECAR_VERSION)
	// PLACEHOLDER_ECR/ prefix used when KM_ACCOUNTS_APPLICATION is unset.
	DNSProxyImage  string // ECR URI for km-dns-proxy sidecar
	HTTPProxyImage string // ECR URI for km-http-proxy sidecar
	AuditLogImage  string // ECR URI for km-audit-log sidecar
	TracingImage   string // ECR URI for km-tracing sidecar
	// Filesystem enforcement fields (populated from profile policy)
	HasFilesystemPolicy    bool     // true if FilesystemPolicy is set
	EffectiveWritablePaths []string // WritablePaths + auto-injected /tmp when readonlyRootFilesystem is true
	// Email fields (MAIL-02 through MAIL-05)
	HasEmail       bool   // always true in Phase 4 — every sandbox gets an email identity
	SandboxEmail   string // {sandbox-id}@{emailDomain} (from NetworkConfig.EmailDomain)
	ArtifactBucket string // km-sandbox-artifacts-ea554771 (for S3 inbox read IAM)
	// Budget enforcement fields (BUDG-03, BUDG-07)
	HasBudget        bool    // true when profile.spec.budget is set
	SpotRateUSD      float64 // pre-calculated hourly rate (0.0 when no budget)
	ComputeLimit     float64 // compute max spend USD (0 = not set)
	AILimit          float64 // AI max spend USD (0 = not set)
	WarningThreshold float64 // warning fraction (default 0.8)
}

// ============================================================
// Template functions
// ============================================================

// templateFuncs provides helper functions used in service.hcl templates.
var templateFuncs = template.FuncMap{
	// sgRuleHCL serializes a SGRule into an HCL object literal.
	"sgRuleHCL": func(r SGRule) string {
		cidrs := ""
		for i, c := range r.CIDRBlocks {
			if i > 0 {
				cidrs += ", "
			}
			cidrs += fmt.Sprintf("%q", c)
		}
		return fmt.Sprintf(
			"{ from_port = %d, to_port = %d, protocol = %q, cidr_blocks = [%s], description = %q }",
			r.FromPort, r.ToPort, r.Protocol, cidrs, r.Description,
		)
	},
	// joinStrings produces a comma-separated HCL list of quoted strings.
	"joinStrings": func(ss []string) string {
		quoted := make([]string, len(ss))
		for i, s := range ss {
			quoted[i] = fmt.Sprintf("%q", s)
		}
		return strings.Join(quoted, ", ")
	},
	// volumeName converts an absolute path to a valid ECS volume name.
	// e.g. "/tmp" -> "vol-tmp", "/workspace/data" -> "vol-workspace-data"
	"volumeName": func(path string) string {
		// Strip leading slash, replace remaining slashes with dashes
		name := strings.TrimPrefix(path, "/")
		name = strings.ReplaceAll(name, "/", "-")
		return "vol-" + name
	},
}

// ============================================================
// EC2 service.hcl generation
// ============================================================

// generateEC2ServiceHCL produces the service.hcl content for an EC2/ec2spot sandbox.
// NetworkConfig holds shared VPC/subnet info from km init.
type NetworkConfig struct {
	VPCID             string
	PublicSubnets     []string
	AvailabilityZones []string
	RegionLabel       string
	// EmailDomain is the sandboxes subdomain (e.g. "sandboxes.klankermaker.ai").
	// When empty, defaults to "sandboxes.klankermaker.ai". Derived from Config.Domain
	// as "sandboxes."+domain so forks use their own domain without code changes.
	EmailDomain string
	// SpotRateUSD is the resolved spot instance hourly rate in USD.
	// Populated by create.go from the AWS Pricing API (or static fallback table)
	// before calling Compile(). Zero when no budget or rate lookup is skipped.
	SpotRateUSD float64
}

// budgetHCLFields extracts the budget-related template fields from a SandboxProfile.
// Returns zero values when budget is nil (enforcement disabled).
func budgetHCLFields(p *profile.SandboxProfile) (hasBudget bool, computeLimit, aiLimit, warningThreshold float64) {
	if p.Spec.Budget == nil {
		return false, 0, 0, 0
	}
	hasBudget = true
	threshold := p.Spec.Budget.WarningThreshold
	if threshold <= 0 {
		threshold = 0.8
	}
	if p.Spec.Budget.Compute != nil {
		computeLimit = p.Spec.Budget.Compute.MaxSpendUSD
	}
	if p.Spec.Budget.AI != nil {
		aiLimit = p.Spec.Budget.AI.MaxSpendUSD
	}
	return hasBudget, computeLimit, aiLimit, threshold
}

func generateEC2ServiceHCL(p *profile.SandboxProfile, sandboxID string, useSpot bool, sgRules []SGRule, iamPolicy *IAMSessionPolicy, userData string, network *NetworkConfig) (string, error) {
	tmpl, err := template.New("ec2-service-hcl").Funcs(templateFuncs).Parse(ec2ServiceHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse ec2 service.hcl template: %w", err)
	}

	hasBudget, computeLimit, aiLimit, warningThreshold := budgetHCLFields(p)

	params := ec2HCLParams{
		ProfileName:       p.Metadata.Name,
		SandboxID:         sandboxID,
		Region:            p.Spec.Runtime.Region,
		RegionLabel:       network.RegionLabel,
		InstanceType:      p.Spec.Runtime.InstanceType,
		UseSpot:           useSpot,
		UserDataBase64:    userData,
		VPCID:             network.VPCID,
		PublicSubnets:     network.PublicSubnets,
		AvailabilityZones: network.AvailabilityZones,
		SGEgressRules:     sgRules,
		IAMPolicy:         iamPolicy,
		// Budget enforcement fields
		HasBudget:        hasBudget,
		SpotRateUSD:      network.SpotRateUSD,
		ComputeLimit:     computeLimit,
		AILimit:          aiLimit,
		WarningThreshold: warningThreshold,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("execute ec2 service.hcl template: %w", err)
	}
	return buf.String(), nil
}

// ============================================================
// ECS service.hcl generation
// ============================================================

// ecsDefaultCPU and ecsDefaultMemory are the total Fargate task allocations
// when no override is provided in the profile.
const ecsDefaultCPU = 1024
const ecsDefaultMemory = 2048

// generateECSServiceHCL produces the service.hcl content for an ECS/ecs-cluster sandbox.
func generateECSServiceHCL(p *profile.SandboxProfile, sandboxID string, useSpot bool, sgRules []SGRule, network *NetworkConfig) (string, error) {
	tmpl, err := template.New("ecs-service-hcl").Funcs(templateFuncs).Parse(ecsServiceHCLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse ecs service.hcl template: %w", err)
	}

	// Main container gets the majority of CPU/memory; sidecars share the rest.
	// Total: 1024 CPU, 2048 MiB memory
	// Sidecars: 2x128 CPU + 2x64 CPU = 384 CPU, 2x256 + 2x128 = 768 MiB
	// Main gets the remainder: 640 CPU, 1280 MiB
	mainCPU := ecsDefaultCPU - (128 + 128 + 64 + 64)
	mainMemory := ecsDefaultMemory - (256 + 256 + 128 + 128)
	mainMemoryReservation := mainMemory / 2

	// Use profile image if set, otherwise placeholder
	mainImage := "MAIN_IMAGE_PLACEHOLDER"
	if p.Spec.Runtime.InstanceType != "" {
		// For ECS, instanceType holds the Fargate task size (e.g. "512/1024")
		// We keep the placeholder here; real image set at provision time.
	}

	// Email domain for Phase 4: use domain from NetworkConfig when set, otherwise default.
	emailDomain := "sandboxes.klankermaker.ai"
	if network != nil && network.EmailDomain != "" {
		emailDomain = network.EmailDomain
	}
	const defaultArtifactBucket = "km-sandbox-artifacts-ea554771"
	artifactBucket := os.Getenv("KM_ARTIFACTS_BUCKET")
	if artifactBucket == "" {
		artifactBucket = defaultArtifactBucket
	}

	hasBudget, computeLimit, aiLimit, warningThreshold := budgetHCLFields(p)

	// Compute ECR image URIs for sidecar containers (PROV-10).
	// KM_ACCOUNTS_APPLICATION provides the AWS account ID for the ECR registry.
	// KM_SIDECAR_VERSION controls the image tag; defaults to "latest" when unset.
	accountID := os.Getenv("KM_ACCOUNTS_APPLICATION")
	imageTag := os.Getenv("KM_SIDECAR_VERSION")
	if imageTag == "" {
		imageTag = "latest"
	}
	var ecrRegistry string
	if accountID != "" {
		ecrRegistry = fmt.Sprintf("%s.dkr.ecr.%s.amazonaws.com", accountID, p.Spec.Runtime.Region)
	} else {
		ecrRegistry = "PLACEHOLDER_ECR"
	}
	sidecarImage := func(name string) string {
		return ecrRegistry + "/km-" + name + ":" + imageTag
	}

	params := ecsHCLParams{
		ProfileName:           p.Metadata.Name,
		SandboxID:             sandboxID,
		Region:                p.Spec.Runtime.Region,
		RegionLabel:           network.RegionLabel,
		TaskCPU:               ecsDefaultCPU,
		TaskMemory:            ecsDefaultMemory,
		MainImage:             mainImage,
		MainCPU:               mainCPU,
		MainMemory:            mainMemory,
		MainMemoryReservation: mainMemoryReservation,
		UseSpot:               useSpot,
		VPCID:                 network.VPCID,
		PublicSubnets:         network.PublicSubnets,
		SGEgressRules:         sgRules,
		AllowedDNSSuffixes:    strings.Join(p.Spec.Network.Egress.AllowedDNSSuffixes, ","),
		AllowedHTTPHosts:      strings.Join(p.Spec.Network.Egress.AllowedHosts, ","),
		ArtifactsBucket:       artifactBucket,
		// Sidecar ECR image URIs computed from KM_ACCOUNTS_APPLICATION + region + KM_SIDECAR_VERSION.
		DNSProxyImage:  sidecarImage("dns-proxy"),
		HTTPProxyImage: sidecarImage("http-proxy"),
		AuditLogImage:  sidecarImage("audit-log"),
		TracingImage:   sidecarImage("tracing"),
		// Email fields — every Phase 4 sandbox gets an email identity.
		HasEmail:       true,
		SandboxEmail:   sandboxID + "@" + emailDomain,
		ArtifactBucket: artifactBucket,
		// Budget enforcement fields
		HasBudget:        hasBudget,
		SpotRateUSD:      network.SpotRateUSD,
		ComputeLimit:     computeLimit,
		AILimit:          aiLimit,
		WarningThreshold: warningThreshold,
	}

	// Populate filesystem enforcement fields (nil-safe).
	if p.Spec.Policy.FilesystemPolicy != nil {
		params.HasFilesystemPolicy = true
		// Collect the declared writable paths.
		writablePaths := make([]string, len(p.Spec.Policy.FilesystemPolicy.WritablePaths))
		copy(writablePaths, p.Spec.Policy.FilesystemPolicy.WritablePaths)
		// Auto-inject /tmp when readonlyRootFilesystem is enabled and /tmp is not already listed.
		hasTmp := false
		for _, wp := range writablePaths {
			if wp == "/tmp" {
				hasTmp = true
				break
			}
		}
		if !hasTmp {
			writablePaths = append([]string{"/tmp"}, writablePaths...)
		}
		params.EffectiveWritablePaths = writablePaths
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("execute ecs service.hcl template: %w", err)
	}
	return buf.String(), nil
}
