package compiler

import (
	"bytes"
	"strings"
	"text/template"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// userDataTemplate generates the EC2 bootstrap script.
// It performs: SSM agent install, IMDSv2 verification, secret injection,
// optional GitHub token injection, filesystem bind mounts (2.5), sidecar install,
// iptables DNAT, spot interruption handler (6.5), and SANDBOX_READY signal.
const userDataTemplate = `#!/bin/bash
# Klankrmkr sandbox bootstrap — generated by profile compiler
# DO NOT EDIT — this file is overwritten on each provision

set -euo pipefail

# ============================================================
# 1. SSM Agent: install and start
# ============================================================
echo "[km-bootstrap] Installing amazon-ssm-agent..."
yum install -y amazon-ssm-agent 2>&1 | tee -a /var/log/km-bootstrap.log
systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent
echo "[km-bootstrap] SSM agent started"

# ============================================================
# 2. IMDSv2: verify token-based metadata access is working
# ============================================================
echo "[km-bootstrap] Verifying IMDSv2 token..."
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>&1)
if [ -z "$IMDS_TOKEN" ]; then
  echo "[km-bootstrap] ERROR: IMDSv2 token fetch failed — cannot access instance metadata" >&2
  exit 1
fi
echo "[km-bootstrap] IMDSv2 token obtained successfully"

# Retrieve instance region for SSM API calls
REGION=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
  http://169.254.169.254/latest/meta-data/placement/region)
export AWS_DEFAULT_REGION="${REGION}"
echo "[km-bootstrap] Region: $REGION"

# ============================================================
# 2.5. Filesystem policy: read-only bind mounts (before sidecar startup)
# ============================================================
{{- if .ReadOnlyPaths }}
echo "[km-bootstrap] Applying filesystem read-only bind mounts..."
{{- range .ReadOnlyPaths }}
mount --bind "{{ . }}" "{{ . }}"
mount -o remount,bind,ro "{{ . }}"
{{- end }}
echo "[km-bootstrap] Read-only bind mounts applied"
{{- end }}

# ============================================================
# 3. Secret injection: fetch allowed SSM paths and export as env vars
# ============================================================
{{- if .SecretPaths }}
echo "[km-bootstrap] Injecting secrets from SSM..."
declare -A SECRET_PATHS=(
{{- range .SecretPaths }}
  ["{{ . }}"]="{{ . }}"
{{- end }}
)
for PATH_KEY in "${!SECRET_PATHS[@]}"; do
  PARAM_NAME="${SECRET_PATHS[$PATH_KEY]}"
  # aws ssm get-parameter with --with-decryption to support SecureString
  SECRET_VALUE=$(aws ssm get-parameter \
    --name "$PARAM_NAME" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>&1)
  if [ $? -eq 0 ]; then
    # Derive env var name from last path component, uppercased
    ENV_NAME=$(basename "$PARAM_NAME" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
    export "${ENV_NAME}=${SECRET_VALUE}"
    echo "[km-bootstrap] Injected secret: $PARAM_NAME -> $ENV_NAME"
  else
    echo "[km-bootstrap] WARNING: failed to fetch secret $PARAM_NAME" >&2
  fi
done
{{- else }}
echo "[km-bootstrap] No secrets to inject"
{{- end }}

# ============================================================
# 4. GitHub token injection (if GitHub access is configured)
# ============================================================
{{- if .HasGitHub }}
echo "[km-bootstrap] Injecting GitHub App token..."
GITHUB_TOKEN=$(aws ssm get-parameter \
  --name "/km/github/app-token" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text 2>&1)
if [ $? -eq 0 ]; then
  export GITHUB_TOKEN
  echo "[km-bootstrap] GITHUB_TOKEN injected"
else
  echo "[km-bootstrap] WARNING: failed to fetch GitHub App token" >&2
fi
{{- end }}

# ============================================================
# 5. Sidecar binaries: install DNS proxy, HTTP proxy, audit log
# ============================================================
echo "[km-bootstrap] Installing km sidecars..."
mkdir -p /opt/km/bin /etc/km/tracing

# Download sidecar binaries from S3 (km-sandbox-artifacts bucket)
KM_ARTIFACTS_BUCKET="{{ .KMArtifactsBucket }}"
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/dns-proxy" /opt/km/bin/km-dns-proxy
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/http-proxy" /opt/km/bin/km-http-proxy
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/audit-log" /opt/km/bin/km-audit-log
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/tracing/config.yaml" /etc/km/tracing/config.yaml
chmod +x /opt/km/bin/km-*

# Create dedicated sidecar user (exempt from iptables DNAT — prevents redirect loops)
useradd -r -s /usr/sbin/nologin km-sidecar || true

# Write systemd unit files (run all sidecar services as km-sidecar user)
cat > /etc/systemd/system/km-dns-proxy.service << 'UNIT'
[Unit]
Description=Klankrmkr DNS proxy sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=ALLOWED_SUFFIXES={{ .AllowedDNSSuffixes }}
Environment=UPSTREAM_DNS=169.254.169.253
Environment=DNS_PORT=5353
ExecStart=/opt/km/bin/km-dns-proxy
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/km-http-proxy.service << 'UNIT'
[Unit]
Description=Klankrmkr HTTP proxy sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=ALLOWED_HOSTS={{ .AllowedHTTPHosts }}
Environment=PROXY_PORT=3128
ExecStart=/opt/km/bin/km-http-proxy
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/km-audit-log.service << 'UNIT'
[Unit]
Description=Klankrmkr audit log sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=CW_LOG_GROUP=/km/sandboxes/{{ .SandboxID }}/
ExecStart=/opt/km/bin/km-audit-log
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable km-dns-proxy km-http-proxy km-audit-log
systemctl start km-dns-proxy km-http-proxy km-audit-log
echo "[km-bootstrap] Sidecars started"

# ============================================================
# 6. iptables DNAT: redirect DNS and HTTP traffic to sidecars
# ============================================================
echo "[km-bootstrap] Configuring iptables DNAT..."

# IMDS exemption MUST be inserted first (-I inserts at top of chain).
# Without this, IMDSv2 PUT token requests (port 80 to 169.254.169.254)
# are redirected to the HTTP proxy and fail, breaking SSM and credential refresh.
iptables -t nat -I OUTPUT -d 169.254.169.254 -j RETURN

# DNS: redirect UDP/TCP port 53 to local DNS proxy on :5353
# ! --uid-owner km-sidecar exempts the proxy's own upstream queries (prevents redirect loop)
iptables -t nat -A OUTPUT -p udp --dport 53 ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 5353
iptables -t nat -A OUTPUT -p tcp --dport 53 ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 5353

# HTTP/HTTPS: redirect to HTTP proxy on :3128
# km-sidecar user is exempt to prevent the proxy from redirecting its own upstream connections
iptables -t nat -A OUTPUT -p tcp --dport 80  ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 3128
iptables -t nat -A OUTPUT -p tcp --dport 443 ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 3128

echo "[km-bootstrap] iptables DNAT configured"

# ============================================================
# 6.5. Spot interruption handler (background)
# ============================================================
{{- if .UseSpot }}
{{- if .ArtifactPaths }}
# Write artifact upload helper script
cat > /opt/km/bin/km-upload-artifacts << 'UPLOADSCRIPT'
#!/bin/bash
# Upload configured artifact paths to S3
BUCKET="{{ .KMArtifactsBucket }}"
SANDBOX_ID="{{ .SandboxID }}"
MAX_SIZE_MB={{ .ArtifactMaxSizeMB }}
ARTIFACT_PATHS=({{ range .ArtifactPaths }}"{{ . }}" {{ end }})
for APATH in "${ARTIFACT_PATHS[@]}"; do
  find "$APATH" -type f 2>/dev/null | while read FILE; do
    SIZE_MB=$(( $(stat -f%z "$FILE" 2>/dev/null || stat --printf="%s" "$FILE" 2>/dev/null) / 1048576 ))
    if [ "$MAX_SIZE_MB" -gt 0 ] && [ "$SIZE_MB" -gt "$MAX_SIZE_MB" ]; then
      echo "[km-upload] SKIP $FILE (${SIZE_MB}MB > ${MAX_SIZE_MB}MB limit)"
      continue
    fi
    REL_PATH="${FILE#/}"
    aws s3 cp "$FILE" "s3://${BUCKET}/artifacts/${SANDBOX_ID}/${REL_PATH}" 2>&1 || echo "[km-upload] WARN: failed to upload $FILE"
  done
done
UPLOADSCRIPT
chmod +x /opt/km/bin/km-upload-artifacts
{{- end }}
(
  while true; do
    SPOT_ACTION=$(curl -sf \
      -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
      "http://169.254.169.254/latest/meta-data/spot/termination-time" 2>/dev/null || echo "")
    if [ -n "$SPOT_ACTION" ]; then
      echo "[km-spot] Spot interruption detected at $SPOT_ACTION"
      {{- if .ArtifactPaths }}
      /opt/km/bin/km-upload-artifacts || true
      {{- end }}
      echo "[km-spot] Shutdown handler complete"
      break
    fi
    sleep 5
  done
) &
{{- end }}

# ============================================================
# 7. Sandbox ready signal
# ============================================================
echo "[km-bootstrap] SANDBOX_READY sandbox_id={{ .SandboxID }}"
`

// userDataParams holds the template parameters for user-data generation.
type userDataParams struct {
	SandboxID          string
	SecretPaths        []string
	HasGitHub          bool
	AllowedDNSSuffixes string // comma-separated, from profile.Network.Egress.AllowedDNSSuffixes
	AllowedHTTPHosts   string // comma-separated, from profile.Network.Egress.AllowedHosts
	KMArtifactsBucket  string // from config env var KM_ARTIFACTS_BUCKET
	// Filesystem enforcement (section 2.5)
	ReadOnlyPaths []string
	WritablePaths []string
	// Spot interruption handling (section 6.5)
	UseSpot           bool
	ArtifactPaths     []string
	ArtifactMaxSizeMB int
}

// generateUserData produces the EC2 bootstrap user-data.sh content for the given profile.
// It is only called for ec2 substrate sandboxes.
// artifactsBucket is from the KM_ARTIFACTS_BUCKET env var; may be empty string.
// useSpot indicates whether the EC2 instance uses spot pricing (enables spot poll loop).
func generateUserData(p *profile.SandboxProfile, sandboxID string, secretPaths []string, artifactsBucket string, useSpot bool) (string, error) {
	tmpl, err := template.New("userdata").Parse(userDataTemplate)
	if err != nil {
		return "", err
	}

	params := userDataParams{
		SandboxID:          sandboxID,
		SecretPaths:        secretPaths,
		HasGitHub:          p.Spec.SourceAccess.GitHub != nil,
		AllowedDNSSuffixes: strings.Join(p.Spec.Network.Egress.AllowedDNSSuffixes, ","),
		AllowedHTTPHosts:   strings.Join(p.Spec.Network.Egress.AllowedHosts, ","),
		KMArtifactsBucket:  artifactsBucket,
		UseSpot:            useSpot,
	}

	// Populate filesystem policy fields (nil-safe)
	if p.Spec.Policy.FilesystemPolicy != nil {
		params.ReadOnlyPaths = p.Spec.Policy.FilesystemPolicy.ReadOnlyPaths
		params.WritablePaths = p.Spec.Policy.FilesystemPolicy.WritablePaths
	}

	// Populate artifact fields (nil-safe)
	if p.Spec.Artifacts != nil {
		params.ArtifactPaths = p.Spec.Artifacts.Paths
		params.ArtifactMaxSizeMB = p.Spec.Artifacts.MaxSizeMB
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", err
	}
	return buf.String(), nil
}
