package compiler

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// otpEnvName derives the env var name for an OTP secret from its SSM path.
// The last path segment is uppercased, with hyphens replaced by underscores,
// and prefixed with "KM_OTP_". E.g. /sandbox/sb-123/otp/github-token -> KM_OTP_GITHUB_TOKEN
func otpEnvName(path string) string {
	seg := filepath.Base(path)
	return "KM_OTP_" + strings.ToUpper(strings.ReplaceAll(seg, "-", "_"))
}

// userDataTemplate generates the EC2 bootstrap script.
// It performs: SSM agent install, IMDSv2 verification, secret injection,
// optional GitHub token injection, filesystem bind mounts (2.5), sidecar install,
// iptables DNAT, spot interruption handler (6.5), and SANDBOX_READY signal.
const userDataTemplate = `#!/bin/bash
# Klankrmkr sandbox bootstrap — generated by profile compiler
# DO NOT EDIT — this file is overwritten on each provision

set -euo pipefail

# ============================================================
# 1. SSM Agent: install and start
# ============================================================
echo "[km-bootstrap] Installing amazon-ssm-agent..."
yum install -y amazon-ssm-agent 2>&1 | tee -a /var/log/km-bootstrap.log
systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent
echo "[km-bootstrap] SSM agent started"

# ============================================================
# 2. IMDSv2: verify token-based metadata access is working
# ============================================================
echo "[km-bootstrap] Verifying IMDSv2 token..."
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>&1)
if [ -z "$IMDS_TOKEN" ]; then
  echo "[km-bootstrap] ERROR: IMDSv2 token fetch failed — cannot access instance metadata" >&2
  exit 1
fi
echo "[km-bootstrap] IMDSv2 token obtained successfully"

# Retrieve instance region for SSM API calls
REGION=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
  http://169.254.169.254/latest/meta-data/placement/region)
export AWS_DEFAULT_REGION="${REGION}"
echo "[km-bootstrap] Region: $REGION"

# ============================================================
# 2.5. Filesystem policy: read-only bind mounts (before sidecar startup)
# ============================================================
{{- if .ReadOnlyPaths }}
echo "[km-bootstrap] Applying filesystem read-only bind mounts..."
{{- range .ReadOnlyPaths }}
mount --bind "{{ . }}" "{{ . }}"
mount -o remount,bind,ro "{{ . }}"
{{- end }}
echo "[km-bootstrap] Read-only bind mounts applied"
{{- end }}
{{- if .AdditionalVolumeMountPoint }}

# ============================================================
# 2.6. Additional EBS volume: format and mount (Phase 33)
# ============================================================
echo "[km-bootstrap] Waiting for additional EBS volume to attach..."
DEVICE=""
for i in $(seq 1 30); do
  # AL2023: udev creates /dev/xvdf symlink automatically from /dev/sdf attachment
  # Ubuntu/other: fall through to direct NVMe probe
  for dev in /dev/xvdf /dev/sdf /dev/nvme1n1 /dev/nvme2n1; do
    if [ -b "$dev" ]; then
      # Verify it's not the root device
      ROOT_DEV=$(lsblk -no PKNAME $(df / | tail -1 | awk '{print $1}') 2>/dev/null || echo "")
      DEV_BASE=$(basename "$dev")
      if [ "$DEV_BASE" != "$ROOT_DEV" ] && ! df / 2>/dev/null | grep -q "$dev"; then
        DEVICE="$dev"
        break 2
      fi
    fi
  done
  sleep 2
done

if [ -n "$DEVICE" ]; then
  # Format only if no filesystem exists (idempotent)
  if ! blkid "$DEVICE" &>/dev/null; then
    echo "[km-bootstrap] Formatting $DEVICE as ext4..."
    mkfs.ext4 -F "$DEVICE"
  fi
  mkdir -p "{{ .AdditionalVolumeMountPoint }}"
  # Mount and add to fstab for persistence across reboots
  DEVICE_UUID=$(blkid -s UUID -o value "$DEVICE")
  if [ -n "$DEVICE_UUID" ] && ! grep -q "$DEVICE_UUID" /etc/fstab 2>/dev/null; then
    echo "UUID=${DEVICE_UUID} {{ .AdditionalVolumeMountPoint }} ext4 defaults,nofail 0 2" >> /etc/fstab
  fi
  mount -a
  chown sandbox:sandbox "{{ .AdditionalVolumeMountPoint }}" 2>/dev/null || true
  echo "[km-bootstrap] Additional volume mounted at {{ .AdditionalVolumeMountPoint }}"
else
  echo "[km-bootstrap] WARNING: additional EBS volume device not found after 60s"
fi
{{- end }}
{{- if .EFSFilesystemID }}

# ============================================================
# 2.7. EFS shared filesystem: install utils and mount (Phase 43)
# ============================================================
echo "[km-bootstrap] Mounting EFS shared filesystem {{ .EFSFilesystemID }}..."
yum install -y amazon-efs-utils 2>&1 | tee -a /var/log/km-bootstrap.log
mkdir -p "{{ .EFSMountPoint }}"
# Add fstab entry with _netdev,nofail,tls so boot continues if EFS is unavailable
if ! grep -q "{{ .EFSFilesystemID }}" /etc/fstab 2>/dev/null; then
  echo "{{ .EFSFilesystemID }}:/ {{ .EFSMountPoint }} efs _netdev,nofail,tls 0 0" >> /etc/fstab
fi
mount -a -t efs 2>&1 | tee -a /var/log/km-bootstrap.log || true
if mountpoint -q "{{ .EFSMountPoint }}" 2>/dev/null; then
  chown sandbox:sandbox "{{ .EFSMountPoint }}" 2>/dev/null || true
  echo "[km-bootstrap] EFS mounted at {{ .EFSMountPoint }}"
else
  echo "[km-bootstrap] WARNING: EFS mount failed — {{ .EFSFilesystemID }} may be unavailable"
fi
{{- end }}

# ============================================================
# 2.8. Sandbox identity: set hostname and export identity env vars
# ============================================================
SANDBOX_FQDN="{{ .SandboxID }}.{{ .EmailDomain }}"
hostnamectl set-hostname "${SANDBOX_FQDN}" 2>/dev/null || hostname "${SANDBOX_FQDN}"
cat > /etc/profile.d/km-identity.sh << EOF
export KM_SANDBOX_ID="{{ .SandboxID }}"
export KM_SANDBOX_HOSTNAME="${SANDBOX_FQDN}"
export KM_SANDBOX_DOMAIN="{{ .EmailDomain }}"
export KM_SANDBOX_EMAIL="{{ .SandboxEmail }}"
export KM_SANDBOX_FROM_EMAIL="{{ .SandboxEmail }}"
{{- if .OperatorEmail }}
export KM_OPERATOR_EMAIL="{{ .OperatorEmail }}"
{{- end }}
{{- if .Alias }}
export KM_SANDBOX_ALIAS="{{ .Alias }}"
export KM_ALIAS_EMAIL="{{ .AliasEmail }}"
{{- end }}
EOF
chmod 644 /etc/profile.d/km-identity.sh
echo "[km-bootstrap] Hostname set to ${SANDBOX_FQDN}"

# ============================================================
# 2.8. Profile environment variables: write to /etc/profile.d/
# ============================================================
{{- if .ProfileEnv }}
echo "[km-bootstrap] Writing profile environment variables..."
cat > /etc/profile.d/km-profile-env.sh << 'PROFILE_ENV'
{{- range $key, $value := .ProfileEnv }}
export {{ $key }}="{{ $value }}"
{{- end }}
PROFILE_ENV
chmod 644 /etc/profile.d/km-profile-env.sh
echo "[km-bootstrap] Profile env vars written ({{ len .ProfileEnv }} vars)"
{{- end }}

# ============================================================
# 2.9. Claude Code OpenTelemetry environment
# ============================================================
{{- if .ClaudeTelemetryEnabled }}
cat >> /etc/profile.d/km-profile-env.sh << 'CLAUDE_OTEL'
export CLAUDE_CODE_ENABLE_TELEMETRY=1
export OTEL_METRICS_EXPORTER=otlp
export OTEL_LOGS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_PROTOCOL=grpc
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
{{- if .ClaudeTelemetryLogPrompts }}
export OTEL_LOG_USER_PROMPTS=1
{{- end }}
{{- if .ClaudeTelemetryLogToolDetails }}
export OTEL_LOG_TOOL_DETAILS=1
{{- end }}
CLAUDE_OTEL
cat >> /etc/profile.d/km-profile-env.sh << EOF
export OTEL_RESOURCE_ATTRIBUTES="sandbox_id={{ .SandboxID }},profile_name={{ .ProfileName }},substrate={{ .Substrate }}"
EOF
echo "[km-bootstrap] Claude Code OTEL telemetry configured"
{{- end }}

# ============================================================
# 3. Secret injection: fetch allowed SSM paths and export as env vars
# ============================================================
{{- if .SecretPaths }}
echo "[km-bootstrap] Injecting secrets from SSM..."
declare -A SECRET_PATHS=(
{{- range .SecretPaths }}
  ["{{ . }}"]="{{ . }}"
{{- end }}
)
for PATH_KEY in "${!SECRET_PATHS[@]}"; do
  PARAM_NAME="${SECRET_PATHS[$PATH_KEY]}"
  # aws ssm get-parameter with --with-decryption to support SecureString
  SECRET_VALUE=$(aws ssm get-parameter \
    --name "$PARAM_NAME" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>&1)
  if [ $? -eq 0 ]; then
    # Derive env var name from last path component, uppercased
    ENV_NAME=$(basename "$PARAM_NAME" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
    export "${ENV_NAME}=${SECRET_VALUE}"
    echo "[km-bootstrap] Injected secret: $PARAM_NAME -> $ENV_NAME"
  else
    echo "[km-bootstrap] WARNING: failed to fetch secret $PARAM_NAME" >&2
  fi
done
{{- else }}
echo "[km-bootstrap] No secrets to inject"
{{- end }}

# ============================================================
# 3.5 OTP secrets: read once from SSM and delete (one-time bootstrap credentials)
# ============================================================
{{- if .OTPSecrets }}
echo "[km-bootstrap] Injecting OTP secrets (delete-after-read)..."
{{- range .OTPSecrets }}
OTP_VAL=$(aws ssm get-parameter --name "{{ .Path }}" --with-decryption --query Parameter.Value --output text 2>/dev/null)
if [ -n "$OTP_VAL" ]; then
  export {{ .EnvName }}="$OTP_VAL"
  echo "[km-bootstrap] OTP secret injected: {{ .Path }} -> {{ .EnvName }}"
  aws ssm delete-parameter --name "{{ .Path }}" 2>/dev/null || true
  echo "[km-bootstrap] OTP secret deleted from SSM: {{ .Path }}"
fi
{{- end }}
{{- end }}

# ============================================================
# 3.7. Email address: expose sandbox email as env var
# ============================================================
{{- if .SandboxEmail }}
export KM_EMAIL_ADDRESS="{{ .SandboxEmail }}"
echo "[km-bootstrap] KM_EMAIL_ADDRESS={{ .SandboxEmail }}"
{{- if .Alias }}
export KM_SANDBOX_ALIAS="{{ .Alias }}"
export KM_ALIAS_EMAIL="{{ .AliasEmail }}"
echo "[km-bootstrap] KM_ALIAS_EMAIL={{ .AliasEmail }}"
{{- end }}
{{- end }}

{{- if .HasGitHub }}
# ============================================================
# 4. GitHub credential helper: GIT_ASKPASS (if GitHub access is configured)
# EC2 only — token fetched from per-sandbox SSM at git-operation time.
# ECS credential helper delivery is deferred to a future phase.
# ============================================================
echo "[km-bootstrap] Installing GIT_ASKPASS credential helper..."
SANDBOX_ID="{{ .SandboxID }}"
export SANDBOX_ID
mkdir -p /opt/km/bin
cat > /opt/km/bin/km-git-askpass << 'ASKPASS'
#!/bin/bash
TOKEN=$(aws ssm get-parameter \
  --name "/sandbox/${SANDBOX_ID}/github-token" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text 2>/dev/null || echo "")
case "$1" in
  *Username*) echo "x-access-token" ;;
  *Password*) echo "$TOKEN" ;;
  *)          echo "" ;;
esac
ASKPASS
chmod +x /opt/km/bin/km-git-askpass
export GIT_ASKPASS=/opt/km/bin/km-git-askpass
echo "[km-bootstrap] GIT_ASKPASS credential helper installed"
{{- end }}

{{- if .HasAllowedRefs }}
# ============================================================
# 4b. Git ref enforcement: pre-push hook blocks pushes to unlisted refs
# ============================================================
echo "[km-bootstrap] Installing ref enforcement hooks..."
export KM_ALLOWED_REFS="{{ .AllowedRefs }}"
mkdir -p /opt/km/hooks
cat > /opt/km/hooks/pre-push << 'PREPUSH'
#!/bin/bash
ALLOWED_REFS="${KM_ALLOWED_REFS:-}"
if [ -z "$ALLOWED_REFS" ]; then exit 0; fi
while read local_ref local_sha remote_ref remote_sha; do
  branch="${remote_ref#refs/heads/}"
  allowed=false
  IFS=: read -ra PATTERNS <<< "$ALLOWED_REFS"
  for pattern in "${PATTERNS[@]}"; do
    if [[ "$branch" == $pattern ]]; then allowed=true; break; fi
  done
  if [ "$allowed" = false ]; then
    echo "[km] Push to '$branch' denied -- not in allowedRefs: $ALLOWED_REFS" >&2
    exit 1
  fi
done
exit 0
PREPUSH
chmod +x /opt/km/hooks/pre-push
# Install git if not present (needed for hooks and source access)
if ! command -v git &>/dev/null; then
  yum install -y git 2>&1 | tail -1
fi
git config --system core.hooksPath /opt/km/hooks
echo "[km-bootstrap] Ref enforcement hooks installed (allowedRefs: {{ .AllowedRefs }})"
{{- end }}

# ============================================================
# 5. Sidecar binaries: install DNS proxy, HTTP proxy, audit log
# ============================================================
echo "[km-bootstrap] Installing km sidecars..."
mkdir -p /opt/km/bin /etc/km/tracing

# Download sidecar binaries from S3 (km-sandbox-artifacts bucket)
KM_ARTIFACTS_BUCKET="{{ .KMArtifactsBucket }}"
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/dns-proxy" /opt/km/bin/km-dns-proxy
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/http-proxy" /opt/km/bin/km-http-proxy
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/audit-log" /opt/km/bin/km-audit-log
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/tracing/config.yaml" /etc/km/tracing/config.yaml
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/otelcol-contrib" /opt/km/bin/otelcol-contrib
chmod +x /opt/km/bin/km-*
chmod +x /opt/km/bin/otelcol-contrib
{{- if or (eq .Enforcement "ebpf") (eq .Enforcement "both") }}

# Download km binary for eBPF enforcer (km ebpf-attach command)
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/km" /usr/local/bin/km
chmod +x /usr/local/bin/km
echo "[km-bootstrap] km binary installed for eBPF enforcement"
{{- end }}

# Create dedicated sidecar user (exempt from iptables DNAT — prevents redirect loops)
useradd -r -s /usr/sbin/nologin km-sidecar || true

# Create restricted sandbox user for agent workloads (no sudo, no root).
# This is the default user for km shell sessions.
useradd -m -s /bin/bash -d /home/sandbox sandbox 2>/dev/null || true
mkdir -p /workspace
chown sandbox:sandbox /workspace
# Ensure sandbox user gets proxy env vars and audit hook
ln -sf /etc/profile.d/km-audit.sh /etc/profile.d/km-proxy.sh 2>/dev/null || true

# Write systemd unit files (run all sidecar services as km-sidecar user)
cat > /etc/systemd/system/km-dns-proxy.service << 'UNIT'
[Unit]
Description=Klankrmkr DNS proxy sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=ALLOWED_SUFFIXES={{ .AllowedDNSSuffixes }}
Environment=UPSTREAM_DNS=169.254.169.253
Environment=DNS_PORT=5353
ExecStart=/opt/km/bin/km-dns-proxy
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/km-http-proxy.service << 'UNIT'
[Unit]
Description=Klankrmkr HTTP proxy sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=AWS_REGION={{ .AWSRegion }}
Environment=ALLOWED_HOSTS={{ .AllowedHTTPHosts }}
Environment=KM_GITHUB_ALLOWED_REPOS={{ .GitHubAllowedRepos }}
Environment=PROXY_PORT=3128
ExecStart=/opt/km/bin/km-http-proxy
ExecStartPost=/bin/bash -c 'echo $MAINPID > /run/km/http-proxy.pid'
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

# Create named pipe for audit-log sidecar input.
# Shell commands are written here by PROMPT_COMMAND; sidecar reads from it.
mkdir -p /run/km
chown km-sidecar:km-sidecar /run/km
mkfifo /run/km/audit-pipe
chown km-sidecar:km-sidecar /run/km/audit-pipe
chmod 666 /run/km/audit-pipe

cat > /etc/systemd/system/km-audit-log.service << 'UNIT'
[Unit]
Description=Klankrmkr audit log sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=CW_LOG_GROUP=/km/sandboxes/{{ .SandboxID }}/
Environment=AUDIT_LOG_DEST=cloudwatch
{{- if gt .IdleTimeoutMinutes 0 }}
Environment=IDLE_TIMEOUT_MINUTES={{ .IdleTimeoutMinutes }}
{{- end }}
Environment=KM_AUDIT_PIPE=/run/km/audit-pipe
ExecStart=/opt/km/bin/km-audit-log
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/km-tracing.service << 'UNIT'
[Unit]
Description=Klankrmkr OTel Collector sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=OTEL_S3_BUCKET={{ .KMArtifactsBucket }}
Environment=AWS_REGION={{ .AWSRegion }}
ExecStart=/opt/km/bin/otelcol-contrib --config /etc/km/tracing/config.yaml
Restart=always
RestartSec=5
[Install]
WantedBy=multi-user.target
UNIT

# Shell audit hook: writes JSON audit events to the named pipe on every command,
# plus a background heartbeat every 60s so long-running commands (top, vim, etc.)
# don't trigger the idle detector.
# Installed as /etc/profile.d/ so it applies to all login shells (SSM sessions).
cat > /etc/profile.d/km-audit.sh << 'HOOK'
# Guard: only install once per shell (profile.d can be sourced multiple times)
[ -n "$_KM_AUDIT_INSTALLED" ] && return 0
_KM_AUDIT_INSTALLED=1

_km_audit() {
  local cmd
  cmd=$(HISTTIMEFORMAT= history 1 | sed 's/^ *[0-9]* *//')
  [ -z "$cmd" ] && return 0
  # Escape backslashes first, then double-quotes, then newlines for valid JSON
  cmd=$(printf '%s' "$cmd" | sed 's/\\/\\\\/g; s/"/\\"/g; s/	/ /g' | head -c 500)
  printf '{"timestamp":"%s","sandbox_id":"%s","event_type":"command","source":"shell","detail":{"command":"%s","user":"%s"}}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "{{ .SandboxID }}" "$cmd" "$(whoami)" \
    > /run/km/audit-pipe 2>/dev/null
}
PROMPT_COMMAND="_km_audit;${PROMPT_COMMAND}"

# Background heartbeat: keeps the sandbox alive while a session is open,
# even during long-running commands. Killed automatically when the shell exits.
_km_heartbeat() {
  while true; do
    sleep 60
    printf '{"timestamp":"%s","sandbox_id":"%s","event_type":"heartbeat","source":"shell","detail":{}}\n' \
      "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "{{ .SandboxID }}" > /run/km/audit-pipe 2>/dev/null
  done
}
_km_heartbeat &
_KM_HEARTBEAT_PID=$!
trap 'kill $_KM_HEARTBEAT_PID 2>/dev/null' EXIT
HOOK
chmod 644 /etc/profile.d/km-audit.sh

systemctl daemon-reload
{{- if .SandboxEmail }}
# Mail poller: syncs inbound email from S3 to /var/mail/km/ every 30 seconds.
# Agents can watch /var/mail/km/new/ for incoming messages.
mkdir -p /var/mail/km/new /var/mail/km/processed

cat > /opt/km/bin/km-mail-poller << 'MAILPOLL'
#!/bin/bash
# km-mail-poller: sync inbound email from S3 to local filesystem
BUCKET="${KM_ARTIFACTS_BUCKET}"
SANDBOX_ID="${SANDBOX_ID}"
MAIL_DIR="/var/mail/km"
POLL_INTERVAL="${KM_MAIL_POLL_INTERVAL:-60}"

if [ -z "$BUCKET" ]; then
  echo "[km-mail-poller] KM_ARTIFACTS_BUCKET not set, exiting"
  exit 0
fi

MY_ADDR=$(echo "${SANDBOX_ID}@" | tr '[:upper:]' '[:lower:]')
MY_ALIAS_ADDR="${KM_SANDBOX_ALIAS:+$(echo "${KM_SANDBOX_ALIAS}@" | tr '[:upper:]' '[:lower:]')}"
MATCH_PATTERN="$MY_ADDR"
if [ -n "$MY_ALIAS_ADDR" ]; then
  MATCH_PATTERN="$MY_ADDR|$MY_ALIAS_ADDR"
  echo "[km-mail-poller] Polling s3://$BUCKET/mail/ for $MY_ADDR or $MY_ALIAS_ADDR every ${POLL_INTERVAL}s -> $MAIL_DIR/new/"
else
  echo "[km-mail-poller] Polling s3://$BUCKET/mail/ for $MY_ADDR every ${POLL_INTERVAL}s -> $MAIL_DIR/new/"
fi

while true; do
  # List all mail objects, download, and keep only messages addressed to this sandbox
  aws s3 ls "s3://$BUCKET/mail/" 2>/dev/null | awk '{print $NF}' | while read -r key; do
    if [ -z "$key" ]; then continue; fi
    local_file="$MAIL_DIR/new/$key"
    if [ ! -f "$local_file" ] && [ ! -f "$MAIL_DIR/processed/$key" ] && [ ! -f "$MAIL_DIR/skipped/$key" ]; then
      tmp_file=$(mktemp)
      if aws s3 cp "s3://$BUCKET/mail/$key" "$tmp_file" 2>/dev/null; then
        # Check if the To header contains this sandbox's address or alias
        if head -c 8192 "$tmp_file" | tr '[:upper:]' '[:lower:]' | grep -qE "$MATCH_PATTERN"; then
          mv "$tmp_file" "$local_file"
          echo "[km-mail-poller] New mail: $key"
        else
          rm -f "$tmp_file"
          # Mark as skipped so we don't re-download on every poll
          mkdir -p "$MAIL_DIR/skipped"
          touch "$MAIL_DIR/skipped/$key"
        fi
      else
        rm -f "$tmp_file"
      fi
    fi
  done
  sleep "$POLL_INTERVAL"
done
MAILPOLL
chmod +x /opt/km/bin/km-mail-poller

# km-send: send Ed25519-signed email with optional attachments via SES
cat > /opt/km/bin/km-send << 'KMSEND'
#!/bin/bash
# km-send — send a signed email from inside a sandbox
# Usage: km-send --to <addr> --subject <subject> [--body <file>] [--attach file1,file2,...]
#                [--cc addr1,addr2,...] [--use-bcc] [--reply-to <addr>] [message on stdin]
set -euo pipefail

TO=""
SUBJECT=""
BODY_FILE=""
ATTACH_CSV=""
CC_CSV=""
USE_BCC=false
REPLY_TO=""

usage() {
  echo "Usage: km-send --to <addr> --subject <subject> [--body <file>] [--attach file1,file2,...]" >&2
  echo "       [--cc addr1,addr2,...] [--use-bcc] [--reply-to <addr>]" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --to)        TO="$2";        shift 2 ;;
    --subject)   SUBJECT="$2";   shift 2 ;;
    --body)      BODY_FILE="$2"; shift 2 ;;
    --attach)    ATTACH_CSV="$2"; shift 2 ;;
    --cc)        CC_CSV="$2";    shift 2 ;;
    --use-bcc)   USE_BCC=true;   shift ;;
    --reply-to)  REPLY_TO="$2";  shift 2 ;;
    --)          shift; break ;;
    -*)          echo "[km-send] Unknown option: $1" >&2; usage ;;
    *)           break ;;
  esac
done

# Default --to to operator inbox when omitted
if [[ -z "$TO" ]]; then
  TO="operator@${KM_SANDBOX_DOMAIN:-sandboxes.klankermaker.ai}"
  echo "[km-send] No --to specified, defaulting to operator: $TO"
fi

# Validate required args
[[ -z "$SUBJECT" ]] && { echo "[km-send] ERROR: --subject is required" >&2; usage; }

# Validate required env vars
[[ -z "${KM_SANDBOX_ID:-}" ]]    && { echo "[km-send] ERROR: KM_SANDBOX_ID is not set" >&2; exit 1; }
[[ -z "${KM_EMAIL_ADDRESS:-}" ]] && { echo "[km-send] ERROR: KM_EMAIL_ADDRESS is not set" >&2; exit 1; }

# Build display-name From address: "alias" <email> when alias is set
if [[ -n "${KM_SANDBOX_ALIAS:-}" ]]; then
  FROM="\"${KM_SANDBOX_ALIAS}\" <${KM_EMAIL_ADDRESS}>"
else
  FROM="$KM_EMAIL_ADDRESS"
fi
SENDER_ID="$KM_SANDBOX_ID"
TMPDIR_KM=$(mktemp -d /tmp/km-send-XXXXXX)
trap 'rm -rf "$TMPDIR_KM"' EXIT

# Read body from file or stdin
BODY_TMP="$TMPDIR_KM/body.txt"
if [[ -n "$BODY_FILE" ]]; then
  cp "$BODY_FILE" "$BODY_TMP"
else
  cat > "$BODY_TMP"
fi

# Auto-include KM-AUTH when sending to the operator inbox.
# The body is Ed25519 signed, so a third party can't forge a signed body
# containing the phrase without the sender's private key.
OPERATOR_INBOX="operator@${KM_SANDBOX_DOMAIN:-sandboxes.klankermaker.ai}"
if [[ "$TO" == "$OPERATOR_INBOX" ]] || [[ "$TO" == *"$OPERATOR_INBOX"* ]]; then
  KM_SAFE_PHRASE="${KM_SAFE_PHRASE:-}"
  if [[ -z "$KM_SAFE_PHRASE" ]]; then
    # Try fetching from SSM
    KM_SAFE_PHRASE=$(aws ssm get-parameter --name "/km/config/remote-create/safe-phrase" --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || true)
  fi
  if [[ -n "$KM_SAFE_PHRASE" ]]; then
    printf '\n\nKM-AUTH: %s' "$KM_SAFE_PHRASE" >> "$BODY_TMP"
    echo "[km-send] KM-AUTH phrase appended (signed with body)"
  else
    echo "[km-send] WARN: sending to operator but no KM-AUTH phrase available" >&2
  fi
fi

# ------------------------------------------------------------------
# ed25519_privkey_to_pem: convert base64-encoded 64-byte Ed25519 key
# (seed || public) from SSM to a PKCS8 PEM file openssl can use.
# The 32-byte seed is wrapped in the fixed DER structure:
#   SEQUENCE { INTEGER 0, SEQUENCE { OID 1.3.101.112 }, OCTET STRING { OCTET STRING seed } }
# which is the 16-byte prefix 302e020100300506032b657004220420 followed by the 32-byte seed.
# ------------------------------------------------------------------
ed25519_privkey_to_pem() {
  local b64="$1"
  local pem_file="$TMPDIR_KM/signing.pem"

  # Decode the 64-byte key and extract the 32-byte seed (first 32 bytes)
  local raw_hex
  raw_hex=$(printf '%s' "$b64" | base64 -d | od -An -tx1 | tr -d ' \n')
  local seed_hex="${raw_hex:0:64}"   # first 32 bytes = 64 hex chars

  # Build PKCS8 DER: fixed 16-byte header + 32-byte seed
  local pkcs8_hex="302e020100300506032b657004220420${seed_hex}"

  # Convert hex to binary, base64-encode, wrap in PEM
  printf '%s' "$pkcs8_hex" | xxd -r -p | base64 | fold -w 64 | {
    printf '-----BEGIN PRIVATE KEY-----\n'
    cat
    printf '-----END PRIVATE KEY-----\n'
  } > "$pem_file"

  echo "$pem_file"
}

# ------------------------------------------------------------------
# build_mime: assemble a MIME message (single-part or multipart/mixed)
# Uses globals: CC_CSV, REPLY_TO
# Returns path to the temp MIME file.
# ------------------------------------------------------------------
build_mime() {
  local from="$1" to="$2" subject="$3" sender_id="$4" signature="$5"
  local body_file="$6"
  shift 6
  local attach_files=("$@")

  local mime_file="$TMPDIR_KM/message.mime"
  local date_str
  date_str=$(date -R)

  # Helper: emit common headers (From, To, Cc, Reply-To, Subject, Date, X-KM-*)
  emit_headers() {
    printf 'From: %s\r\n' "$from"
    printf 'To: %s\r\n' "$to"
    [[ -n "$CC_CSV" ]] && printf 'Cc: %s\r\n' "$CC_CSV"
    [[ -n "$REPLY_TO" ]] && printf 'Reply-To: %s\r\n' "$REPLY_TO"
    printf 'Subject: %s\r\n' "$subject"
    printf 'Date: %s\r\n' "$date_str"
    printf 'X-KM-Sender-ID: %s\r\n' "$sender_id"
    printf 'X-KM-Signature: %s\r\n' "$signature"
    printf 'MIME-Version: 1.0\r\n'
  }

  if [[ ${#attach_files[@]} -eq 0 ]]; then
    # Single-part text/plain
    {
      emit_headers
      printf 'Content-Type: text/plain; charset=UTF-8\r\n'
      printf 'Content-Transfer-Encoding: 8bit\r\n'
      printf '\r\n'
      cat "$body_file"
    } > "$mime_file"
  else
    # Multipart/mixed
    local boundary="=_km_$(od -An -N12 -tx1 /dev/urandom | tr -d ' \n')"
    {
      emit_headers
      printf 'Content-Type: multipart/mixed; boundary="%s"\r\n' "$boundary"
      printf '\r\n'
      printf '--%s\r\n' "$boundary"
      printf 'Content-Type: text/plain; charset=UTF-8\r\n'
      printf 'Content-Transfer-Encoding: 8bit\r\n'
      printf '\r\n'
      cat "$body_file"
      printf '\r\n'
      for attach in "${attach_files[@]}"; do
        local fname
        fname=$(basename "$attach")
        printf '\r\n--%s\r\n' "$boundary"
        printf 'Content-Type: application/octet-stream; name="%s"\r\n' "$fname"
        printf 'Content-Transfer-Encoding: base64\r\n'
        printf 'Content-Disposition: attachment; filename="%s"\r\n' "$fname"
        printf '\r\n'
        base64 -w 76 "$attach"
        printf '\r\n'
      done
      printf '--%s--\r\n' "$boundary"
    } > "$mime_file"
  fi

  echo "$mime_file"
}

# ------------------------------------------------------------------
# Fetch Ed25519 private key from SSM and build PEM
# ------------------------------------------------------------------
PRIVKEY_B64=$(aws ssm get-parameter \
  --name "/sandbox/$KM_SANDBOX_ID/signing-key" \
  --with-decryption \
  --query 'Parameter.Value' \
  --output text)

PEM_FILE=$(ed25519_privkey_to_pem "$PRIVKEY_B64")

# ------------------------------------------------------------------
# Sign the message body
# ------------------------------------------------------------------
SIGNATURE=$(openssl pkeyutl -sign -inkey "$PEM_FILE" -rawin < "$BODY_TMP" | base64 -w0)

# ------------------------------------------------------------------
# Build MIME message
# ------------------------------------------------------------------
declare -a ATTACH_FILES=()
if [[ -n "$ATTACH_CSV" ]]; then
  IFS=',' read -ra ATTACH_FILES <<< "$ATTACH_CSV"
fi

MIME_FILE=$(build_mime "$FROM" "$TO" "$SUBJECT" "$SENDER_ID" "$SIGNATURE" "$BODY_TMP" "${ATTACH_FILES[@]+"${ATTACH_FILES[@]}"}")

# ------------------------------------------------------------------
# Send via SES raw email
# ------------------------------------------------------------------
MIME_B64=$(base64 -w0 < "$MIME_FILE")

# Build SES destination: To + optional CC + optional BCC (operator email)
SES_DEST="ToAddresses=$TO"
[[ -n "$CC_CSV" ]] && SES_DEST="${SES_DEST},CcAddresses=$CC_CSV"
if $USE_BCC; then
  BCC_ADDR="${KM_OPERATOR_EMAIL:-}"
  if [[ -n "$BCC_ADDR" ]]; then
    SES_DEST="${SES_DEST},BccAddresses=$BCC_ADDR"
  else
    echo "[km-send] WARN: --use-bcc but KM_OPERATOR_EMAIL not set, skipping BCC" >&2
  fi
fi

aws sesv2 send-email \
  --from-email-address "$FROM" \
  --destination "$SES_DEST" \
  --content "Raw={Data=$MIME_B64}"

echo "[km-send] Sent signed email to $TO (sig: ${SIGNATURE:0:12}...)"
KMSEND
chmod +x /opt/km/bin/km-send
echo "[km-bootstrap] km-send installed at /opt/km/bin/km-send"

cat > /etc/systemd/system/km-mail-poller.service << 'UNIT'
[Unit]
Description=Klankrmkr mail poller — syncs inbound email from S3
After=network.target
[Service]
User=root
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=KM_ARTIFACTS_BUCKET={{ .KMArtifactsBucket }}
ExecStart=/opt/km/bin/km-mail-poller
Restart=always
RestartSec=5
[Install]
WantedBy=multi-user.target
UNIT

# km-recv: read and display signed emails from /var/mail/km/new/
# Usage: km-recv [--json] [--watch] [--mark-read]
cat > /opt/km/bin/km-recv << 'KMRECV'
#!/bin/bash
# km-recv: read, verify, and display emails from the local inbox.
# Pure bash + AWS CLI + openssl — no km binary dependency.
#
# Usage: km-recv [--json] [--watch] [--mark-read]
#   --json       machine-readable JSON output (one object per message, newline-delimited)
#   --watch      poll loop (check every 5 seconds for new messages)
#   --mark-read  move messages to /var/mail/km/processed/ after reading (default: leave in new/)

set -euo pipefail

# ----------------------------------------------------------------
# Argument parsing
# ----------------------------------------------------------------
JSON_OUTPUT=false
WATCH_MODE=false
MARK_READ=false

for arg in "$@"; do
  case "$arg" in
    --json)      JSON_OUTPUT=true ;;
    --watch)     WATCH_MODE=true ;;
    --mark-read) MARK_READ=true ;;
    --help|-h)
      echo "Usage: km-recv [--json] [--watch] [--mark-read]"
      echo "  --json       machine-readable JSON (newline-delimited, one object per message)"
      echo "  --watch      poll every 5 seconds for new messages"
      echo "  --mark-read  move messages to processed/ after reading"
      exit 0
      ;;
    *)
      echo "[km-recv] Unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

MAIL_DIR="/var/mail/km"
SANDBOX_ID="${KM_SANDBOX_ID:-}"
IDENTITIES_TABLE="${KM_IDENTITIES_TABLE:-km-identities}"

# ----------------------------------------------------------------
# ed25519_pubkey_to_pem: convert a base64-encoded 32-byte Ed25519
# public key to a PEM-encoded SubjectPublicKeyInfo temporary file.
#
# SubjectPublicKeyInfo DER layout for Ed25519:
#   302a300506032b6570032100 (12-byte fixed OID prefix)
#   + 32 bytes of raw public key
#
# Returns the path to the temp PEM file via stdout.
# Caller is responsible for deleting the temp file.
# ----------------------------------------------------------------
ed25519_pubkey_to_pem() {
  local b64_key="$1"
  local tmp_der
  local tmp_pem

  tmp_der=$(mktemp /tmp/km-recv-XXXXXX.der)
  tmp_pem=$(mktemp /tmp/km-recv-XXXXXX.pem)

  # Build DER: fixed SubjectPublicKeyInfo prefix for Ed25519 + 32-byte key
  local der_hex="302a300506032b6570032100"
  local key_hex
  key_hex=$(printf '%s' "$b64_key" | base64 -d | xxd -p | tr -d '\n')

  # Write full DER to binary file
  printf '%s%s' "$der_hex$key_hex" | xxd -r -p > "$tmp_der"

  # Wrap in PEM
  {
    echo "-----BEGIN PUBLIC KEY-----"
    base64 "$tmp_der" | fold -w 64
    echo "-----END PUBLIC KEY-----"
  } > "$tmp_pem"

  rm -f "$tmp_der"
  echo "$tmp_pem"
}

# ----------------------------------------------------------------
# parse_headers: extract all commonly used headers from raw email.
# Sets global variables: HDR_FROM HDR_TO HDR_SUBJECT HDR_SENDER_ID
# HDR_SIGNATURE HDR_ENCRYPTED HDR_CONTENT_TYPE
# ----------------------------------------------------------------
parse_headers() {
  local raw="$1"

  HDR_FROM=$(echo "$raw"         | grep -i "^From:"              | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r')
  HDR_TO=$(echo "$raw"           | grep -i "^To:"                | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r')
  HDR_SUBJECT=$(echo "$raw"      | grep -i "^Subject:"           | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r')
  HDR_SENDER_ID=$(echo "$raw"    | grep -i "^X-KM-Sender-ID:"    | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r')
  HDR_SIGNATURE=$(echo "$raw"    | grep -i "^X-KM-Signature:"    | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r')
  HDR_ENCRYPTED=$(echo "$raw"    | grep -i "^X-KM-Encrypted:"    | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r' | tr '[:upper:]' '[:lower:]')
  HDR_CONTENT_TYPE=$(echo "$raw" | grep -i "^Content-Type:"      | head -1 | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r')
}

# ----------------------------------------------------------------
# extract_body: return the plain-text body of a MIME message.
# For single-part messages: everything after the first blank line.
# For multipart/: returns the first text/plain part's content.
# ----------------------------------------------------------------
extract_body() {
  local raw="$1"

  # Check for multipart boundary
  local boundary
  boundary=$(echo "$HDR_CONTENT_TYPE" | grep -oi 'boundary="[^"]*"' | sed 's/boundary="//;s/"$//')
  if [ -z "$boundary" ]; then
    boundary=$(echo "$HDR_CONTENT_TYPE" | grep -oi "boundary=[^;[:space:]]*" | sed 's/boundary=//')
  fi

  if [ -n "$boundary" ]; then
    # Multipart: find first text/plain part
    local in_text_plain=false
    local past_part_headers=false
    local body_lines=""

    while IFS= read -r line; do
      line_clean=$(echo "$line" | tr -d '\r')
      if [[ "$line_clean" == "--${boundary}"* ]]; then
        if $in_text_plain && [ -n "$body_lines" ]; then
          break
        fi
        in_text_plain=false
        past_part_headers=false
        body_lines=""
        continue
      fi
      if ! $in_text_plain; then
        if echo "$line_clean" | grep -qi "^Content-Type:.*text/plain"; then
          in_text_plain=true
          past_part_headers=false
          continue
        fi
        continue
      fi
      if ! $past_part_headers; then
        if [ -z "$line_clean" ]; then
          past_part_headers=true
        fi
        continue
      fi
      body_lines="${body_lines}${line_clean}
"
    done <<< "$raw"

    if [ -n "$body_lines" ]; then
      echo "$body_lines"
      return
    fi
  fi

  # Single-part or fallback: skip headers (up to first blank line), return rest
  echo "$raw" | awk 'found{print} /^[[:space:]]*$/{found=1}' | head -100
}

# ----------------------------------------------------------------
# list_attachments: print filenames of MIME attachments (one per line).
# ----------------------------------------------------------------
list_attachments() {
  local raw="$1"
  echo "$raw" | grep -i "^Content-Disposition:.*attachment" | \
    grep -oi 'filename="[^"]*"' | sed 's/filename="//;s/"$//'
}

# ----------------------------------------------------------------
# save_attachment: decode a base64 MIME attachment part to a file.
# Usage: save_attachment "$raw_email" "filename.txt" "/output/dir/"
# ----------------------------------------------------------------
save_attachment() {
  local raw="$1"
  local filename="$2"
  local outdir="${3:-.}"

  local in_target=false
  local in_body=false
  local body_b64=""

  while IFS= read -r line; do
    line_clean=$(echo "$line" | tr -d '\r')

    if echo "$line_clean" | grep -qi "filename=\"${filename}\""; then
      in_target=true
      in_body=false
      continue
    fi

    if $in_target; then
      if [ -z "$line_clean" ] && ! $in_body; then
        in_body=true
        continue
      fi
      if $in_body; then
        if [[ "$line_clean" == "--"* ]]; then
          break
        fi
        body_b64="${body_b64}${line_clean}"
      fi
    fi
  done <<< "$raw"

  if [ -z "$body_b64" ]; then
    echo "[km-recv] Attachment '$filename' not found or empty" >&2
    return 1
  fi

  mkdir -p "$outdir"
  printf '%s' "$body_b64" | base64 -d > "${outdir}/${filename}"
  echo "[km-recv] Saved attachment: ${outdir}/${filename}"
}

# ----------------------------------------------------------------
# verify_signature: best-effort Ed25519 signature verification.
# Looks up sender public key from DynamoDB km-identities table.
# Sets global: SIG_STATUS ("verified"|"failed"|"no-key"|"unsigned"|"error")
# ----------------------------------------------------------------
verify_signature() {
  local sender_id="$1"
  local signature_b64="$2"
  local body="$3"

  if [ -z "$sender_id" ] || [ -z "$signature_b64" ]; then
    SIG_STATUS="unsigned"
    return
  fi

  # Look up public key from DynamoDB
  local pubkey_b64
  pubkey_b64=$(aws dynamodb get-item \
    --table-name "$IDENTITIES_TABLE" \
    --key "{\"sandbox_id\":{\"S\":\"${sender_id}\"}}" \
    --query 'Item.public_key.S' \
    --output text 2>/dev/null || echo "")

  if [ -z "$pubkey_b64" ] || [ "$pubkey_b64" = "None" ]; then
    SIG_STATUS="no-key"
    return
  fi

  # Convert base64 pubkey (32 bytes) to Ed25519 PEM
  local pem_file
  pem_file=$(ed25519_pubkey_to_pem "$pubkey_b64" 2>/dev/null || echo "")

  if [ -z "$pem_file" ] || [ ! -f "$pem_file" ]; then
    SIG_STATUS="error"
    return
  fi

  # Write signature and body to temp files for openssl
  local sig_file body_file
  sig_file=$(mktemp /tmp/km-recv-XXXXXX.sig)
  body_file=$(mktemp /tmp/km-recv-XXXXXX.body)
  printf '%s' "$signature_b64" | base64 -d > "$sig_file" 2>/dev/null || true
  printf '%s' "$body" > "$body_file"

  # Verify with openssl pkeyutl (Ed25519 requires -rawin)
  if openssl pkeyutl -verify \
      -pubin -inkey "$pem_file" \
      -sigfile "$sig_file" \
      -in "$body_file" \
      -rawin \
      2>/dev/null; then
    SIG_STATUS="verified"
  else
    SIG_STATUS="failed"
  fi

  rm -f "$pem_file" "$sig_file" "$body_file"
}

# ----------------------------------------------------------------
# json_escape: escape a string for safe embedding in JSON.
# ----------------------------------------------------------------
json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g;s/"/\\"/g;s/\t/\\t/g' | tr -d '\000-\037'
}

# ----------------------------------------------------------------
# process_messages: scan /var/mail/km/new/ and process each message
# ----------------------------------------------------------------
process_messages() {
  local index=0
  local found_any=false

  shopt -s nullglob
  for msg_file in "$MAIL_DIR/new/"*; do
    [ -f "$msg_file" ] || continue

    found_any=true
    index=$((index + 1))

    # Read raw email content (cap at 1MB to avoid runaway)
    local raw
    raw=$(head -c 1048576 "$msg_file")

    # Parse headers into global HDR_* variables
    parse_headers "$raw"

    # Extract body
    local body body_preview
    body=$(extract_body "$raw")
    body_preview=$(echo "$body" | head -1 | cut -c1-80)

    # List attachments
    local attachments attachment_list
    attachments=$(list_attachments "$raw")
    attachment_list=$(echo "$attachments" | tr '\n' ',' | sed 's/,$//')

    # Determine encrypted status
    local is_encrypted=false
    if [ "$HDR_ENCRYPTED" = "yes" ] || [ "$HDR_ENCRYPTED" = "true" ] || [ "$HDR_ENCRYPTED" = "1" ]; then
      is_encrypted=true
    fi

    # Signature verification (best-effort — network may not be available during bootstrap)
    SIG_STATUS="unsigned"
    verify_signature "$HDR_SENDER_ID" "$HDR_SIGNATURE" "$body" || true

    if $JSON_OUTPUT; then
      local json_from json_to json_subject json_sender_id json_body json_sig
      json_from=$(json_escape "$HDR_FROM")
      json_to=$(json_escape "$HDR_TO")
      json_subject=$(json_escape "$HDR_SUBJECT")
      json_sender_id=$(json_escape "$HDR_SENDER_ID")
      json_body=$(json_escape "$body")
      json_sig=$(json_escape "$SIG_STATUS")
      local json_enc="false"
      $is_encrypted && json_enc="true"
      local attach_json="[]"
      if [ -n "$attachment_list" ]; then
        attach_json='["'"$(echo "$attachment_list" | sed 's/,/","/g')"'"]'
      fi
      printf '{"index":%d,"from":"%s","sender_id":"%s","to":"%s","subject":"%s","signature":"%s","encrypted":%s,"body":"%s","attachments":%s}\n' \
        "$index" "$json_from" "$json_sender_id" "$json_to" "$json_subject" \
        "$json_sig" "$json_enc" "$json_body" "$attach_json"
    else
      # Human-readable output
      local sig_display enc_display from_display
      case "$SIG_STATUS" in
        verified) sig_display="✓ verified" ;;
        failed)   sig_display="✗ failed"   ;;
        no-key)   sig_display="? no-key"   ;;
        unsigned) sig_display="— unsigned" ;;
        *)        sig_display="? $SIG_STATUS" ;;
      esac
      enc_display="no"
      $is_encrypted && enc_display="yes"
      from_display="${HDR_SENDER_ID:-${HDR_FROM}}"
      printf '[%d] From: %-20s  Subject: %-20s  Sig: %-12s  Enc: %s\n' \
        "$index" "$from_display" "${HDR_SUBJECT:-<no subject>}" \
        "$sig_display" "$enc_display"
      if $is_encrypted; then
        printf '    Body: [encrypted - cannot decrypt in bash]\n\n'
      else
        printf '    Body: %s\n\n' "$body_preview"
      fi
    fi

    # Move to processed (only when --mark-read)
    if $MARK_READ; then
      mv "$msg_file" "$MAIL_DIR/processed/$(basename "$msg_file")"
    fi
  done

  if ! $found_any && ! $JSON_OUTPUT; then
    echo "[km-recv] No new messages in $MAIL_DIR/new/"
  fi
}

# ----------------------------------------------------------------
# Main
# ----------------------------------------------------------------
if $WATCH_MODE; then
  echo "[km-recv] Watching $MAIL_DIR/new/ — press Ctrl-C to stop"
  while true; do
    process_messages
    sleep 5
  done
else
  process_messages
fi
KMRECV
chmod +x /opt/km/bin/km-recv
echo "[km-bootstrap] km-recv installed at /opt/km/bin/km-recv"
{{- end }}

{{- if or (eq .Enforcement "ebpf") (eq .Enforcement "both") }}
# In eBPF/gatekeeper mode, skip km-dns-proxy (enforcer runs its own DNS resolver)
systemctl enable km-http-proxy km-audit-log km-tracing{{ if .SandboxEmail }} km-mail-poller{{ end }}
systemctl start km-http-proxy km-audit-log km-tracing{{ if .SandboxEmail }} km-mail-poller{{ end }}
echo "[km-bootstrap] Sidecars started (DNS via eBPF enforcer, not km-dns-proxy)"
{{- else }}
systemctl enable km-dns-proxy km-http-proxy km-audit-log km-tracing{{ if .SandboxEmail }} km-mail-poller{{ end }}
systemctl start km-dns-proxy km-http-proxy km-audit-log km-tracing{{ if .SandboxEmail }} km-mail-poller{{ end }}
echo "[km-bootstrap] Sidecars started"
{{- end }}
echo "[km-bootstrap] Shell audit hook installed at /etc/profile.d/km-audit.sh"
{{- if .SandboxEmail }}
echo "[km-bootstrap] Mail poller started — inbox at /var/mail/km/new/"
echo "[km-bootstrap] km-send ready — send signed email with: km-send --to <addr> --subject <subject>"
{{- end }}

{{- if eq .Enforcement "proxy" }}
# ============================================================
# 6. iptables DNAT: redirect DNS and HTTP traffic to sidecars
# ============================================================
echo "[km-bootstrap] Configuring iptables DNAT..."

# Amazon Linux 2023 uses nftables — install iptables compatibility layer
if ! command -v iptables &>/dev/null; then
  yum install -y iptables-nft 2>/dev/null || yum install -y iptables 2>/dev/null || true
fi

# IMDS exemption MUST be inserted first (-I inserts at top of chain).
# Without this, IMDSv2 PUT token requests (port 80 to 169.254.169.254)
# are redirected to the HTTP proxy and fail, breaking SSM and credential refresh.
iptables -t nat -I OUTPUT -d 169.254.169.254 -j RETURN

# Exempt root user from DNAT — SSM agent, systemd, and AWS CLI run as root.
# Without this, SSM agent connections to ssm.amazonaws.com:443 get redirected
# to the HTTP proxy and blocked (not in the allowlist), breaking SSM sessions.
iptables -t nat -A OUTPUT -m owner --uid-owner 0 -j RETURN

# DNS: redirect UDP/TCP port 53 to local DNS proxy on :5353
# ! --uid-owner km-sidecar exempts the proxy's own upstream queries (prevents redirect loop)
iptables -t nat -A OUTPUT -p udp --dport 53 -m owner ! --uid-owner km-sidecar -j REDIRECT --to-ports 5353
iptables -t nat -A OUTPUT -p tcp --dport 53 -m owner ! --uid-owner km-sidecar -j REDIRECT --to-ports 5353

# HTTP/HTTPS: redirect to HTTP proxy on :3128
# km-sidecar user is exempt to prevent the proxy from redirecting its own upstream connections
iptables -t nat -A OUTPUT -p tcp --dport 80  -m owner ! --uid-owner km-sidecar -j REDIRECT --to-ports 3128
iptables -t nat -A OUTPUT -p tcp --dport 443 -m owner ! --uid-owner km-sidecar -j REDIRECT --to-ports 3128

echo "[km-bootstrap] iptables DNAT configured"

# Set proxy env vars for applications that respect them (curl, wget, pip, npm, etc.)
# This covers HTTPS traffic which iptables DNAT can't transparently proxy without MITM.
cat >> /etc/profile.d/km-audit.sh << 'PROXYENV'
export http_proxy=http://127.0.0.1:3128
export https_proxy=http://127.0.0.1:3128
export HTTP_PROXY=http://127.0.0.1:3128
export HTTPS_PROXY=http://127.0.0.1:3128
export no_proxy=169.254.169.254,localhost,127.0.0.1
export NO_PROXY=169.254.169.254,localhost,127.0.0.1
PROXYENV
echo "[km-bootstrap] Proxy env vars configured for shell sessions"
{{- end }}

{{- if eq .Enforcement "both" }}
# Set proxy env vars as belt-and-suspenders (gatekeeper mode: connect4 is primary, proxy is L7 fallback).
# Apps that respect HTTP_PROXY will route traffic through the proxy for Bedrock/GitHub inspection.
cat >> /etc/profile.d/km-audit.sh << 'PROXYENV'
export http_proxy=http://127.0.0.1:3128
export https_proxy=http://127.0.0.1:3128
export HTTP_PROXY=http://127.0.0.1:3128
export HTTPS_PROXY=http://127.0.0.1:3128
export no_proxy=169.254.169.254,localhost,127.0.0.1
export NO_PROXY=169.254.169.254,localhost,127.0.0.1
PROXYENV
echo "[km-bootstrap] Proxy env vars configured (gatekeeper mode belt-and-suspenders)"
{{- end }}

{{- if or (eq .Enforcement "ebpf") (eq .Enforcement "both") }}
# ============================================================
# 6b. eBPF cgroup enforcement: kernel-level DNS/IP allowlisting
# ============================================================
echo "[km-bootstrap] Configuring eBPF network enforcement..."

# Create sandbox cgroup for eBPF attachment
mkdir -p /sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope

# Allow sandbox user to place processes in this cgroup
# (needed for SSM sessions and su - sandbox to join the cgroup)
chown root:sandbox /sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope/cgroup.procs
chmod 664 /sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope/cgroup.procs

echo "[km-bootstrap] Sandbox cgroup created at /sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope"

# Create systemd service for eBPF enforcer (loads BPF + runs DNS resolver)
cat > /etc/systemd/system/km-ebpf-enforcer.service << 'UNIT'
[Unit]
Description=Klankrmkr eBPF network enforcer
After=network.target
[Service]
Type=simple
{{- if eq .Enforcement "both" }}
ExecStartPre=/bin/bash -c 'echo KM_HTTP_PROXY_PID=$(cat /run/km/http-proxy.pid 2>/dev/null || echo 0) > /run/km/enforcer.env'
EnvironmentFile=-/run/km/enforcer.env
{{- end }}
ExecStart=/usr/local/bin/km ebpf-attach \
  --sandbox-id {{ .SandboxID }} \
{{- if or (eq .Enforcement "ebpf") (eq .Enforcement "both") }}
  --dns-port 53 \
{{- else }}
  --dns-port 0 \
{{- end }}
  --http-proxy-port 3128 \
{{- if or (eq .Enforcement "ebpf") (eq .Enforcement "both") }}
  --firewall-mode block \
{{- else }}
  --firewall-mode log \
{{- end }}
  --allowed-dns "{{ .AllowedDNSSuffixes }}" \
  --allowed-hosts "{{ .AllowedHTTPHosts }}" \
  --proxy-hosts "{{ .L7ProxyHosts }}" \
{{- if eq .Enforcement "both" }}
  --proxy-pid ${KM_HTTP_PROXY_PID} \
{{- end }}
{{- if .TLSEnabled }}
  --tls \
  --allowed-repos "{{ .TLSAllowedRepos }}" \
{{- end }}
  --cgroup /sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable --now km-ebpf-enforcer

# Wait for BPF programs to load and DNS resolver to start
sleep 3
if systemctl is-active --quiet km-ebpf-enforcer; then
  echo "[km-bootstrap] eBPF enforcer running (systemd)"
{{- if eq .Enforcement "both" }}
  # Restart http-proxy in transparent mode. The proxy needs to read BPF maps
  # (pinned by the enforcer) to look up original destinations for DNAT'd connections.
  # Set KM_TRANSPARENT_PROXY=true and override User=root (bpffs requires root).
  mkdir -p /etc/systemd/system/km-http-proxy.service.d
  cat > /etc/systemd/system/km-http-proxy.service.d/transparent.conf << 'DROPIN'
[Service]
Environment=KM_TRANSPARENT_PROXY=true
User=root
DROPIN
  systemctl daemon-reload
  systemctl restart km-http-proxy
  echo "[km-bootstrap] km-http-proxy restarted in transparent proxy mode"
{{- end }}
else
  echo "[km-bootstrap] WARNING: eBPF enforcer failed to start"
  journalctl -u km-ebpf-enforcer --no-pager -n 10
fi

# Create wrapper shell that moves process into sandbox cgroup before exec'ing bash.
# This ensures ALL sandbox user sessions (SSM, su, login) are enforced by eBPF.
cat > /usr/local/bin/km-sandbox-shell << 'SHELLEOF'
#!/bin/bash
# km-sandbox-shell: moves into sandbox cgroup then execs bash
CGROUP_PROCS="/sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope/cgroup.procs"
if [ -w "$CGROUP_PROCS" ]; then
  echo $$ > "$CGROUP_PROCS" 2>/dev/null
fi
exec /bin/bash --login "$@"
SHELLEOF
chmod +x /usr/local/bin/km-sandbox-shell

# Set sandbox user's login shell to the wrapper
usermod -s /usr/local/bin/km-sandbox-shell sandbox

# Also keep profile.d as belt-and-suspenders for interactive sessions
cat > /etc/profile.d/km-cgroup.sh << 'CGROUPEOF'
# Move current process into sandbox cgroup for eBPF enforcement
if [ "$(whoami)" = "sandbox" ]; then
  echo $$ > /sys/fs/cgroup/km.slice/km-{{ .SandboxID }}.scope/cgroup.procs 2>/dev/null || true
fi
CGROUPEOF

{{- if or (eq .Enforcement "ebpf") (eq .Enforcement "both") }}
# Override resolv.conf to route ALL DNS through the enforcer's resolver.
# The enforcer runs its own DNS resolver on :53 (both eBPF and gatekeeper modes).
cp /etc/resolv.conf /etc/resolv.conf.bak
echo "nameserver 127.0.0.1" > /etc/resolv.conf
echo "[km-bootstrap] DNS routed through eBPF enforcer resolver on :53"
{{- else }}
echo "[km-bootstrap] DNS handled by km-dns-proxy sidecar + iptables DNAT (proxy mode)"
{{- end }}

echo "[km-bootstrap] eBPF enforcement configured (sandbox shell → cgroup)"
{{- end }}

{{- if eq .Enforcement "ebpf" }}
# With pure eBPF mode, no iptables DNAT and no HTTP_PROXY env vars needed.
# BPF connect4 handles all traffic redirection at the syscall level.
# Proxy env vars are NOT set — apps connect directly, BPF enforces.
echo "[km-bootstrap] Pure eBPF mode — no iptables, no proxy env vars"
{{- end }}

# ============================================================
# 6.5. Spot interruption handler (background)
# ============================================================
{{- if .UseSpot }}
{{- if .ArtifactPaths }}
# Write artifact upload helper script
cat > /opt/km/bin/km-upload-artifacts << 'UPLOADSCRIPT'
#!/bin/bash
# Upload configured artifact paths to S3
BUCKET="{{ .KMArtifactsBucket }}"
SANDBOX_ID="{{ .SandboxID }}"
MAX_SIZE_MB={{ .ArtifactMaxSizeMB }}
ARTIFACT_PATHS=({{ range .ArtifactPaths }}"{{ . }}" {{ end }})
for APATH in "${ARTIFACT_PATHS[@]}"; do
  find "$APATH" -type f 2>/dev/null | while read FILE; do
    SIZE_MB=$(( $(stat -f%z "$FILE" 2>/dev/null || stat --printf="%s" "$FILE" 2>/dev/null) / 1048576 ))
    if [ "$MAX_SIZE_MB" -gt 0 ] && [ "$SIZE_MB" -gt "$MAX_SIZE_MB" ]; then
      echo "[km-upload] SKIP $FILE (${SIZE_MB}MB > ${MAX_SIZE_MB}MB limit)"
      continue
    fi
    REL_PATH="${FILE#/}"
    aws s3 cp "$FILE" "s3://${BUCKET}/artifacts/${SANDBOX_ID}/${REL_PATH}" 2>&1 || echo "[km-upload] WARN: failed to upload $FILE"
  done
done
UPLOADSCRIPT
chmod +x /opt/km/bin/km-upload-artifacts
{{- end }}
(
  while true; do
    SPOT_ACTION=$(curl -sf \
      -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
      "http://169.254.169.254/latest/meta-data/spot/termination-time" 2>/dev/null || echo "")
    if [ -n "$SPOT_ACTION" ]; then
      echo "[km-spot] Spot interruption detected at $SPOT_ACTION"
      {{- if .ArtifactPaths }}
      /opt/km/bin/km-upload-artifacts || true
      {{- end }}
      {{- if .OperatorEmail }}
      aws sesv2 send-email --from-email-address "{{ .NotificationsEmail }}" \
        --destination "ToAddresses={{ .OperatorEmail }}" \
        --content "Simple={Subject={Data='km sandbox spot-interruption: {{ .SandboxID }}'},Body={Text={Data='Sandbox {{ .SandboxID }} received spot interruption notice. Artifacts uploaded (best-effort).'}}}" \
        --region "${AWS_DEFAULT_REGION}" 2>&1 || echo "[km-spot] WARN: failed to send spot notification"
      {{- end }}
      echo "[km-spot] Shutdown handler complete"
      break
    fi
    sleep 5
  done
) &
{{- end }}

# ============================================================
# 7. Budget enforcement setup (if enabled)
# ============================================================
{{- if .BudgetEnabled }}
echo "[km-bootstrap] Setting up budget enforcement environment..."

# Install goproxy CA cert for MITM proxy so budget-tracked traffic
# (HTTP/HTTPS via km-http-proxy) can be inspected for AI spend tracking.
# The CA cert (public) is stored in S3 at sidecars/km-proxy-ca.crt.
# The CA key (private) is stored in S3 at sidecars/km-proxy-ca.key.
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/km-proxy-ca.crt" \
  /usr/local/share/ca-certificates/km-proxy-ca.crt 2>&1 || \
  echo "[km-bootstrap] WARNING: could not fetch proxy CA cert; AI spend tracking may be incomplete"
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/km-proxy-ca.key" \
  /etc/km/proxy-ca.key 2>&1 || \
  echo "[km-bootstrap] WARNING: could not fetch proxy CA key; MITM will use default CA"
chmod 600 /etc/km/proxy-ca.key 2>/dev/null

if [ -f /usr/local/share/ca-certificates/km-proxy-ca.crt ]; then
  # Amazon Linux 2023 uses update-ca-trust; Debian/Ubuntu uses update-ca-certificates
  if command -v update-ca-trust &>/dev/null; then
    cp /usr/local/share/ca-certificates/km-proxy-ca.crt /etc/pki/ca-trust/source/anchors/
    update-ca-trust
  elif command -v update-ca-certificates &>/dev/null; then
    update-ca-certificates
  fi
  echo "[km-bootstrap] Proxy CA cert installed in system trust store"

  # Detect the merged CA bundle path (includes the km proxy CA after update-ca-trust).
  # Many tools (Python certifi, Node.js, Rust) bundle their own CA stores and ignore
  # the system trust store. These env vars override the bundled stores so MITM works.
  KM_CA_BUNDLE=""
  if [ -f /etc/pki/tls/certs/ca-bundle.crt ]; then
    KM_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt        # RHEL / Amazon Linux
  elif [ -f /etc/ssl/certs/ca-certificates.crt ]; then
    KM_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt       # Debian / Ubuntu
  fi

  if [ -n "$KM_CA_BUNDLE" ]; then
    cat >> /etc/profile.d/km-audit.sh << CAENV
export SSL_CERT_FILE=${KM_CA_BUNDLE}
export REQUESTS_CA_BUNDLE=${KM_CA_BUNDLE}
export CURL_CA_BUNDLE=${KM_CA_BUNDLE}
export NODE_EXTRA_CA_CERTS=${KM_CA_BUNDLE}
export AWS_CA_BUNDLE=${KM_CA_BUNDLE}
CAENV
    echo "[km-bootstrap] CA trust env vars set for Python/Node/Rust/curl/AWS SDK (bundle: ${KM_CA_BUNDLE})"
  fi
fi

# Build base64 PEM (cert+key) for the proxy's KM_PROXY_CA_CERT env var.
# The proxy uses this to sign MITM leaf certificates that the sandbox trusts.
KM_PROXY_CA_PEM=""
if [ -f /usr/local/share/ca-certificates/km-proxy-ca.crt ] && [ -f /etc/km/proxy-ca.key ]; then
  KM_PROXY_CA_PEM=$(cat /usr/local/share/ca-certificates/km-proxy-ca.crt /etc/km/proxy-ca.key | base64 -w0)
  echo "[km-bootstrap] Proxy CA cert+key prepared for MITM"
fi

# Add budget + CA environment to km-http-proxy via systemd drop-in.
# The base unit (section 4) has SANDBOX_ID, ALLOWED_HOSTS, PROXY_PORT.
# This drop-in adds budget enforcement and custom CA config.
mkdir -p /etc/systemd/system/km-http-proxy.service.d
cat > /etc/systemd/system/km-http-proxy.service.d/budget.conf << DROPIN
[Service]
Environment=KM_BUDGET_ENABLED=true
Environment=KM_BUDGET_TABLE={{ .BudgetTable }}
Environment=KM_PROXY_CA_CERT=${KM_PROXY_CA_PEM}
DROPIN

# Reload and restart proxy to pick up budget + CA config.
systemctl daemon-reload
systemctl restart km-http-proxy
echo "[km-bootstrap] km-http-proxy restarted with budget enforcement + custom CA"

# Export budget environment variables for in-sandbox processes
export KM_BUDGET_ENABLED=true
export KM_BUDGET_TABLE="{{ .BudgetTable }}"

# Create /run/km/ for budget_remaining file (written by km-http-proxy when AI budget checked)
mkdir -p /run/km
chmod 755 /run/km

echo "[km-bootstrap] Budget enforcement environment configured"
{{- end }}

{{- if .Rsync }}
# ============================================================
# 7.4. Rsync restore (from S3)
# ============================================================
echo "[km-bootstrap] Restoring rsync snapshot: {{ .Rsync }}"
SHELL_USER=$(awk -F: '$3 >= 1000 && $3 < 65534 {print $1; exit}' /etc/passwd)
SHELL_HOME=$(eval echo "~$SHELL_USER")
aws s3 cp "s3://{{ .KMArtifactsBucket }}/rsync/{{ .Rsync }}.tar.gz" /tmp/km-rsync.tar.gz 2>/dev/null && {
  cd "$SHELL_HOME" && tar xzf /tmp/km-rsync.tar.gz
  chown -R "$SHELL_USER:$SHELL_USER" "$SHELL_HOME"
  echo "[km-bootstrap] Rsync snapshot {{ .Rsync }} restored into $SHELL_HOME"
} || echo "[km-bootstrap] WARNING: rsync snapshot {{ .Rsync }} not found in S3 (skipped)"
{{- end }}
{{- if or .InitCommands .InitScripts }}
# ============================================================
# 7.5. Profile init (commands + scripts downloaded from S3)
# ============================================================
echo "[km-bootstrap] Downloading init payload from S3..."
KM_INIT_BUCKET="{{ .KMArtifactsBucket }}"
aws s3 cp "s3://${KM_INIT_BUCKET}/artifacts/{{ .SandboxID }}/km-init.sh" /tmp/km-init.sh 2>/dev/null && {
  chmod +x /tmp/km-init.sh
  echo "[km-bootstrap] Running init script..."
  /tmp/km-init.sh
  echo "[km-bootstrap] Init complete"
} || echo "[km-bootstrap] No init script found in S3 (skipped)"
{{- end }}

# ============================================================
# 8. Sandbox ready signal
# ============================================================
echo "[km-bootstrap] SANDBOX_READY sandbox_id={{ .SandboxID }}"
`

// parseIdleTimeoutMinutes converts a duration string like "2h" or "30m" to minutes.
// Returns 0 if the string is empty or unparseable.
func parseIdleTimeoutMinutes(s string) int {
	if s == "" {
		return 0
	}
	d, err := time.ParseDuration(s)
	if err != nil {
		return 0
	}
	return int(d.Minutes())
}

// userDataParams holds the template parameters for user-data generation.
type userDataParams struct {
	SandboxID          string
	SecretPaths        []string
	HasGitHub          bool
	HasAllowedRefs     bool   // true when allowedRefs is non-empty
	AllowedRefs        string // colon-separated list for KM_ALLOWED_REFS env var
	AllowedDNSSuffixes string // comma-separated, from profile.Network.Egress.AllowedDNSSuffixes
	AllowedHTTPHosts     string // comma-separated, from profile.Network.Egress.AllowedHosts
	GitHubAllowedRepos   string // comma-separated GitHub repos from profile.sourceAccess.github.allowedRepos
	KMArtifactsBucket    string // from config env var KM_ARTIFACTS_BUCKET
	// Filesystem enforcement (section 2.5)
	ReadOnlyPaths []string
	WritablePaths []string
	// Spot interruption handling (section 6.5)
	UseSpot           bool
	ArtifactPaths     []string
	ArtifactMaxSizeMB int
	// Email fields (MAIL-02 through MAIL-05)
	SandboxEmail         string // {sandbox-id}@{emailDomain} (config-derived)
	EmailDomain          string // e.g. "sandboxes.klankermaker.ai"
	Alias                string // optional human-friendly alias (e.g. "orc-1")
	AliasEmail           string // {alias}@{emailDomain} — set when Alias is non-empty
	NotificationsEmail   string // notifications@{emailDomain} — from address for spot notifications
	OperatorEmail        string // from KM_OPERATOR_EMAIL env var — for spot notification
	AWSRegion            string // from IMDS region — for spot notification ses send-email CLI call
	// Budget enforcement fields (BUDG-03, BUDG-07)
	BudgetEnabled bool   // true when profile.spec.budget is set
	BudgetTable   string // DynamoDB table name from KM_BUDGET_TABLE env var
	// Idle timeout (minutes) — passed to audit-log sidecar for SandboxIdle event detection
	IdleTimeoutMinutes int
	// OTPSecrets holds path + env name pairs for one-time-password secret injection.
	// Each entry is fetched from SSM and deleted after first read.
	OTPSecrets []otpSecret
	// Rsync is the name of a saved home snapshot to restore on boot.
	Rsync string
	// InitCommands is a list of shell commands to run after sidecar startup.
	InitCommands []string
	// InitScripts is a list of S3 keys for init scripts to download and execute.
	InitScripts []string
	// ProfileEnv holds key=value pairs from profile spec.execution.env to export
	// via /etc/profile.d/ so they're available in all login shells (SSM sessions).
	ProfileEnv map[string]string
	// Claude Code OTEL telemetry (OTEL-01, OTEL-06)
	ClaudeTelemetryEnabled        bool
	ClaudeTelemetryLogPrompts     bool
	ClaudeTelemetryLogToolDetails bool
	ProfileName                   string
	Substrate                     string
	// Enforcement selects the network enforcement mode: "proxy", "ebpf", or "both".
	// Defaults to "proxy" when the profile field is unset (backwards compatible).
	// eBPF enforcement is EC2-only in Phase 40.
	Enforcement string
	// TLSEnabled enables TLS uprobe observability via --tls flag on km ebpf-attach.
	// Derived from profile spec.observability.tlsCapture.enabled.
	TLSEnabled bool
	// TLSAllowedRepos is the comma-separated list of allowed GitHub repos
	// passed to --allowed-repos on km ebpf-attach when TLS capture is enabled.
	TLSAllowedRepos string
	// Additional EBS volume mount point (Phase 33)
	// Empty string means no additional volume.
	AdditionalVolumeMountPoint string
	// EFS shared filesystem mount (Phase 43)
	// EFSFilesystemID is non-empty when the profile has mountEFS:true AND EFS is initialized.
	EFSFilesystemID string
	// EFSMountPoint is the filesystem path where EFS is mounted. Default "/shared".
	EFSMountPoint string
	// L7ProxyHosts is a comma-separated list of domain suffixes requiring L7 proxy inspection
	// via connect4 DNAT rewrite. Derived from profile sourceAccess.github and useBedrock fields.
	// Passed to km ebpf-attach --proxy-hosts in "ebpf" and "both" enforcement modes.
	L7ProxyHosts string
}

// parseUserDataTemplate parses the userDataTemplate and returns the compiled template.
// Exported for use in tests that need direct template access.
func parseUserDataTemplate() (*template.Template, error) {
	return template.New("userdata").Parse(userDataTemplate)
}

// otpSecret holds an SSM path and derived env var name for an OTP secret.
type otpSecret struct {
	Path    string // SSM parameter path (e.g. /sandbox/sb-123/otp/github-token)
	EnvName string // derived env var name (e.g. KM_OTP_GITHUB_TOKEN)
}

// joinAllowedRefs returns the AllowedRefs slice as a colon-separated string
// suitable for the KM_ALLOWED_REFS environment variable.
// Returns empty string when GitHub config is nil or AllowedRefs is empty.
func joinAllowedRefs(p *profile.SandboxProfile) string {
	if p.Spec.SourceAccess.GitHub == nil || len(p.Spec.SourceAccess.GitHub.AllowedRefs) == 0 {
		return ""
	}
	return strings.Join(p.Spec.SourceAccess.GitHub.AllowedRefs, ":")
}

// joinGitHubAllowedRepos returns the AllowedRepos slice as a comma-separated string
// suitable for the KM_GITHUB_ALLOWED_REPOS environment variable.
// Returns empty string when GitHub config is nil or AllowedRepos is empty.
func joinGitHubAllowedRepos(p *profile.SandboxProfile) string {
	if p.Spec.SourceAccess.GitHub == nil || len(p.Spec.SourceAccess.GitHub.AllowedRepos) == 0 {
		return ""
	}
	return strings.Join(p.Spec.SourceAccess.GitHub.AllowedRepos, ",")
}

// buildL7ProxyHosts returns a comma-separated list of domain suffixes that require
// L7 proxy interception (connect4 DNAT rewrite) based on the profile configuration.
// Only domains that the profile actually accesses are included:
//   - GitHub domains when profile has sourceAccess.github configured
//   - Bedrock/Anthropic domains when profile has useBedrock: true
//
// The returned string is passed to km ebpf-attach --proxy-hosts in "ebpf" and
// "both" enforcement modes so the resolver marks resolved IPs for proxy redirect.
func buildL7ProxyHosts(p *profile.SandboxProfile) string {
	var hosts []string
	if p.Spec.SourceAccess.GitHub != nil {
		hosts = append(hosts, "github.com", "api.github.com", "raw.githubusercontent.com", "codeload.githubusercontent.com")
	}
	if p.Spec.Execution.UseBedrock {
		// .amazonaws.com covers Bedrock endpoints (bedrock-runtime.us-east-1.amazonaws.com etc.)
		// This is broader than strictly necessary, but non-Bedrock traffic passes through
		// the proxy transparently without MITM inspection.
		hosts = append(hosts, ".amazonaws.com", "api.anthropic.com")
	}
	return strings.Join(hosts, ",")
}

// generateUserData produces the EC2 bootstrap user-data.sh content for the given profile.
// It is only called for ec2 substrate sandboxes.
// artifactsBucket is from the KM_ARTIFACTS_BUCKET env var; may be empty string.
// useSpot indicates whether the EC2 instance uses spot pricing (enables spot poll loop).
// network carries EFSFilesystemID from efs/outputs.json when EFS is initialized; may be nil.
// emailDomainOverride is variadic for backward compatibility: [0]=emailDomain, [1]=alias.
func generateUserData(p *profile.SandboxProfile, sandboxID string, secretPaths []string, artifactsBucket string, useSpot bool, network *NetworkConfig, emailDomainOverride ...string) (string, error) {
	tmpl, err := template.New("userdata").Parse(userDataTemplate)
	if err != nil {
		return "", err
	}

	emailDomain := "sandboxes.klankermaker.ai"
	alias := ""
	if len(emailDomainOverride) > 0 && emailDomainOverride[0] != "" {
		emailDomain = emailDomainOverride[0]
	}
	if len(emailDomainOverride) > 1 && emailDomainOverride[1] != "" {
		alias = emailDomainOverride[1]
	}

	budgetTable := os.Getenv("KM_BUDGET_TABLE")
	if budgetTable == "" {
		budgetTable = "km-budgets"
	}

	params := userDataParams{
		SandboxID:          sandboxID,
		SecretPaths:        secretPaths,
		HasGitHub:          p.Spec.SourceAccess.GitHub != nil && len(p.Spec.SourceAccess.GitHub.AllowedRepos) > 0,
		HasAllowedRefs:     p.Spec.SourceAccess.GitHub != nil && len(p.Spec.SourceAccess.GitHub.AllowedRefs) > 0,
		AllowedRefs:        joinAllowedRefs(p),
		AllowedDNSSuffixes:  strings.Join(p.Spec.Network.Egress.AllowedDNSSuffixes, ","),
		AllowedHTTPHosts:    strings.Join(append(p.Spec.Network.Egress.AllowedHosts, p.Spec.Network.Egress.AllowedDNSSuffixes...), ","),
		GitHubAllowedRepos:  joinGitHubAllowedRepos(p),
		KMArtifactsBucket:   artifactsBucket,
		UseSpot:            useSpot,
		// Email fields — every sandbox gets an email identity.
		SandboxEmail:       sandboxID + "@" + emailDomain,
		EmailDomain:        emailDomain,
		Alias:              alias,
		NotificationsEmail: "notifications@" + emailDomain,
		OperatorEmail:      os.Getenv("KM_OPERATOR_EMAIL"),
		AWSRegion:          p.Spec.Runtime.Region,
		// Budget enforcement fields — enable when profile.spec.budget is set.
		BudgetEnabled: p.Spec.Budget != nil,
		BudgetTable:   budgetTable,
		// Idle timeout — converted from duration string to minutes for the sidecar.
		IdleTimeoutMinutes: parseIdleTimeoutMinutes(p.Spec.Lifecycle.IdleTimeout),
	}

	// Populate alias email when alias is set.
	if alias != "" {
		params.AliasEmail = alias + "@" + emailDomain
	}

	// Populate artifact fields (nil-safe)
	if p.Spec.Artifacts != nil {
		params.ArtifactPaths = p.Spec.Artifacts.Paths
		params.ArtifactMaxSizeMB = p.Spec.Artifacts.MaxSizeMB
	}

	// Populate OTP secrets (nil-safe)
	if p.Spec.OTP != nil {
		for _, path := range p.Spec.OTP.Secrets {
			params.OTPSecrets = append(params.OTPSecrets, otpSecret{
				Path:    path,
				EnvName: otpEnvName(path),
			})
		}
	}

	// Populate rsync, init commands, and profile env vars
	params.Rsync = p.Spec.Execution.Rsync
	params.InitCommands = p.Spec.Execution.InitCommands
	params.InitScripts = p.Spec.Execution.InitScripts
	params.ProfileEnv = mergeBedrockEnv(p)

	// Populate Claude Code OTEL telemetry fields (OTEL-01, OTEL-06).
	// IsEnabled() returns true when ClaudeTelemetry is nil (default on).
	ct := p.Spec.Observability.ClaudeTelemetry
	params.ClaudeTelemetryEnabled = ct.IsEnabled()
	if ct != nil {
		params.ClaudeTelemetryLogPrompts = ct.LogPrompts
		params.ClaudeTelemetryLogToolDetails = ct.LogToolDetails
	}
	params.ProfileName = p.Metadata.Name
	params.Substrate = p.Spec.Runtime.Substrate

	// Populate enforcement mode — default to "proxy" for backwards compatibility.
	enforcement := p.Spec.Network.Enforcement
	if enforcement == "" {
		enforcement = "proxy"
	}
	params.Enforcement = enforcement

	// TLS uprobe observability — enable when profile has tlsCapture enabled.
	if p.Spec.Observability.TlsCapture.IsEnabled() {
		params.TLSEnabled = true
		params.TLSAllowedRepos = joinGitHubAllowedRepos(p)
	}

	// L7 proxy hosts — domain suffixes that require connect4 DNAT redirect to the L7 proxy.
	// Derived from profile fields (GitHub + Bedrock) rather than repo names.
	params.L7ProxyHosts = buildL7ProxyHosts(p)

	// Additional EBS volume mount point (Phase 33)
	if p.Spec.Runtime.AdditionalVolume != nil {
		params.AdditionalVolumeMountPoint = p.Spec.Runtime.AdditionalVolume.MountPoint
	}

	// EFS shared filesystem mount (Phase 43)
	// Only set when profile requests it AND the network config has a filesystem ID.
	if p.Spec.Runtime.MountEFS && network != nil && network.EFSFilesystemID != "" {
		params.EFSFilesystemID = network.EFSFilesystemID
		params.EFSMountPoint = p.Spec.Runtime.EFSMountPoint
		if params.EFSMountPoint == "" {
			params.EFSMountPoint = "/shared"
		}
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", err
	}
	return buf.String(), nil
}
