package compiler

import (
	"bytes"
	"os"
	"strings"
	"text/template"
	"time"

	"github.com/whereiskurt/klankrmkr/pkg/profile"
)

// userDataTemplate generates the EC2 bootstrap script.
// It performs: SSM agent install, IMDSv2 verification, secret injection,
// optional GitHub token injection, filesystem bind mounts (2.5), sidecar install,
// iptables DNAT, spot interruption handler (6.5), and SANDBOX_READY signal.
const userDataTemplate = `#!/bin/bash
# Klankrmkr sandbox bootstrap — generated by profile compiler
# DO NOT EDIT — this file is overwritten on each provision

set -euo pipefail

# ============================================================
# 1. SSM Agent: install and start
# ============================================================
echo "[km-bootstrap] Installing amazon-ssm-agent..."
yum install -y amazon-ssm-agent 2>&1 | tee -a /var/log/km-bootstrap.log
systemctl enable amazon-ssm-agent
systemctl start amazon-ssm-agent
echo "[km-bootstrap] SSM agent started"

# ============================================================
# 2. IMDSv2: verify token-based metadata access is working
# ============================================================
echo "[km-bootstrap] Verifying IMDSv2 token..."
IMDS_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>&1)
if [ -z "$IMDS_TOKEN" ]; then
  echo "[km-bootstrap] ERROR: IMDSv2 token fetch failed — cannot access instance metadata" >&2
  exit 1
fi
echo "[km-bootstrap] IMDSv2 token obtained successfully"

# Retrieve instance region for SSM API calls
REGION=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
  http://169.254.169.254/latest/meta-data/placement/region)
export AWS_DEFAULT_REGION="${REGION}"
echo "[km-bootstrap] Region: $REGION"

# ============================================================
# 2.5. Filesystem policy: read-only bind mounts (before sidecar startup)
# ============================================================
{{- if .ReadOnlyPaths }}
echo "[km-bootstrap] Applying filesystem read-only bind mounts..."
{{- range .ReadOnlyPaths }}
mount --bind "{{ . }}" "{{ . }}"
mount -o remount,bind,ro "{{ . }}"
{{- end }}
echo "[km-bootstrap] Read-only bind mounts applied"
{{- end }}

# ============================================================
# 3. Secret injection: fetch allowed SSM paths and export as env vars
# ============================================================
{{- if .SecretPaths }}
echo "[km-bootstrap] Injecting secrets from SSM..."
declare -A SECRET_PATHS=(
{{- range .SecretPaths }}
  ["{{ . }}"]="{{ . }}"
{{- end }}
)
for PATH_KEY in "${!SECRET_PATHS[@]}"; do
  PARAM_NAME="${SECRET_PATHS[$PATH_KEY]}"
  # aws ssm get-parameter with --with-decryption to support SecureString
  SECRET_VALUE=$(aws ssm get-parameter \
    --name "$PARAM_NAME" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>&1)
  if [ $? -eq 0 ]; then
    # Derive env var name from last path component, uppercased
    ENV_NAME=$(basename "$PARAM_NAME" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
    export "${ENV_NAME}=${SECRET_VALUE}"
    echo "[km-bootstrap] Injected secret: $PARAM_NAME -> $ENV_NAME"
  else
    echo "[km-bootstrap] WARNING: failed to fetch secret $PARAM_NAME" >&2
  fi
done
{{- else }}
echo "[km-bootstrap] No secrets to inject"
{{- end }}

# ============================================================
# 3.5. Email address: expose sandbox email as env var
# ============================================================
{{- if .SandboxEmail }}
export KM_EMAIL_ADDRESS="{{ .SandboxEmail }}"
echo "[km-bootstrap] KM_EMAIL_ADDRESS={{ .SandboxEmail }}"
{{- end }}

# ============================================================
# 4. GitHub credential helper: GIT_ASKPASS (if GitHub access is configured)
# EC2 only — token fetched from per-sandbox SSM at git-operation time.
# ECS credential helper delivery is deferred to a future phase.
# ============================================================
{{- if .HasGitHub }}
echo "[km-bootstrap] Installing GIT_ASKPASS credential helper..."
SANDBOX_ID="{{ .SandboxID }}"
export SANDBOX_ID
mkdir -p /opt/km/bin
cat > /opt/km/bin/km-git-askpass << 'ASKPASS'
#!/bin/bash
TOKEN=$(aws ssm get-parameter \
  --name "/sandbox/${SANDBOX_ID}/github-token" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text 2>/dev/null || echo "")
case "$1" in
  *Username*) echo "x-access-token" ;;
  *Password*) echo "$TOKEN" ;;
  *)          echo "" ;;
esac
ASKPASS
chmod +x /opt/km/bin/km-git-askpass
export GIT_ASKPASS=/opt/km/bin/km-git-askpass
echo "[km-bootstrap] GIT_ASKPASS credential helper installed"
{{- end }}

# ============================================================
# 5. Sidecar binaries: install DNS proxy, HTTP proxy, audit log
# ============================================================
echo "[km-bootstrap] Installing km sidecars..."
mkdir -p /opt/km/bin /etc/km/tracing

# Download sidecar binaries from S3 (km-sandbox-artifacts bucket)
KM_ARTIFACTS_BUCKET="{{ .KMArtifactsBucket }}"
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/dns-proxy" /opt/km/bin/km-dns-proxy
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/http-proxy" /opt/km/bin/km-http-proxy
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/audit-log" /opt/km/bin/km-audit-log
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/tracing/config.yaml" /etc/km/tracing/config.yaml
chmod +x /opt/km/bin/km-*

# Create dedicated sidecar user (exempt from iptables DNAT — prevents redirect loops)
useradd -r -s /usr/sbin/nologin km-sidecar || true

# Write systemd unit files (run all sidecar services as km-sidecar user)
cat > /etc/systemd/system/km-dns-proxy.service << 'UNIT'
[Unit]
Description=Klankrmkr DNS proxy sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=ALLOWED_SUFFIXES={{ .AllowedDNSSuffixes }}
Environment=UPSTREAM_DNS=169.254.169.253
Environment=DNS_PORT=5353
ExecStart=/opt/km/bin/km-dns-proxy
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/km-http-proxy.service << 'UNIT'
[Unit]
Description=Klankrmkr HTTP proxy sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=ALLOWED_HOSTS={{ .AllowedHTTPHosts }}
Environment=PROXY_PORT=3128
ExecStart=/opt/km/bin/km-http-proxy
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

# Create named pipe for audit-log sidecar input.
# Shell commands are written here by PROMPT_COMMAND; sidecar reads from it.
mkdir -p /run/km
mkfifo /run/km/audit-pipe
chown km-sidecar:km-sidecar /run/km/audit-pipe

cat > /etc/systemd/system/km-audit-log.service << 'UNIT'
[Unit]
Description=Klankrmkr audit log sidecar
After=network.target
[Service]
User=km-sidecar
Environment=SANDBOX_ID={{ .SandboxID }}
Environment=CW_LOG_GROUP=/km/sandboxes/{{ .SandboxID }}/
Environment=AUDIT_LOG_DEST=cloudwatch
{{- if gt .IdleTimeoutMinutes 0 }}
Environment=IDLE_TIMEOUT_MINUTES={{ .IdleTimeoutMinutes }}
{{- end }}
ExecStart=/bin/bash -c 'exec 3>/run/km/audit-pipe; exec /opt/km/bin/km-audit-log < /run/km/audit-pipe'
Restart=always
RestartSec=2
[Install]
WantedBy=multi-user.target
UNIT

# Shell audit hook: writes JSON audit events to the named pipe on every command,
# plus a background heartbeat every 60s so long-running commands (top, vim, etc.)
# don't trigger the idle detector.
# Installed as /etc/profile.d/ so it applies to all login shells (SSM sessions).
cat > /etc/profile.d/km-audit.sh << 'HOOK'
_km_audit() {
  local cmd
  cmd=$(history 1 | sed 's/^ *[0-9]* *//')
  printf '{"timestamp":%d,"sandbox_id":"%s","event_type":"command","source":"shell","detail":{"command":"%s","user":"%s"}}\n' \
    "$(date +%s%3N)" "{{ .SandboxID }}" "$(echo "$cmd" | sed 's/"/\\"/g' | head -c 500)" "$(whoami)" \
    > /run/km/audit-pipe 2>/dev/null
}
PROMPT_COMMAND="_km_audit;${PROMPT_COMMAND}"

# Background heartbeat: keeps the sandbox alive while a session is open,
# even during long-running commands. Killed automatically when the shell exits.
_km_heartbeat() {
  while true; do
    sleep 60
    printf '{"timestamp":%d,"sandbox_id":"%s","event_type":"heartbeat","source":"shell","detail":{}}\n' \
      "$(date +%s%3N)" "{{ .SandboxID }}" > /run/km/audit-pipe 2>/dev/null
  done
}
_km_heartbeat &
_KM_HEARTBEAT_PID=$!
trap 'kill $_KM_HEARTBEAT_PID 2>/dev/null' EXIT
HOOK
chmod 644 /etc/profile.d/km-audit.sh

systemctl daemon-reload
systemctl enable km-dns-proxy km-http-proxy km-audit-log
systemctl start km-dns-proxy km-http-proxy km-audit-log
echo "[km-bootstrap] Sidecars started"
echo "[km-bootstrap] Shell audit hook installed at /etc/profile.d/km-audit.sh"

# ============================================================
# 6. iptables DNAT: redirect DNS and HTTP traffic to sidecars
# ============================================================
echo "[km-bootstrap] Configuring iptables DNAT..."

# IMDS exemption MUST be inserted first (-I inserts at top of chain).
# Without this, IMDSv2 PUT token requests (port 80 to 169.254.169.254)
# are redirected to the HTTP proxy and fail, breaking SSM and credential refresh.
iptables -t nat -I OUTPUT -d 169.254.169.254 -j RETURN

# DNS: redirect UDP/TCP port 53 to local DNS proxy on :5353
# ! --uid-owner km-sidecar exempts the proxy's own upstream queries (prevents redirect loop)
iptables -t nat -A OUTPUT -p udp --dport 53 ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 5353
iptables -t nat -A OUTPUT -p tcp --dport 53 ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 5353

# HTTP/HTTPS: redirect to HTTP proxy on :3128
# km-sidecar user is exempt to prevent the proxy from redirecting its own upstream connections
iptables -t nat -A OUTPUT -p tcp --dport 80  ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 3128
iptables -t nat -A OUTPUT -p tcp --dport 443 ! -m owner --uid-owner km-sidecar -j REDIRECT --to-ports 3128

echo "[km-bootstrap] iptables DNAT configured"

# ============================================================
# 6.5. Spot interruption handler (background)
# ============================================================
{{- if .UseSpot }}
{{- if .ArtifactPaths }}
# Write artifact upload helper script
cat > /opt/km/bin/km-upload-artifacts << 'UPLOADSCRIPT'
#!/bin/bash
# Upload configured artifact paths to S3
BUCKET="{{ .KMArtifactsBucket }}"
SANDBOX_ID="{{ .SandboxID }}"
MAX_SIZE_MB={{ .ArtifactMaxSizeMB }}
ARTIFACT_PATHS=({{ range .ArtifactPaths }}"{{ . }}" {{ end }})
for APATH in "${ARTIFACT_PATHS[@]}"; do
  find "$APATH" -type f 2>/dev/null | while read FILE; do
    SIZE_MB=$(( $(stat -f%z "$FILE" 2>/dev/null || stat --printf="%s" "$FILE" 2>/dev/null) / 1048576 ))
    if [ "$MAX_SIZE_MB" -gt 0 ] && [ "$SIZE_MB" -gt "$MAX_SIZE_MB" ]; then
      echo "[km-upload] SKIP $FILE (${SIZE_MB}MB > ${MAX_SIZE_MB}MB limit)"
      continue
    fi
    REL_PATH="${FILE#/}"
    aws s3 cp "$FILE" "s3://${BUCKET}/artifacts/${SANDBOX_ID}/${REL_PATH}" 2>&1 || echo "[km-upload] WARN: failed to upload $FILE"
  done
done
UPLOADSCRIPT
chmod +x /opt/km/bin/km-upload-artifacts
{{- end }}
(
  while true; do
    SPOT_ACTION=$(curl -sf \
      -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
      "http://169.254.169.254/latest/meta-data/spot/termination-time" 2>/dev/null || echo "")
    if [ -n "$SPOT_ACTION" ]; then
      echo "[km-spot] Spot interruption detected at $SPOT_ACTION"
      {{- if .ArtifactPaths }}
      /opt/km/bin/km-upload-artifacts || true
      {{- end }}
      {{- if .OperatorEmail }}
      aws sesv2 send-email --from-email-address "{{ .NotificationsEmail }}" \
        --destination "ToAddresses={{ .OperatorEmail }}" \
        --content "Simple={Subject={Data='km sandbox spot-interruption: {{ .SandboxID }}'},Body={Text={Data='Sandbox {{ .SandboxID }} received spot interruption notice. Artifacts uploaded (best-effort).'}}}" \
        --region "${AWS_DEFAULT_REGION}" 2>&1 || echo "[km-spot] WARN: failed to send spot notification"
      {{- end }}
      echo "[km-spot] Shutdown handler complete"
      break
    fi
    sleep 5
  done
) &
{{- end }}

# ============================================================
# 7. Budget enforcement setup (if enabled)
# ============================================================
{{- if .BudgetEnabled }}
echo "[km-bootstrap] Setting up budget enforcement environment..."

# Install goproxy CA cert for MITM proxy so budget-tracked traffic
# (HTTP/HTTPS via km-http-proxy) can be inspected for AI spend tracking.
# The CA cert (public) is stored in S3 at sidecars/km-proxy-ca.crt.
# The CA key (private) is stored in S3 at sidecars/km-proxy-ca.key.
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/km-proxy-ca.crt" \
  /usr/local/share/ca-certificates/km-proxy-ca.crt 2>&1 || \
  echo "[km-bootstrap] WARNING: could not fetch proxy CA cert; AI spend tracking may be incomplete"
aws s3 cp "s3://${KM_ARTIFACTS_BUCKET}/sidecars/km-proxy-ca.key" \
  /etc/km/proxy-ca.key 2>&1 || \
  echo "[km-bootstrap] WARNING: could not fetch proxy CA key; MITM will use default CA"
chmod 600 /etc/km/proxy-ca.key 2>/dev/null

if [ -f /usr/local/share/ca-certificates/km-proxy-ca.crt ]; then
  update-ca-certificates
  echo "[km-bootstrap] Proxy CA cert installed in system trust store"
fi

# Build base64 PEM (cert+key) for the proxy's KM_PROXY_CA_CERT env var.
# The proxy uses this to sign MITM leaf certificates that the sandbox trusts.
KM_PROXY_CA_PEM=""
if [ -f /usr/local/share/ca-certificates/km-proxy-ca.crt ] && [ -f /etc/km/proxy-ca.key ]; then
  KM_PROXY_CA_PEM=$(cat /usr/local/share/ca-certificates/km-proxy-ca.crt /etc/km/proxy-ca.key | base64 -w0)
  echo "[km-bootstrap] Proxy CA cert+key prepared for MITM"
fi

# Add budget + CA environment to km-http-proxy via systemd drop-in.
# The base unit (section 4) has SANDBOX_ID, ALLOWED_HOSTS, PROXY_PORT.
# This drop-in adds budget enforcement and custom CA config.
mkdir -p /etc/systemd/system/km-http-proxy.service.d
cat > /etc/systemd/system/km-http-proxy.service.d/budget.conf << DROPIN
[Service]
Environment=KM_BUDGET_ENABLED=true
Environment=KM_BUDGET_TABLE={{ .BudgetTable }}
Environment=KM_PROXY_CA_CERT=${KM_PROXY_CA_PEM}
DROPIN

# Reload and restart proxy to pick up budget + CA config.
systemctl daemon-reload
systemctl restart km-http-proxy
echo "[km-bootstrap] km-http-proxy restarted with budget enforcement + custom CA"

# Export budget environment variables for in-sandbox processes
export KM_BUDGET_ENABLED=true
export KM_BUDGET_TABLE="{{ .BudgetTable }}"

# Create /run/km/ for budget_remaining file (written by km-http-proxy when AI budget checked)
mkdir -p /run/km
chmod 755 /run/km

echo "[km-bootstrap] Budget enforcement environment configured"
{{- end }}

# ============================================================
# 8. Sandbox ready signal
# ============================================================
echo "[km-bootstrap] SANDBOX_READY sandbox_id={{ .SandboxID }}"
`

// parseIdleTimeoutMinutes converts a duration string like "2h" or "30m" to minutes.
// Returns 0 if the string is empty or unparseable.
func parseIdleTimeoutMinutes(s string) int {
	if s == "" {
		return 0
	}
	d, err := time.ParseDuration(s)
	if err != nil {
		return 0
	}
	return int(d.Minutes())
}

// userDataParams holds the template parameters for user-data generation.
type userDataParams struct {
	SandboxID          string
	SecretPaths        []string
	HasGitHub          bool
	AllowedDNSSuffixes string // comma-separated, from profile.Network.Egress.AllowedDNSSuffixes
	AllowedHTTPHosts   string // comma-separated, from profile.Network.Egress.AllowedHosts
	KMArtifactsBucket  string // from config env var KM_ARTIFACTS_BUCKET
	// Filesystem enforcement (section 2.5)
	ReadOnlyPaths []string
	WritablePaths []string
	// Spot interruption handling (section 6.5)
	UseSpot           bool
	ArtifactPaths     []string
	ArtifactMaxSizeMB int
	// Email fields (MAIL-02 through MAIL-05)
	SandboxEmail         string // {sandbox-id}@{emailDomain} (config-derived)
	NotificationsEmail   string // notifications@{emailDomain} — from address for spot notifications
	OperatorEmail        string // from KM_OPERATOR_EMAIL env var — for spot notification
	AWSRegion            string // from IMDS region — for spot notification ses send-email CLI call
	// Budget enforcement fields (BUDG-03, BUDG-07)
	BudgetEnabled bool   // true when profile.spec.budget is set
	BudgetTable   string // DynamoDB table name from KM_BUDGET_TABLE env var
	// Idle timeout (minutes) — passed to audit-log sidecar for SandboxIdle event detection
	IdleTimeoutMinutes int
}

// generateUserData produces the EC2 bootstrap user-data.sh content for the given profile.
// It is only called for ec2 substrate sandboxes.
// artifactsBucket is from the KM_ARTIFACTS_BUCKET env var; may be empty string.
// useSpot indicates whether the EC2 instance uses spot pricing (enables spot poll loop).
// emailDomain is the sandboxes subdomain (e.g. "sandboxes.klankermaker.ai"); defaults to
// "sandboxes.klankermaker.ai" when not provided (variadic for backward compatibility).
func generateUserData(p *profile.SandboxProfile, sandboxID string, secretPaths []string, artifactsBucket string, useSpot bool, emailDomainOverride ...string) (string, error) {
	tmpl, err := template.New("userdata").Parse(userDataTemplate)
	if err != nil {
		return "", err
	}

	emailDomain := "sandboxes.klankermaker.ai"
	if len(emailDomainOverride) > 0 && emailDomainOverride[0] != "" {
		emailDomain = emailDomainOverride[0]
	}

	budgetTable := os.Getenv("KM_BUDGET_TABLE")
	if budgetTable == "" {
		budgetTable = "km-budgets"
	}

	params := userDataParams{
		SandboxID:          sandboxID,
		SecretPaths:        secretPaths,
		HasGitHub:          p.Spec.SourceAccess.GitHub != nil,
		AllowedDNSSuffixes: strings.Join(p.Spec.Network.Egress.AllowedDNSSuffixes, ","),
		AllowedHTTPHosts:   strings.Join(p.Spec.Network.Egress.AllowedHosts, ","),
		KMArtifactsBucket:  artifactsBucket,
		UseSpot:            useSpot,
		// Email fields — every sandbox gets an email identity.
		SandboxEmail:       sandboxID + "@" + emailDomain,
		NotificationsEmail: "notifications@" + emailDomain,
		OperatorEmail:      os.Getenv("KM_OPERATOR_EMAIL"),
		AWSRegion:          p.Spec.Runtime.Region,
		// Budget enforcement fields — enable when profile.spec.budget is set.
		BudgetEnabled: p.Spec.Budget != nil,
		BudgetTable:   budgetTable,
		// Idle timeout — converted from duration string to minutes for the sidecar.
		IdleTimeoutMinutes: parseIdleTimeoutMinutes(p.Spec.Lifecycle.IdleTimeout),
	}

	// Populate filesystem policy fields (nil-safe)
	if p.Spec.Policy.FilesystemPolicy != nil {
		params.ReadOnlyPaths = p.Spec.Policy.FilesystemPolicy.ReadOnlyPaths
		params.WritablePaths = p.Spec.Policy.FilesystemPolicy.WritablePaths
	}

	// Populate artifact fields (nil-safe)
	if p.Spec.Artifacts != nil {
		params.ArtifactPaths = p.Spec.Artifacts.Paths
		params.ArtifactMaxSizeMB = p.Spec.Artifacts.MaxSizeMB
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", err
	}
	return buf.String(), nil
}
