#kubectl apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: km
  namespace: security
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::01234567890:role/kph-cluster-dev-use1-0
    eks.amazonaws.com/token-expiration: "3600"
#EOF