/* SPDX-License-Identifier: GPL-2.0-only */
/* common.h — Shared BPF types and volatile configuration constants.
 *
 * Included by bpf.c only. Go-side equivalents are in types.go.
 */
#pragma once

/* ── Integer types ─────────────────────────────────────────────────── */
typedef unsigned char  u8;
typedef unsigned short u16;
typedef unsigned int   u32;
typedef unsigned long long u64;

/* ── Network byte-order helpers ────────────────────────────────────── */
static __attribute__((always_inline)) u32 bpf_htonl(u32 x) {
    return __builtin_bswap32(x);
}
static __attribute__((always_inline)) u32 bpf_ntohl(u32 x) {
    return __builtin_bswap32(x);
}
static __attribute__((always_inline)) u16 bpf_htons(u16 x) {
    return __builtin_bswap16(x);
}
static __attribute__((always_inline)) u16 bpf_ntohs(u16 x) {
    return __builtin_bswap16(x);
}

/* ── Ring-buffer event struct ──────────────────────────────────────── */
/* Go-side mirror: bpfEvent (generated by bpf2go -type event) */
struct event {
    u64 timestamp;   /* bpf_ktime_get_ns() */
    u32 pid;         /* tgid from bpf_get_current_pid_tgid() >> 32 */
    u32 src_ip;      /* network byte order */
    u32 dst_ip;      /* network byte order */
    u16 dst_port;    /* host byte order */
    u8  action;      /* 0=deny, 1=allow, 2=redirect */
    u8  layer;       /* 1=connect4, 2=sendmsg4, 3=egress_skb, 4=sockops */
    u8  comm[16];    /* task name from bpf_get_current_comm() */
    u8  _pad[7];     /* explicit padding to 64-byte alignment */
};

/* ── LPM_TRIE key for IPv4 CIDR lookups ───────────────────────────── */
/* Go-side mirror: LpmKey in types.go */
struct ip4_trie_key {
    u32 prefixlen; /* 0-32 */
    u8  addr[4];   /* network byte order */
};

/* ── Action constants (must match types.go) ────────────────────────── */
#define ACTION_DENY     0
#define ACTION_ALLOW    1
#define ACTION_REDIRECT 2

/* ── Layer constants (must match types.go) ─────────────────────────── */
#define LAYER_CONNECT4   1
#define LAYER_SENDMSG4   2
#define LAYER_EGRESS_SKB 3
#define LAYER_SOCKOPS    4

/* ── Firewall mode constants (must match types.go) ─────────────────── */
#define MODE_LOG   0
#define MODE_ALLOW 1
#define MODE_BLOCK 2

/* ── Volatile constants — set at load time by the Go loader ────────── */
/* const_dns_proxy_port: UDP port the local DNS proxy listens on (host byte order) */
volatile const u32 const_dns_proxy_port = 5353;

/* const_proxy_pid: PID of the sidecar proxy process (exempt from interception) */
volatile const u32 const_proxy_pid = 0;

/* const_http_proxy_port: TCP port to redirect HTTP (port 80) connections to */
volatile const u32 const_http_proxy_port = 3128;

/* const_https_proxy_port: TCP port to redirect HTTPS (port 443) connections to */
volatile const u32 const_https_proxy_port = 3129;

/* const_firewall_mode: 0=log, 1=allow (permissive), 2=block (enforcing) */
volatile const u16 const_firewall_mode = MODE_LOG;

/* const_mitm_proxy_address: IPv4 address of the MITM proxy in network byte order
 * Default 0x0100007f = 127.0.0.1 in big-endian. */
volatile const u32 const_mitm_proxy_address = 0x0100007f;
