/* SPDX-License-Identifier: GPL-2.0-only */
/* vmlinux.h — Minimal kernel type subset for CO-RE BPF programs.
 *
 * This is NOT the full vmlinux.h generated by bpftool. It contains only
 * the struct definitions and type aliases that our BPF programs reference.
 * Targeting Linux 6.1 (Amazon Linux 2023 default kernel).
 *
 * Pattern: cilium/ebpf minimal headers for portable BPF programs.
 */
#pragma once

/* ── BTF integer types ─────────────────────────────────────────────── */
typedef unsigned char  __u8;
typedef unsigned short __u16;
typedef unsigned int   __u32;
typedef unsigned long long __u64;
typedef signed char    __s8;
typedef short          __s16;
typedef int            __s32;
typedef long long      __s64;

/* Network byte-order annotated types (big-endian on all arches for BPF) */
typedef __u16 __be16;
typedef __u32 __be32;
typedef __u64 __be64;

/* ── bpf_sock_addr — context for cgroup/connect4 and cgroup/sendmsg4 ─ */
/* See: include/uapi/linux/bpf.h */
struct bpf_sock_addr {
    __u32 user_family;    /* 2 = AF_INET */
    __u32 user_ip4;       /* destination IPv4 in network byte order */
    __u32 user_ip6[4];    /* destination IPv6 (unused here) */
    __u32 user_port;      /* destination port in network byte order (high 16 bits) */
    __u32 family;
    __u32 type;
    __u32 protocol;
    __u32 msg_src_ip4;    /* source IPv4 for sendmsg (sendmsg4 only) */
    __u32 msg_src_ip6[4];
    /* ... more fields follow in kernel, but we only use the above */
};

/* ── __sk_buff — context for cgroup_skb/egress ─────────────────────── */
/* See: include/uapi/linux/bpf.h */
struct __sk_buff {
    __u32 len;
    __u32 pkt_type;
    __u32 mark;
    __u32 queue_mapping;
    __u32 protocol;       /* ETH_P_IP = 0x0800 in host byte order after cgroup_skb */
    __u32 vlan_present;
    __u32 vlan_tci;
    __u32 vlan_proto;
    __u32 priority;
    __u32 ingress_ifindex;
    __u32 ifindex;
    __u32 tc_index;
    __u32 cb[5];
    __u32 hash;
    __u32 tc_classid;
    __u32 data;           /* pointer to packet data start (for direct access) */
    __u32 data_end;       /* pointer to packet data end */
    __u32 napi_id;
    /* ... more fields follow in kernel */
};

/* ── bpf_sock_ops — context for SEC("sockops") ─────────────────────── */
/* See: include/uapi/linux/bpf.h */
struct bpf_sock_ops {
    __u32 op;             /* BPF_SOCK_OPS_* callback opcode */
    union {
        __u32 args[4];
        __u32 reply;
        __u32 replylong[4];
    };
    __u32 family;
    __u32 remote_ip4;     /* network byte order */
    __u32 local_ip4;      /* network byte order */
    __u32 remote_ip6[4];
    __u32 local_ip6[4];
    __u32 remote_port;    /* host byte order */
    __u32 local_port;     /* host byte order */
    __u32 is_fullsock;
    __u32 snd_cwnd;
    __u32 srtt_us;
    __u32 bpf_sock_ops_cb_flags;
    __u32 state;
    __u32 rtt_min;
    __u32 snd_ssthresh;
    __u32 rcv_nxt;
    __u32 snd_nxt;
    __u32 snd_una;
    __u32 mss_cache;
    __u32 ecn_flags;
    __u32 rate_delivered;
    __u32 rate_interval_us;
    __u32 packet_seq_num;
    __u32 data_segs_in;
    __u32 data_segs_out;
    /* ... more fields; we only use op and local_port */
};

/* ── IPv4 header ────────────────────────────────────────────────────── */
/* Minimal iphdr for bpf_skb_load_bytes parsing in cgroup_skb/egress */
struct iphdr {
    __u8  ihl:4;
    __u8  version:4;
    __u8  tos;
    __be16 tot_len;
    __be16 id;
    __be16 frag_off;
    __u8  ttl;
    __u8  protocol;
    __be16 check;
    __be32 saddr;
    __be32 daddr;
};
