//go:build linux && amd64

package sni

import (
	"fmt"
	"net"
	"strings"

	"github.com/cilium/ebpf"
	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
)

// SNIFilter attaches a TC egress classifier to a network interface that
// inspects TLS ClientHello SNI on port 443 and drops disallowed hostnames.
//
// This is a best-effort layer: ClientHellos fragmented across TCP segments
// (e.g. large Chrome hellos) cannot be inspected and are passed through.
//
// Compatible with kernel 6.1+ (uses classic cls_bpf, not TCX which needs 6.6+).
type SNIFilter struct {
	objs    *sniObjects
	qdisc   netlink.Qdisc
	filter  netlink.Filter
	ifIndex int
	ifName  string
	pinPath string
}

// SNIConfig configures a new SNIFilter.
type SNIConfig struct {
	// SandboxID is the identifier of the sandbox being filtered (for logging).
	SandboxID string

	// Interface is the network interface name to attach to (e.g. "eth0").
	Interface string

	// PinPath is the BPF filesystem path to pin objects under, e.g.
	// "/sys/fs/bpf/km-sni-<sandbox-id>". Pin path must be on a bpffs mount.
	// If empty, objects are not pinned.
	PinPath string
}

// NewSNIFilter creates and attaches a TC SNI classifier to the given network
// interface. On success the filter is live immediately; call AllowSNI() to
// populate the allowlist and then the classifier will enforce it.
//
// If the clsact qdisc already exists on the interface, it is reused.
func NewSNIFilter(cfg SNIConfig) (*SNIFilter, error) {
	iface, err := net.InterfaceByName(cfg.Interface)
	if err != nil {
		return nil, fmt.Errorf("sni: interface %q not found: %w", cfg.Interface, err)
	}

	// Load BPF objects from the embedded bytecode generated by bpf2go.
	objs := &sniObjects{}
	opts := &ebpf.CollectionOptions{}
	if cfg.PinPath != "" {
		opts.Maps.PinPath = cfg.PinPath
	}
	if err := loadSniObjects(objs, opts); err != nil {
		return nil, fmt.Errorf("sni: load BPF objects: %w", err)
	}

	f := &SNIFilter{
		objs:    objs,
		ifIndex: iface.Index,
		ifName:  cfg.Interface,
		pinPath: cfg.PinPath,
	}

	// Add clsact qdisc to the interface. clsact is a special "classless"
	// qdisc that provides ingress and egress hook points for cls_bpf filters.
	// If it already exists on the interface (e.g. from a previous run) we
	// ignore the EEXIST error and proceed to attach the filter.
	qdisc := &netlink.GenericQdisc{
		QdiscAttrs: netlink.QdiscAttrs{
			LinkIndex: iface.Index,
			Handle:    netlink.MakeHandle(0xffff, 0),
			Parent:    netlink.HANDLE_CLSACT,
		},
		QdiscType: "clsact",
	}
	if err := netlink.QdiscAdd(qdisc); err != nil {
		// EEXIST means clsact is already present; that is fine.
		if !isEEXIST(err) {
			objs.Close()
			return nil, fmt.Errorf("sni: add clsact qdisc on %s: %w", cfg.Interface, err)
		}
	}
	f.qdisc = qdisc

	// Add TC egress filter (cls_bpf) on HANDLE_MIN_EGRESS.
	// DirectAction=true means the BPF program return value is used directly
	// as the TC verdict (TC_ACT_OK, TC_ACT_SHOT, etc.) without a separate
	// action module.
	filter := &netlink.BpfFilter{
		FilterAttrs: netlink.FilterAttrs{
			LinkIndex: iface.Index,
			Parent:    netlink.HANDLE_MIN_EGRESS,
			Handle:    netlink.MakeHandle(0, 1),
			Protocol:  unix.ETH_P_ALL,
			Priority:  1,
		},
		Fd:           objs.SniFilter.FD(),
		Name:         fmt.Sprintf("km-sni-%s", cfg.SandboxID),
		DirectAction: true,
	}
	if err := netlink.FilterAdd(filter); err != nil {
		// Best-effort qdisc cleanup on failure.
		_ = netlink.QdiscDel(qdisc)
		objs.Close()
		return nil, fmt.Errorf("sni: add TC egress filter on %s: %w", cfg.Interface, err)
	}
	f.filter = filter

	return f, nil
}

// AllowSNI adds a hostname to the SNI allowlist. The hostname is lowercased
// before insertion. Wildcard patterns are NOT supported — only exact matches.
//
// AllowSNI may be called concurrently (BPF map operations are atomic).
func (f *SNIFilter) AllowSNI(hostname string) error {
	key, err := hostnameToKey(hostname)
	if err != nil {
		return err
	}
	val := uint8(1)
	if err := f.objs.AllowedSni.Put(key, val); err != nil {
		return fmt.Errorf("sni: AllowSNI %q: %w", hostname, err)
	}
	return nil
}

// RemoveSNI removes a hostname from the SNI allowlist. If the hostname is not
// present, RemoveSNI returns nil (idempotent).
func (f *SNIFilter) RemoveSNI(hostname string) error {
	key, err := hostnameToKey(hostname)
	if err != nil {
		return err
	}
	if err := f.objs.AllowedSni.Delete(key); err != nil {
		// ENOENT means the key was not present; treat as success.
		if isENOENT(err) {
			return nil
		}
		return fmt.Errorf("sni: RemoveSNI %q: %w", hostname, err)
	}
	return nil
}

// Close removes the TC filter and clsact qdisc from the interface, then closes
// and (if pinned) unpins the BPF objects. It is safe to call Close multiple
// times.
func (f *SNIFilter) Close() error {
	var errs []string

	if f.filter != nil {
		if err := netlink.FilterDel(f.filter); err != nil && !isENOENT(err) {
			errs = append(errs, fmt.Sprintf("delete TC filter: %v", err))
		}
		f.filter = nil
	}

	if f.qdisc != nil {
		if err := netlink.QdiscDel(f.qdisc); err != nil && !isENOENT(err) {
			errs = append(errs, fmt.Sprintf("delete clsact qdisc: %v", err))
		}
		f.qdisc = nil
	}

	if f.objs != nil {
		if err := f.objs.Close(); err != nil {
			errs = append(errs, fmt.Sprintf("close BPF objects: %v", err))
		}
		f.objs = nil
	}

	if len(errs) > 0 {
		return fmt.Errorf("sni: Close: %s", strings.Join(errs, "; "))
	}
	return nil
}

// hostnameToKey converts a hostname string to the [256]byte null-padded
// lowercase key used in the allowed_sni BPF map.
func hostnameToKey(hostname string) ([256]byte, error) {
	lower := strings.ToLower(strings.TrimSpace(hostname))
	if len(lower) == 0 {
		return [256]byte{}, fmt.Errorf("sni: hostname must not be empty")
	}
	if len(lower) > 255 {
		return [256]byte{}, fmt.Errorf("sni: hostname %q exceeds 255 bytes", hostname)
	}
	var key [256]byte
	copy(key[:], lower)
	// remaining bytes are zero (null-padded) by Go's zero-value initialization
	return key, nil
}

// isEEXIST reports whether err represents an EEXIST kernel error.
func isEEXIST(err error) bool {
	return strings.Contains(err.Error(), "file exists") ||
		strings.Contains(err.Error(), "exist")
}

// isENOENT reports whether err represents an ENOENT kernel error.
func isENOENT(err error) bool {
	return strings.Contains(err.Error(), "no such file") ||
		strings.Contains(err.Error(), "not exist")
}
