// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package sni

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSni returns the embedded CollectionSpec for sni.
func loadSni() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SniBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sni: %w", err)
	}

	return spec, err
}

// loadSniObjects loads sni and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sniObjects
//	*sniPrograms
//	*sniMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSniObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSni()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sniSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sniSpecs struct {
	sniProgramSpecs
	sniMapSpecs
	sniVariableSpecs
}

// sniProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sniProgramSpecs struct {
	SniFilter *ebpf.ProgramSpec `ebpf:"sni_filter"`
}

// sniMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sniMapSpecs struct {
	AllowedSni *ebpf.MapSpec `ebpf:"allowed_sni"`
	SniEvents  *ebpf.MapSpec `ebpf:"sni_events"`
}

// sniVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sniVariableSpecs struct {
}

// sniObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSniObjects or ebpf.CollectionSpec.LoadAndAssign.
type sniObjects struct {
	sniPrograms
	sniMaps
	sniVariables
}

func (o *sniObjects) Close() error {
	return _SniClose(
		&o.sniPrograms,
		&o.sniMaps,
	)
}

// sniMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSniObjects or ebpf.CollectionSpec.LoadAndAssign.
type sniMaps struct {
	AllowedSni *ebpf.Map `ebpf:"allowed_sni"`
	SniEvents  *ebpf.Map `ebpf:"sni_events"`
}

func (m *sniMaps) Close() error {
	return _SniClose(
		m.AllowedSni,
		m.SniEvents,
	)
}

// sniVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSniObjects or ebpf.CollectionSpec.LoadAndAssign.
type sniVariables struct {
}

// sniPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSniObjects or ebpf.CollectionSpec.LoadAndAssign.
type sniPrograms struct {
	SniFilter *ebpf.Program `ebpf:"sni_filter"`
}

func (p *sniPrograms) Close() error {
	return _SniClose(
		p.SniFilter,
	)
}

func _SniClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sni_x86_bpfel.o
var _SniBytes []byte
