// Package slack — rich.go
// Tier-3 "blocks-rich" renderer. Phase 111.
//
// RenderRich converts GFM markdown input into a Slack Block Kit JSON payload
// using the newer block types (markdown, table) that are unavailable in the
// Tier-2 renderer:
//
//   - Prose segments → {"type":"markdown","text":<verbatim GFM>} blocks.
//     The markdown block accepts native GFM (bold/italic/lists/code/links).
//     Unlike Tier-2, we do NOT run Mrkdwnify — the block handles it natively.
//   - Leading H1 → blockHeader (same as Tier-2, for visual hierarchy).
//   - Tool lines (🔧) → blockContext (same as Tier-2).
//   - GFM pipe tables → blockTable (Phase 111 Plan 02 fills this in).
//   - ai-footer → trailing context block when aiFooter is true.
//
// Fallback chain: RenderRich ok=false → caller uses RenderBlocks → Mrkdwnify.
// The default render path (RenderBlocks / renderBlocks) is NOT touched here.
package slack

import (
	"encoding/json"
	"strings"
)

// maxMarkdownCumulative is the cumulative character budget for all markdown
// blocks in a single chat.postMessage call (Slack API constraint).
const maxMarkdownCumulative = 12000

// blockMarkdown is the Tier-3 prose block type.
// Slack GA Feb 2025: {"type":"markdown","text":"<GFM>"}.
// The text field accepts verbatim GFM — bold/italic/lists/code/native links.
// Do NOT run Mrkdwnify on the text before storing it here.
type blockMarkdown struct {
	Type string `json:"type"` // "markdown"
	Text string `json:"text"`
}

// richSegKind classifies a segment of the input as prose or table.
type richSegKind int

const (
	segRichProse richSegKind = iota // normal prose, headings, tool lines
	segRichTable                    // GFM pipe-table run (≥2 consecutive pipe lines)
)

// richSegment holds one classified chunk of the input.
type richSegment struct {
	kind  richSegKind
	lines []string
}

// RenderRich is the public fail-soft wrapper for the Tier-3 renderer.
// Returns:
//
//	blocksJSON   — pre-serialized JSON array for Slack's `blocks:` field
//	fallbackText — plain-text for chat.postMessage `text:` (push/email/search)
//	ok           — false when a cap is hit or the transformer panics
//
// On ok=false the caller should fall back to RenderBlocks (Tier-2).
// Panics inside renderRich are recovered and return ("", "", false).
func RenderRich(input string, aiFooter bool) (blocksJSON, fallbackText string, ok bool) {
	defer func() {
		if r := recover(); r != nil {
			blocksJSON, fallbackText, ok = "", "", false
		}
	}()
	return renderRich(input, aiFooter)
}

// renderRich is the inner Tier-3 implementation (no recover; RenderRich wraps it).
func renderRich(input string, aiFooter bool) (blocksJSON, fallbackText string, ok bool) {
	segments := segmentInput(input)
	var blocks []any
	var fallbackLines []string
	cumulativeMDChars := 0
	capHit := false

	for _, seg := range segments {
		switch seg.kind {
		case segRichProse:
			newBlocks, newFallback, hit := emitProseBlocks(seg.lines, &cumulativeMDChars)
			blocks = append(blocks, newBlocks...)
			fallbackLines = append(fallbackLines, newFallback...)
			if hit {
				capHit = true
			}
		case segRichTable:
			// Plan 02: replace with buildTableBlock.
			// For now, emit the table lines verbatim as a markdown block
			// (same monospace reflow as Tier-2 uses as fallback).
			tableText := fencePipeTables(strings.Join(seg.lines, "\n"))
			mdb := blockMarkdown{Type: "markdown", Text: tableText}
			blocks = append(blocks, mdb)
			for _, l := range seg.lines {
				fallbackLines = append(fallbackLines, stripForFallback(l))
			}
		}
	}

	if capHit {
		return "", "", false
	}

	if aiFooter {
		blocks = append(blocks, blockContext{
			Type:     "context",
			Elements: []mrkdwnField{{Type: "mrkdwn", Text: "_Generated by AI — verify before sharing._"}},
		})
	}

	// 50-block cap (Slack hard limit).
	if len(blocks) > maxBlocks {
		return "", "", false
	}

	if len(blocks) == 0 {
		return "", "", false
	}

	b, err := json.Marshal(blocks)
	if err != nil {
		return "", "", false
	}

	fallback := buildFallback(fallbackLines)
	return string(b), fallback, true
}

// segmentInput splits input into alternating prose and table segments.
// Table segments are runs of ≥2 consecutive pipe-lines (same threshold as
// fencePipeTables). A solo pipe-line is treated as prose.
// Reuses isPipeLine from mrkdwn.go — detection is identical to fencePipeTables.
func segmentInput(input string) []richSegment {
	lines := strings.Split(input, "\n")
	var segs []richSegment
	i := 0
	for i < len(lines) {
		if isPipeLine(lines[i]) {
			// Collect the full pipe-line run.
			start := i
			for i < len(lines) && isPipeLine(lines[i]) {
				i++
			}
			run := lines[start:i]
			if len(run) >= 2 {
				segs = append(segs, richSegment{kind: segRichTable, lines: run})
			} else {
				// Solo pipe line — treat as prose.
				segs = append(segs, richSegment{kind: segRichProse, lines: run})
			}
		} else {
			// Collect prose lines until the next table run.
			start := i
			for i < len(lines) && !isPipeLine(lines[i]) {
				i++
			}
			segs = append(segs, richSegment{kind: segRichProse, lines: lines[start:i]})
		}
	}
	return segs
}

// emitProseBlocks walks prose segment lines and emits:
//   - blockHeader for leading H1 (only when NOT inside a code fence)
//   - blockContext for tool lines (🔧) (only when NOT inside a code fence)
//   - blockMarkdown for accumulated prose text (verbatim GFM, chunked at 12K cumulative)
//
// Returns the blocks produced, fallback lines, and capHit=true when the
// cumulative markdown budget is exhausted.
func emitProseBlocks(lines []string, cumUsed *int) (blocks []any, fallbackLines []string, capHit bool) {
	var accum strings.Builder
	inCodeFence := false

	flushAccum := func() {
		raw := strings.TrimSpace(accum.String())
		accum.Reset()
		if raw == "" {
			return
		}
		chunks, hit := chunkMarkdown(raw, cumUsed)
		for _, c := range chunks {
			blocks = append(blocks, c)
		}
		if hit {
			capHit = true
		}
	}

	for _, rawLine := range lines {
		line := strings.TrimRight(rawLine, "\r")

		// Track code-fence state.
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			inCodeFence = !inCodeFence
			if accum.Len() > 0 {
				accum.WriteByte('\n')
			}
			accum.WriteString(line)
			fallbackLines = append(fallbackLines, stripForFallback(line))
			continue
		}
		if inCodeFence {
			if accum.Len() > 0 {
				accum.WriteByte('\n')
			}
			accum.WriteString(line)
			fallbackLines = append(fallbackLines, stripForFallback(line))
			continue
		}

		// H1 → header block (promoted for visual hierarchy; NOT inside fence).
		if m := reH1.FindStringSubmatch(line); m != nil {
			flushAccum()
			if capHit {
				return blocks, fallbackLines, capHit
			}
			inner := stripHeaderMarkup(m[1])
			inner = truncateHeader(inner, maxHeaderChars)
			blocks = append(blocks, blockHeader{
				Type: "header",
				Text: plainTextField{Type: "plain_text", Text: inner},
			})
			fallbackLines = append(fallbackLines, inner)
			continue
		}

		// Tool lines → context block (unchanged from Tier-2).
		if strings.HasPrefix(line, toolLinePrefix) {
			flushAccum()
			if capHit {
				return blocks, fallbackLines, capHit
			}
			escaped := htmlEscapeForContext(line)
			blocks = append(blocks, blockContext{
				Type:     "context",
				Elements: []mrkdwnField{{Type: "mrkdwn", Text: escaped}},
			})
			fallbackLines = append(fallbackLines, line)
			continue
		}

		// Ordinary prose line: accumulate verbatim (no Mrkdwnify — markdown block
		// takes raw GFM; running Mrkdwnify would double-convert [l](u) links).
		if accum.Len() > 0 {
			accum.WriteByte('\n')
		}
		accum.WriteString(line)
		fallbackLines = append(fallbackLines, stripForFallback(line))
	}

	flushAccum()
	return blocks, fallbackLines, capHit
}

// chunkMarkdown splits prose text into blockMarkdown slices honouring the 12K
// CUMULATIVE budget shared across all markdown blocks in the payload.
// cumUsed is updated in-place. capHit=true when budget is exhausted.
// Uses splitSection for paragraph/sentence/rune-boundary splitting.
func chunkMarkdown(text string, cumUsed *int) (blocks []blockMarkdown, capHit bool) {
	remaining := text
	for len(remaining) > 0 {
		budget := maxMarkdownCumulative - *cumUsed
		if budget <= 0 {
			// Cumulative cap exhausted — signal cap hit (fail-soft to Tier-2).
			capHit = true
			return blocks, capHit
		}
		chunk := remaining
		if len(chunk) > budget {
			// Split at paragraph/sentence/rune boundary (reuse Tier-2 primitive).
			parts := splitSection(remaining, budget)
			if len(parts) == 0 {
				capHit = true
				return blocks, capHit
			}
			chunk = parts[0]
		}
		blocks = append(blocks, blockMarkdown{Type: "markdown", Text: chunk})
		*cumUsed += len(chunk)
		remaining = remaining[len(chunk):]
	}
	return blocks, capHit
}
