// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package tls

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type connectBpfConnInfo struct {
	_          structs.HostLayout
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
}

type connectBpfPidFdKey struct {
	_   structs.HostLayout
	Pid uint32
	Fd  uint32
}

type connectBpfSslReadArgs struct {
	_      structs.HostLayout
	BufPtr uint64
	Fd     uint32
	_      [4]byte
}

// loadConnectBpf returns the embedded CollectionSpec for connectBpf.
func loadConnectBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connectBpf: %w", err)
	}

	return spec, err
}

// loadConnectBpfObjects loads connectBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectBpfObjects
//	*connectBpfPrograms
//	*connectBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnectBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectBpfSpecs struct {
	connectBpfProgramSpecs
	connectBpfMapSpecs
	connectBpfVariableSpecs
}

// connectBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectBpfProgramSpecs struct {
	KprobeAccept4 *ebpf.ProgramSpec `ebpf:"kprobe__accept4"`
	KprobeConnect *ebpf.ProgramSpec `ebpf:"kprobe__connect"`
}

// connectBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectBpfMapSpecs struct {
	ConnMap        *ebpf.MapSpec `ebpf:"conn_map"`
	LibEnabled     *ebpf.MapSpec `ebpf:"lib_enabled"`
	SslReadArgsMap *ebpf.MapSpec `ebpf:"ssl_read_args_map"`
	TlsEvents      *ebpf.MapSpec `ebpf:"tls_events"`
}

// connectBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectBpfVariableSpecs struct {
}

// connectBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectBpfObjects struct {
	connectBpfPrograms
	connectBpfMaps
	connectBpfVariables
}

func (o *connectBpfObjects) Close() error {
	return _ConnectBpfClose(
		&o.connectBpfPrograms,
		&o.connectBpfMaps,
	)
}

// connectBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectBpfMaps struct {
	ConnMap        *ebpf.Map `ebpf:"conn_map"`
	LibEnabled     *ebpf.Map `ebpf:"lib_enabled"`
	SslReadArgsMap *ebpf.Map `ebpf:"ssl_read_args_map"`
	TlsEvents      *ebpf.Map `ebpf:"tls_events"`
}

func (m *connectBpfMaps) Close() error {
	return _ConnectBpfClose(
		m.ConnMap,
		m.LibEnabled,
		m.SslReadArgsMap,
		m.TlsEvents,
	)
}

// connectBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnectBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectBpfVariables struct {
}

// connectBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectBpfPrograms struct {
	KprobeAccept4 *ebpf.Program `ebpf:"kprobe__accept4"`
	KprobeConnect *ebpf.Program `ebpf:"kprobe__connect"`
}

func (p *connectBpfPrograms) Close() error {
	return _ConnectBpfClose(
		p.KprobeAccept4,
		p.KprobeConnect,
	)
}

func _ConnectBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connectbpf_x86_bpfel.o
var _ConnectBpfBytes []byte
