// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package tls

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type opensslBpfConnInfo struct {
	_          structs.HostLayout
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
}

type opensslBpfPidFdKey struct {
	_   structs.HostLayout
	Pid uint32
	Fd  uint32
}

type opensslBpfSslReadArgs struct {
	_      structs.HostLayout
	BufPtr uint64
	Fd     uint32
	_      [4]byte
}

// loadOpensslBpf returns the embedded CollectionSpec for opensslBpf.
func loadOpensslBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpensslBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load opensslBpf: %w", err)
	}

	return spec, err
}

// loadOpensslBpfObjects loads opensslBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*opensslBpfObjects
//	*opensslBpfPrograms
//	*opensslBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpensslBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpensslBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// opensslBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslBpfSpecs struct {
	opensslBpfProgramSpecs
	opensslBpfMapSpecs
	opensslBpfVariableSpecs
}

// opensslBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslBpfProgramSpecs struct {
	UprobeSslReadEntry       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslWriteEntry      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteExEntry    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex_entry"`
	UretprobeSslReadExReturn *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex_return"`
	UretprobeSslReadReturn   *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_return"`
}

// opensslBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslBpfMapSpecs struct {
	ConnMap        *ebpf.MapSpec `ebpf:"conn_map"`
	LibEnabled     *ebpf.MapSpec `ebpf:"lib_enabled"`
	SslReadArgsMap *ebpf.MapSpec `ebpf:"ssl_read_args_map"`
	TlsEvents      *ebpf.MapSpec `ebpf:"tls_events"`
}

// opensslBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensslBpfVariableSpecs struct {
}

// opensslBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpensslBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslBpfObjects struct {
	opensslBpfPrograms
	opensslBpfMaps
	opensslBpfVariables
}

func (o *opensslBpfObjects) Close() error {
	return _OpensslBpfClose(
		&o.opensslBpfPrograms,
		&o.opensslBpfMaps,
	)
}

// opensslBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpensslBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslBpfMaps struct {
	ConnMap        *ebpf.Map `ebpf:"conn_map"`
	LibEnabled     *ebpf.Map `ebpf:"lib_enabled"`
	SslReadArgsMap *ebpf.Map `ebpf:"ssl_read_args_map"`
	TlsEvents      *ebpf.Map `ebpf:"tls_events"`
}

func (m *opensslBpfMaps) Close() error {
	return _OpensslBpfClose(
		m.ConnMap,
		m.LibEnabled,
		m.SslReadArgsMap,
		m.TlsEvents,
	)
}

// opensslBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpensslBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslBpfVariables struct {
}

// opensslBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpensslBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensslBpfPrograms struct {
	UprobeSslReadEntry       *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry     *ebpf.Program `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslWriteEntry      *ebpf.Program `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteExEntry    *ebpf.Program `ebpf:"uprobe_ssl_write_ex_entry"`
	UretprobeSslReadExReturn *ebpf.Program `ebpf:"uretprobe_ssl_read_ex_return"`
	UretprobeSslReadReturn   *ebpf.Program `ebpf:"uretprobe_ssl_read_return"`
}

func (p *opensslBpfPrograms) Close() error {
	return _OpensslBpfClose(
		p.UprobeSslReadEntry,
		p.UprobeSslReadExEntry,
		p.UprobeSslWriteEntry,
		p.UprobeSslWriteExEntry,
		p.UretprobeSslReadExReturn,
		p.UretprobeSslReadReturn,
	)
}

func _OpensslBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed opensslbpf_x86_bpfel.o
var _OpensslBpfBytes []byte
