// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package exec

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type execbpfExecEvent struct {
	_ structs.HostLayout
	H struct {
		_         structs.HostLayout
		TsNs      uint64
		CgroupId  uint64
		Pid       uint32
		Ppid      uint32
		Uid       uint32
		Ret       int32
		Kind      uint8
		Truncated uint8
		Nargs     uint8
		Pad       uint8
		Comm      [16]int8
		Pad2      [4]int8
	}
	Args [20][128]int8
}

// loadExecbpf returns the embedded CollectionSpec for execbpf.
func loadExecbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execbpf: %w", err)
	}

	return spec, err
}

// loadExecbpfObjects loads execbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execbpfObjects
//	*execbpfPrograms
//	*execbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execbpfSpecs struct {
	execbpfProgramSpecs
	execbpfMapSpecs
	execbpfVariableSpecs
}

// execbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execbpfProgramSpecs struct {
	TpEnterExecve   *ebpf.ProgramSpec `ebpf:"tp_enter_execve"`
	TpEnterExecveat *ebpf.ProgramSpec `ebpf:"tp_enter_execveat"`
	TpExitExecve    *ebpf.ProgramSpec `ebpf:"tp_exit_execve"`
	TpProcessExit   *ebpf.ProgramSpec `ebpf:"tp_process_exit"`
}

// execbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execbpfMapSpecs struct {
	ExecEvents *ebpf.MapSpec `ebpf:"exec_events"`
	Inflight   *ebpf.MapSpec `ebpf:"inflight"`
	Scratch    *ebpf.MapSpec `ebpf:"scratch"`
}

// execbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execbpfVariableSpecs struct {
}

// execbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type execbpfObjects struct {
	execbpfPrograms
	execbpfMaps
	execbpfVariables
}

func (o *execbpfObjects) Close() error {
	return _ExecbpfClose(
		&o.execbpfPrograms,
		&o.execbpfMaps,
	)
}

// execbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type execbpfMaps struct {
	ExecEvents *ebpf.Map `ebpf:"exec_events"`
	Inflight   *ebpf.Map `ebpf:"inflight"`
	Scratch    *ebpf.Map `ebpf:"scratch"`
}

func (m *execbpfMaps) Close() error {
	return _ExecbpfClose(
		m.ExecEvents,
		m.Inflight,
		m.Scratch,
	)
}

// execbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type execbpfVariables struct {
}

// execbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type execbpfPrograms struct {
	TpEnterExecve   *ebpf.Program `ebpf:"tp_enter_execve"`
	TpEnterExecveat *ebpf.Program `ebpf:"tp_enter_execveat"`
	TpExitExecve    *ebpf.Program `ebpf:"tp_exit_execve"`
	TpProcessExit   *ebpf.Program `ebpf:"tp_process_exit"`
}

func (p *execbpfPrograms) Close() error {
	return _ExecbpfClose(
		p.TpEnterExecve,
		p.TpEnterExecveat,
		p.TpExitExecve,
		p.TpProcessExit,
	)
}

func _ExecbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execbpf_x86_bpfel.o
var _ExecbpfBytes []byte
