package main

import (
	"encoding/binary"
	"net"

	"golang.org/x/net/bpf"
)

// buildBPFProgram assembles the classic BPF instruction list restricting a
// capture to the requested host and/or port. AF_PACKET pulls every frame off
// the wire by default; without a filter a "just this host" request would
// still burn through --max-size on unrelated traffic before the operator ever
// sees the packets they asked for.
//
// Both clauses are IPv4-only (Ethernet + IPv4 + TCP/UDP) and match either
// source or destination, mirroring how "host"/"port" read in a tcpdump
// expression. Returns nil when neither flag is set, or when --host cannot be
// resolved — the filter is a narrowing convenience, not a precondition, so an
// unresolvable host is dropped rather than failing the whole capture.
//
// The instruction offsets below are hand-derived, not generated by a general
// assembler, because the program has exactly four possible shapes
// (neither/host/port/both) and backpatching machinery would be more code than
// the filter itself. ethertypeLen/hostLen/portLen are the fixed instruction
// counts of each block; every jump target is computed from them so the shape
// stays consistent if a block's instruction count changes.
//
// Deliberately kept free of any Linux-specific type (unix.SockFilter,
// AF_PACKET, ...) and the //go:build linux constraint that the rest of the
// capture daemon carries: bpf.Instruction and bpf.Assemble are pure Go, which
// is what lets capture_filter_test.go exercise these hand-derived jump
// offsets through bpf.NewVM's pure-Go interpreter in an ordinary `go test` on
// any platform, without a live socket or CAP_NET_RAW. The Linux-only
// buildFilter in capture_daemon_linux.go just assembles and installs whatever
// this returns.
func buildBPFProgram(req captureReq) []bpf.Instruction {
	var hostIP net.IP
	if req.Host != "" {
		if addr, err := net.ResolveIPAddr("ip4", req.Host); err == nil {
			hostIP = addr.IP.To4()
		}
	}
	wantHost := hostIP != nil
	wantPort := req.Port > 0
	if !wantHost && !wantPort {
		return nil
	}

	const (
		ethertypeLen = 2 // load ethertype, jump-if-not-IPv4
		hostLen      = 4 // load src, jump-if-match; load dst, jump-if-match
		portLen      = 8 // load proto, jump TCP, jump UDP, X=IHL*4, load+jump srcport, load+jump dstport
	)
	hostBlockStart := ethertypeLen
	portBlockStart := ethertypeLen
	if wantHost {
		portBlockStart += hostLen
	}
	acceptIdx := ethertypeLen
	if wantHost {
		acceptIdx += hostLen
	}
	if wantPort {
		acceptIdx += portLen
	}
	rejectIdx := acceptIdx + 1

	prog := make([]bpf.Instruction, 0, rejectIdx+1)

	// Ethertype gate: every subsequent offset assumes an IPv4 payload.
	prog = append(prog, bpf.LoadAbsolute{Off: 12, Size: 2})
	prog = append(prog, bpf.JumpIf{
		Cond: bpf.JumpEqual, Val: ethTypeIPv4,
		SkipTrue: 0, SkipFalse: uint8(rejectIdx - 2),
	})

	if wantHost {
		hostVal := binary.BigEndian.Uint32(hostIP)
		matchTarget := portBlockStart
		if !wantPort {
			matchTarget = acceptIdx
		}
		prog = append(prog, bpf.LoadAbsolute{Off: 26, Size: 4}) // src IP
		prog = append(prog, bpf.JumpIf{
			Cond: bpf.JumpEqual, Val: hostVal,
			SkipTrue: uint8(matchTarget - (hostBlockStart + 2)), SkipFalse: 0,
		})
		prog = append(prog, bpf.LoadAbsolute{Off: 30, Size: 4}) // dst IP
		prog = append(prog, bpf.JumpIf{
			Cond: bpf.JumpEqual, Val: hostVal,
			SkipTrue: 0, SkipFalse: uint8(rejectIdx - (hostBlockStart + 4)),
		})
	}

	if wantPort {
		portVal := uint32(req.Port)
		tcpCheck := portBlockStart + 1
		udpCheck := portBlockStart + 2
		srcPortCheck := portBlockStart + 5
		dstPortCheck := portBlockStart + 7
		prog = append(prog, bpf.LoadAbsolute{Off: 23, Size: 1}) // IP protocol
		prog = append(prog, bpf.JumpIf{
			Cond: bpf.JumpEqual, Val: ipProtoTCP,
			SkipTrue: uint8((portBlockStart + 3) - (tcpCheck + 1)), SkipFalse: 0,
		})
		prog = append(prog, bpf.JumpIf{
			Cond: bpf.JumpEqual, Val: ipProtoUDP,
			SkipTrue: 0, SkipFalse: uint8(rejectIdx - (udpCheck + 1)),
		})
		prog = append(prog, bpf.LoadMemShift{Off: 14})          // X = IHL*4 (IP header starts at 14)
		prog = append(prog, bpf.LoadIndirect{Off: 14, Size: 2}) // src port
		prog = append(prog, bpf.JumpIf{
			Cond: bpf.JumpEqual, Val: portVal,
			SkipTrue: uint8(acceptIdx - (srcPortCheck + 1)), SkipFalse: 0,
		})
		prog = append(prog, bpf.LoadIndirect{Off: 16, Size: 2}) // dst port
		prog = append(prog, bpf.JumpIf{
			Cond: bpf.JumpEqual, Val: portVal,
			SkipTrue: 0, SkipFalse: uint8(rejectIdx - (dstPortCheck + 1)),
		})
	}

	prog = append(prog, bpf.RetConstant{Val: 0xffff}) // ACCEPT: keep the whole frame
	prog = append(prog, bpf.RetConstant{Val: 0})       // REJECT: drop it

	return prog
}

// ethTypeIPv4, ipProtoTCP, ipProtoUDP mirror unix.ETH_P_IP / unix.IPPROTO_TCP
// / unix.IPPROTO_UDP. Redeclared as plain constants (rather than imported
// from golang.org/x/sys/unix) so this file stays buildable on every platform
// — the unix package's own constants for these are fine on any Unix, but the
// point of keeping this file build-tag-free is that it must also compile
// where a Linux-only capture_daemon_linux.go const wouldn't be visible.
const (
	ethTypeIPv4 = 0x0800
	ipProtoTCP  = 6
	ipProtoUDP  = 17
)
