// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfIp4TrieKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	BpfSockops   *ebpf.ProgramSpec `ebpf:"bpf_sockops"`
	Connect4     *ebpf.ProgramSpec `ebpf:"connect4"`
	EgressFilter *ebpf.ProgramSpec `ebpf:"egress_filter"`
	Sendmsg4     *ebpf.ProgramSpec `ebpf:"sendmsg4"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	AllowedCidrs       *ebpf.MapSpec `ebpf:"allowed_cidrs"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	HttpProxyIps       *ebpf.MapSpec `ebpf:"http_proxy_ips"`
	SockToOriginalIp   *ebpf.MapSpec `ebpf:"sock_to_original_ip"`
	SockToOriginalPort *ebpf.MapSpec `ebpf:"sock_to_original_port"`
	SocketPidMap       *ebpf.MapSpec `ebpf:"socket_pid_map"`
	SrcPortToSock      *ebpf.MapSpec `ebpf:"src_port_to_sock"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	ConstDnsProxyPort     *ebpf.VariableSpec `ebpf:"const_dns_proxy_port"`
	ConstFirewallMode     *ebpf.VariableSpec `ebpf:"const_firewall_mode"`
	ConstHttpProxyPid     *ebpf.VariableSpec `ebpf:"const_http_proxy_pid"`
	ConstHttpProxyPort    *ebpf.VariableSpec `ebpf:"const_http_proxy_port"`
	ConstHttpsProxyPort   *ebpf.VariableSpec `ebpf:"const_https_proxy_port"`
	ConstMitmProxyAddress *ebpf.VariableSpec `ebpf:"const_mitm_proxy_address"`
	ConstProxyPid         *ebpf.VariableSpec `ebpf:"const_proxy_pid"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	AllowedCidrs       *ebpf.Map `ebpf:"allowed_cidrs"`
	Events             *ebpf.Map `ebpf:"events"`
	HttpProxyIps       *ebpf.Map `ebpf:"http_proxy_ips"`
	SockToOriginalIp   *ebpf.Map `ebpf:"sock_to_original_ip"`
	SockToOriginalPort *ebpf.Map `ebpf:"sock_to_original_port"`
	SocketPidMap       *ebpf.Map `ebpf:"socket_pid_map"`
	SrcPortToSock      *ebpf.Map `ebpf:"src_port_to_sock"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.AllowedCidrs,
		m.Events,
		m.HttpProxyIps,
		m.SockToOriginalIp,
		m.SockToOriginalPort,
		m.SocketPidMap,
		m.SrcPortToSock,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	ConstDnsProxyPort     *ebpf.Variable `ebpf:"const_dns_proxy_port"`
	ConstFirewallMode     *ebpf.Variable `ebpf:"const_firewall_mode"`
	ConstHttpProxyPid     *ebpf.Variable `ebpf:"const_http_proxy_pid"`
	ConstHttpProxyPort    *ebpf.Variable `ebpf:"const_http_proxy_port"`
	ConstHttpsProxyPort   *ebpf.Variable `ebpf:"const_https_proxy_port"`
	ConstMitmProxyAddress *ebpf.Variable `ebpf:"const_mitm_proxy_address"`
	ConstProxyPid         *ebpf.Variable `ebpf:"const_proxy_pid"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	BpfSockops   *ebpf.Program `ebpf:"bpf_sockops"`
	Connect4     *ebpf.Program `ebpf:"connect4"`
	EgressFilter *ebpf.Program `ebpf:"egress_filter"`
	Sendmsg4     *ebpf.Program `ebpf:"sendmsg4"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.BpfSockops,
		p.Connect4,
		p.EgressFilter,
		p.Sendmsg4,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
