//go:build linux && amd64

package ebpf

import (
	"encoding/binary"
	"fmt"
	"net"
	"os"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
)

// Config holds the runtime parameters injected into BPF volatile constants at
// program load time. All values are written via CollectionSpec.Variables before
// Enforcer manages the full lifecycle of BPF network enforcement for a single
// sandbox: load programs, attach to cgroup, pin to bpffs, and tear down.
//
// Link fields (connectLink, sendmsgLink, sockopsLink, egressLink) MUST be
// stored as struct fields; storing them only in local variables causes the
// cilium/ebpf GC finalizer to detach the programs immediately after attachment.
type Enforcer struct {
	config      Config
	cgroupPath  string
	objs        *bpfObjects // generated by bpf2go
	connectLink link.Link   // cgroup/connect4
	sendmsgLink link.Link   // cgroup/sendmsg4
	sockopsLink link.Link   // sockops
	egressLink  link.Link   // cgroup_skb/egress
	pinPath     string      // /sys/fs/bpf/km/{sandbox-id}/
	closed      bool
}

// NewEnforcer creates a new Enforcer for the given Config:
//  1. Removes memlock rlimit for kernels < 5.11 compatibility.
//  2. Creates the sandbox cgroup under km.slice.
//  3. Ensures the bpffs pin directory exists.
//  4. Loads the BPF CollectionSpec, injects volatile constants, and loads
//     programs + maps into the kernel with pin-on-creation for maps.
//  5. Attaches all four BPF programs to the sandbox cgroup.
//  6. Pins all four program links to bpffs so they survive km process exit.
func NewEnforcer(cfg Config) (*Enforcer, error) {
	// Step 1: remove memlock (required for kernels < 5.11; safe no-op otherwise).
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("remove memlock: %w", err)
	}

	// Step 2: create sandbox cgroup.
	cgroupPath, err := CreateSandboxCgroup(cfg.SandboxID)
	if err != nil {
		return nil, fmt.Errorf("create sandbox cgroup: %w", err)
	}

	// Step 3: ensure bpffs pin directory.
	pinPath := PinPath(cfg.SandboxID)
	if err := os.MkdirAll(pinPath, 0o700); err != nil {
		return nil, fmt.Errorf("create bpffs pin dir %s: %w", pinPath, err)
	}

	// Step 4: load CollectionSpec, inject volatile constants, load objects.
	spec, err := loadBpf()
	if err != nil {
		return nil, fmt.Errorf("load bpf spec: %w", err)
	}

	// Populate volatile constants — these are compiled-in global variables
	// declared volatile in C so the verifier doesn't optimize them away.
	if err := spec.Variables["const_dns_proxy_port"].Set(cfg.DNSProxyPort); err != nil {
		return nil, fmt.Errorf("set const_dns_proxy_port: %w", err)
	}
	if err := spec.Variables["const_proxy_pid"].Set(cfg.ProxyPID); err != nil {
		return nil, fmt.Errorf("set const_proxy_pid: %w", err)
	}
	if err := spec.Variables["const_http_proxy_pid"].Set(cfg.HTTPProxyPID); err != nil {
		return nil, fmt.Errorf("set const_http_proxy_pid: %w", err)
	}
	if err := spec.Variables["const_http_proxy_port"].Set(cfg.HTTPProxyPort); err != nil {
		return nil, fmt.Errorf("set const_http_proxy_port: %w", err)
	}
	if err := spec.Variables["const_https_proxy_port"].Set(cfg.HTTPSProxyPort); err != nil {
		return nil, fmt.Errorf("set const_https_proxy_port: %w", err)
	}
	if err := spec.Variables["const_firewall_mode"].Set(cfg.FirewallMode); err != nil {
		return nil, fmt.Errorf("set const_firewall_mode: %w", err)
	}
	if err := spec.Variables["const_mitm_proxy_address"].Set(cfg.MITMProxyAddr); err != nil {
		return nil, fmt.Errorf("set const_mitm_proxy_address: %w", err)
	}

	var objs bpfObjects
	if err := spec.LoadAndAssign(&objs, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{PinPath: pinPath},
	}); err != nil {
		return nil, fmt.Errorf("load bpf objects: %w", err)
	}

	// Step 5: attach all four programs to the sandbox cgroup.
	connectLink, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupPath,
		Attach:  ebpf.AttachCGroupInet4Connect,
		Program: objs.Connect4,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach connect4: %w", err)
	}

	sendmsgLink, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupPath,
		Attach:  ebpf.AttachCGroupUDP4Sendmsg,
		Program: objs.Sendmsg4,
	})
	if err != nil {
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("attach sendmsg4: %w", err)
	}

	sockopsLink, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupPath,
		Attach:  ebpf.AttachCGroupSockOps,
		Program: objs.BpfSockops,
	})
	if err != nil {
		sendmsgLink.Close()
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("attach sockops: %w", err)
	}

	egressLink, err := link.AttachCgroup(link.CgroupOptions{
		Path:    cgroupPath,
		Attach:  ebpf.AttachCGroupInetEgress,
		Program: objs.EgressFilter,
	})
	if err != nil {
		sockopsLink.Close()
		sendmsgLink.Close()
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("attach egress: %w", err)
	}

	// Step 6: pin all four links so programs stay active after km exits.
	if err := connectLink.Pin(pinPath + "connect4_link"); err != nil {
		egressLink.Close()
		sockopsLink.Close()
		sendmsgLink.Close()
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("pin connect4_link: %w", err)
	}
	if err := sendmsgLink.Pin(pinPath + "sendmsg4_link"); err != nil {
		egressLink.Close()
		sockopsLink.Close()
		sendmsgLink.Close()
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("pin sendmsg4_link: %w", err)
	}
	if err := sockopsLink.Pin(pinPath + "sockops_link"); err != nil {
		egressLink.Close()
		sockopsLink.Close()
		sendmsgLink.Close()
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("pin sockops_link: %w", err)
	}
	if err := egressLink.Pin(pinPath + "egress_link"); err != nil {
		egressLink.Close()
		sockopsLink.Close()
		sendmsgLink.Close()
		connectLink.Close()
		objs.Close()
		return nil, fmt.Errorf("pin egress_link: %w", err)
	}

	return &Enforcer{
		config:      cfg,
		cgroupPath:  cgroupPath,
		objs:        &objs,
		connectLink: connectLink,
		sendmsgLink: sendmsgLink,
		sockopsLink: sockopsLink,
		egressLink:  egressLink,
		pinPath:     pinPath,
	}, nil
}

// AllowCIDR parses a CIDR string (e.g. "10.0.0.0/8") and inserts the prefix
// into the BPF allowed_cidrs LPM_TRIE map so the sandbox may connect to
// any address within that range.
func (e *Enforcer) AllowCIDR(cidr string) error {
	_, ipNet, err := net.ParseCIDR(cidr)
	if err != nil {
		return fmt.Errorf("parse cidr %q: %w", cidr, err)
	}
	ones, _ := ipNet.Mask.Size()
	key := LpmKey{
		PrefixLen: uint32(ones),
		Addr:      [4]byte(ipNet.IP.To4()),
	}
	value := uint32(1)
	if err := e.objs.AllowedCidrs.Put(&key, &value); err != nil {
		return fmt.Errorf("put cidr %s into allowed_cidrs: %w", cidr, err)
	}
	return nil
}

// AllowIP inserts a single IPv4 address as a /32 entry into the BPF
// allowed_cidrs map.
func (e *Enforcer) AllowIP(ip net.IP) error {
	v4 := ip.To4()
	if v4 == nil {
		return fmt.Errorf("AllowIP: %v is not an IPv4 address", ip)
	}
	key := LpmKey{
		PrefixLen: 32,
		Addr:      [4]byte{v4[0], v4[1], v4[2], v4[3]},
	}
	value := uint32(1)
	if err := e.objs.AllowedCidrs.Put(&key, &value); err != nil {
		return fmt.Errorf("put ip %v into allowed_cidrs: %w", ip, err)
	}
	return nil
}

// MarkForProxy inserts an IPv4 address into the http_proxy_ips BPF map so
// connections to that IP are redirected to the MITM HTTP proxy for L7
// inspection.
func (e *Enforcer) MarkForProxy(ip net.IP) error {
	v4 := ip.To4()
	if v4 == nil {
		return fmt.Errorf("MarkForProxy: %v is not an IPv4 address", ip)
	}
	// The BPF map key must match the in-memory representation of ctx->user_ip4,
	// which stores network-byte-order IP bytes as a native __u32. On x86 (LE),
	// bytes {0x8c,0x52,0x72,0x03} (140.82.114.3 in NBO) become __u32 = 0x0372528c.
	// Use NativeEndian so the Go uint32 matches the kernel's interpretation.
	ipU32 := binary.NativeEndian.Uint32(v4)
	value := uint32(1)
	if err := e.objs.HttpProxyIps.Put(&ipU32, &value); err != nil {
		return fmt.Errorf("put ip %v into http_proxy_ips: %w", ip, err)
	}
	return nil
}

// Events returns the BPF ring buffer map for userspace consumers. The caller
// should use a cilium/ebpf ringbuf.Reader to consume events asynchronously.
func (e *Enforcer) Events() *ebpf.Map {
	return e.objs.Events
}

// Close unpins links, closes all links and BPF objects, and removes the
// sandbox cgroup. It is idempotent — calling it multiple times is safe.
func (e *Enforcer) Close() error {
	if e.closed {
		return nil
	}
	e.closed = true

	// Unpin links (ignore errors — files may already be removed).
	for _, name := range []string{"connect4_link", "sendmsg4_link", "sockops_link", "egress_link"} {
		_ = os.Remove(e.pinPath + name)
	}

	// Close links in reverse attachment order.
	var errs []error
	if e.egressLink != nil {
		if err := e.egressLink.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close egress link: %w", err))
		}
	}
	if e.sockopsLink != nil {
		if err := e.sockopsLink.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close sockops link: %w", err))
		}
	}
	if e.sendmsgLink != nil {
		if err := e.sendmsgLink.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close sendmsg4 link: %w", err))
		}
	}
	if e.connectLink != nil {
		if err := e.connectLink.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close connect4 link: %w", err))
		}
	}

	// Close BPF objects (programs + maps).
	if e.objs != nil {
		if err := e.objs.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close bpf objects: %w", err))
		}
	}

	// Remove sandbox cgroup (best-effort).
	if err := RemoveSandboxCgroup(e.config.SandboxID); err != nil {
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs[0]
	}
	return nil
}
